### ISSUE TITLE
Provide Contact Info for Nearby Vessels - AIS

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#1]
**I want to be able to:**
What he does: call pilots along the bay and river

**So that I can:**
To find out conditions they are experience.  Other pilots are the best forecast system they have

QUESTIONS:
Does OM already have AIS functionality?
Is other vessel's contact info available?
Is this feasible?

**Comment by nguyandy** [comment]
I'm 99% OM doesn't have AIS functionality at the moment.

But maybe this can tie in with the AIS functionality Andrew is looking to add for Dubai.
With the AIS endpoint, this is the info we can get about a vessel.
```
    {
        "MMSI": "375673000",
        "IMO": "9357145",
        "SHIP_ID": "420",
        "LAT": "24.489820",
        "LON": "54.007950",
        "SPEED": "5",
        "HEADING": "302",
        "COURSE": "110",
        "STATUS": "0",
        "TIMESTAMP": "2021-04-05T12:04:09",
        "DSRC": "TER",
        "UTC_SECONDS": "59",
        "SHIPNAME": "BOURBON HOMERE",
        "SHIPTYPE": "70",
        "CALLSIGN": "J8B5653",
        "FLAG": "VC",
        "LENGTH": "73.2",
        "WIDTH": "16.5",
        "GRT": "2529",
        "DWT": "3230",
        "DRAUGHT": "47",
        "YEAR_BUILT": "2006",
        "ROT": "4",
        "TYPE_NAME": "Supply Vessel",
        "AIS_TYPE_SUMMARY": "Special Craft",
        "DESTINATION": "OFFSHORE",
        "ETA": "2021-04-03T13:30:00"
    }
```

Can calls be somehow made using the info above?

**Comment by jamesdoyle21** [comment]
JLH - 
This may be way down the road, and certainly another project, but are there any plans to create an APP around OceansMap?  That could provide a much more customized user experience.
