### ISSUE TITLE
Change Model Data at a Station to Load from Get Feature Info Instead of Get Time Series

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#100]
@mpiannucci correct me if I worded this wrong

Get Feature Info should speed up how quickly the time series plots load at a station

**Comment by jamesdoyle21** [comment]
Have we looked at this yet?

**Comment by mpiannucci** [comment]
Yeah I don't think it's necessary anymore short term but good to do long term

**Comment by mpiannucci** [comment]
We are smarter about this now, closing
