### ISSUE TITLE
Permalink Viewable on Mobile Device

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#11]
Google Sheet Row Number: 6

Want to be able to: Animated prediction of passage of fronts that will have a lot of wind and visibility issues
So that he can: put animations on an IPAD to send it with his pilots

Does Oceans Map already have this functionality?: Yes, partially, adding data would drive availability of things like visibility
Located where in OM?: Animation tool in FMIS, permalink to save exact visualization

Notes: Need to make oceans map available on ipad - Matt. Generate quick URL. Assign to Matt - this is similar to MARACOOS Task

**Comment by mpiannucci** [comment]
App looks good and works well on mobile, more functionality can be exposed now
