### ISSUE TITLE
Tropical Cyclones -> Active Tropical Cyclones checkbox

### ISSUE THREAD

**Issue by cpaternostro** [asascience/ott-coops#111]
Going to the Tropical Cyclones tab on the left.  After clicking the checkbox for Active Tropical Cyclones.  I can not uncheck that box.  Hovering over the checked box shows the finger pointer that indicates I can interact with it, but I am not able to actually uncheck the box.

**Comment by jamesdoyle21** [comment]
I actually saw the same thing today.

**Comment by mpiannucci** [comment]
Yeah I noticed as well. Thanks!
