### ISSUE TITLE
For Datasets with both Magnitude and Direction, Create a way to Incorporate both in the Traffic Light Tool

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#115]
Examples are wind and currents.

Matt's thought was to create multiple layers with the two bits of data split

**Comment by jamesdoyle21** [comment]
This could be useful to add to the backlog

**Comment by mpiannucci** [comment]
Background Info: 

Any vector layer with the `-group` postfix will always have a `-mag` for magnitude and a `-dir` for direction that can swap out for `-group` to show those as scalars instead of as one vector. So probably cool to just expand those layers for the traffic light tool, or we can add them all to the catalog but that might get too dense.

**Comment by jamesdoyle21** [comment]
This came up in the meeting today, adding to the current sprint

**Comment by mpiannucci** [comment]
I think the best way to handle this is to add a "Variable" Drop down above the Elevation (or where the elevation is for non 3d layers) where the user picks if the rule is for speed or direction
![ref](https://user-images.githubusercontent.com/1832671/164313774-7a16982e-ac85-4306-bf5e-880f6868a8b7.png)

**Comment by mpiannucci** [comment]
Im gunna steal this one 🥷

**Comment by mpiannucci** [comment]
OK so this is actually an NCWMS Limitation: NCWMS doesnt let directional layers to be requested as raster data. I think theres a workaround but have to find it

**Comment by mpiannucci** [comment]
I reached out to greg williams who i think knows how to do this. In the meantime this is paused here https://github.com/asascience/oceansmap-3/commit/061b8b1b9fb9b1dc3af171ac470b7cc9859675e4

**Comment by mpiannucci** [comment]
This is apparently not possible at the moment without patching ncwms, which we really dont want to do for now. We will haev to solve it elsewhere eventually and then that will be back propoagated into OM when it works. Sorry :(

**Comment by mpiannucci** [comment]
We could calculate it manually with pyxms or add specific layers for speed and direction.
