### ISSUE TITLE
3D Vertical Slider is Covered by Legend Bar

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#119]
![image](https://user-images.githubusercontent.com/82955395/135137767-152aa1a9-7322-4fe5-8529-779e41a3d341.png)

**Comment by nguyandy** [comment]
This bug was included in this PR
https://github.com/asascience/oceansmap-3/pull/93

**Comment by jamesdoyle21** [comment]
Looks like this is still happening 

![image](https://user-images.githubusercontent.com/82955395/137741292-6df057e3-8d79-4b13-8d54-9c80d7cde1bd.png)
