### ISSUE TITLE
Validation Tool - Filter the Comparison Options to Only Show Layers with Data at the Selected Station

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#120]

**Comment by jamesdoyle21** [comment]
![image](https://user-images.githubusercontent.com/82955395/137033942-f32f5776-3dd4-421d-8ee5-a92d619e567b.png)

I am going to leave this open because of the bug we found today. Some stations, like Block Island here, are not showing all the data layers available. Atlantic Wave Height should appear here

**Comment by mpiannucci** [comment]
Yeah I am not sure why atlantic just isnt showing up all of a sudden after working fine for like two weeks...
