### ISSUE TITLE
Replicate Data Layer "View Bounds" Option for Validation Tool

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#123]
When the user is selecting a station to compare data, having that "View Bounds" option to show only stations visible on the map would be helpful

**Comment by jamesdoyle21** [comment]
@mpiannucci Has this been pushed? How do I test this in the Validation tool?

**Comment by mpiannucci** [comment]
Dont think so... I think I got this mixed up with the other auto filtering one.

**Comment by ndellicarpini** [comment]
if you guys want I can try to tackle this

**Comment by jamesdoyle21** [comment]
Have at it Nick. Chime in @mpiannucci if you had other plans for this

**Comment by mpiannucci** [comment]
yeah go ahead, just know that my PR is swapping out the map library probably. Trying to get that done by today

**Comment by ndellicarpini** [comment]
PR: https://github.com/asascience/oceansmap-3/pull/115
