### ISSUE TITLE
Add Option for Streamflows for Any Vector Layer 

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#129]

**Comment by jamesdoyle21** [comment]
@mpiannucci are you still looking at streamlines or are we pushing this behind all the Maracoos stuff?

**Comment by mpiannucci** [comment]
maracoos

**Comment by mpiannucci** [comment]
Work is happening in these places: 

https://github.com/asascience/pyXMS/tree/miannucci-streamlines
https://github.com/mpiannucci/mapbox-gl-streamlines

Fixed a bug in the pyxms and now we can get a static image that looks ready to animate: 

![Screen Shot 2021-12-02 at 11 57 51 AM](https://user-images.githubusercontent.com/1832671/144467860-1ca8111d-d318-46d2-906e-ca9386ac77c2.png)

**Comment by mpiannucci** [comment]
non-randomized particles without animation (sharing these so when i wlak away I remember where i was at lol

![Screen Shot 2021-12-02 at 4 00 46 PM](https://user-images.githubusercontent.com/1832671/144502323-e79de595-f312-4023-a2da-2d4dcddea0f8.png)

**Comment by mpiannucci** [comment]
Closer...... Just needs to figure out how to fix the tile boundaries being so pronounced and some of the random clumping 

![close](https://user-images.githubusercontent.com/1832671/145104683-03935687-333b-47a1-9e93-dd6a70ea63c1.gif)

**Comment by mpiannucci** [comment]
Closer...... Just some quirks because of the tiling I need to figure out the best way to handle. 

![close](https://user-images.githubusercontent.com/1832671/145104981-959610de-afaa-451f-a980-c213d976b08c.gif)

**Comment by mpiannucci** [comment]
Current particles playable here: https://oceansmap.s3.amazonaws.com/demos/vector-particles/index.html

Talked to Kelly today, we want to make sure we can draw tails too

**Comment by mpiannucci** [comment]
Okay updated the demo site with the ability to change more of the options AND added tails, looks pretty good. Last bit of configuration is allowing the color to be changed

**Comment by nguyandy** [comment]
wowwwwwwwwww that's crazy amazing!!! just spent 10 minutes staring at it

**Comment by mpiannucci** [comment]
Ohhhhh baby now got colors live:
![Screen Shot 2021-12-14 at 5 13 02 PM](https://user-images.githubusercontent.com/1832671/146087677-09afb92d-3c1f-4a87-a5ec-ec0585be2342.png)

**Comment by jamesdoyle21** [comment]
Damn, the tails and colors make a huge difference. This is fresh.

**Comment by mpiannucci** [comment]
Yeah it's now really good I think with the colors and tails. Now to integrate with OM
