### ISSUE TITLE
UI issue when accessing chart options in Obs View

### ISSUE THREAD

**Issue by nguyandy** [asascience/ott-coops#130]
When opening the chart option menu, it shouldn't create an overflow in the parent container. 

<img width="1111" alt="Screen Shot 2021-10-12 at 10 51 24 AM" src="https://user-images.githubusercontent.com/43226410/136979288-edd37162-449f-452c-923b-8c2a3e9985c6.png">

<img width="1111" alt="Screen Shot 2021-10-12 at 10 51 29 AM" src="https://user-images.githubusercontent.com/43226410/136979293-20df7fc9-178d-47ab-9daa-83679962ca3f.png">

**Comment by ndellicarpini** [comment]
This also happens with the chart hamburger menu in the validation tool
