### ISSUE TITLE
When User Has Point Selected on Map, Do Not Automatically Open Bottom Drawer When Layer is Activated

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#131]
I noticed this when I was making the video. When a user selects a point on the map when a layer is turned on, the bottom drawer opens with the plots - that is normal. But if the user exits out of that drawer and activates a new layer, the drawer open. This should not be the case. We should only open that drawer when a user selects a new point )virtual station) on the map

**Comment by jamesdoyle21** [comment]
https://user-images.githubusercontent.com/82955395/136985520-c2ad02cc-8421-4e2c-8ba6-47b782bce121.mp4

**Comment by jamesdoyle21** [comment]
For this example, when I turned on Atlantic Wave Height the drawer stayed closed, but then it opened when I turned on Global Wind when it should have stayed closed

**Comment by nguyandy** [comment]
> So this is happening at the useEffect ObservationDrawer.tsx:163. I have pushed a very simple fix to [asascience/oceansmap-3@5988681](https://github.com/asascience/oceansmap-3/commit/5988681ca5bb8b1f135f6ccf26c1de296d99dfca) (this just checks if the drawer is open before updating the elevation on the plot)
> 
> **_However, this changes the functionality, now if you change the elevation slider with the drawer closed, the drawer does not reopen_**. A better change could be to hide the elevation slider when its not appropriate rather than removing it, which would maintain the currentElevation between activations of elevation slider.
> 
> I am open to either my current fix or the fix I described above, just let me know and I'll set up a pr for either.

Nice find @ndellicarpini !
Regarding that change in functionality, I think the change you made _should_ be the way the drawer behaves. If the drawer is not open, changing the elevation slider should not trigger the drawer to open up either.

**Comment by ndellicarpini** [comment]
Yea sorry for posting my elevation slider dissertation in the wrong issue. I created a PR for the basic fix here: https://github.com/asascience/oceansmap-3/pull/95

**Comment by mpiannucci** [comment]
Issue auto closed I think.

**Comment by nguyandy** [comment]
> Issue auto closed I think.

@mpiannucci , I'm guessing because the PR had a linked issue and was merged.
https://github.com/asascience/oceansmap-3/pull/95
