### ISSUE TITLE
Change Data Layer Button Text from "View Bounds" to "Map View"

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#132]
![image](https://user-images.githubusercontent.com/82955395/137035159-08122a29-f4cf-4e48-b4f3-2488ee0501c1.png)

**Comment by ndellicarpini** [comment]
changed in https://github.com/asascience/oceansmap-3/commit/9128873d2f77b47708fe846fc87b65e8c89e6cfe

**Comment by ndellicarpini** [comment]
PR: https://github.com/asascience/oceansmap-3/pull/108
