### ISSUE TITLE
Change Data Layers Button "Reset" to "All"

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#134]
![image](https://user-images.githubusercontent.com/82955395/137035871-979ce482-f900-41a9-9f3c-ff8bc873df04.png)

Keep the highlighted functionality of the button, just change the text

**Comment by ndellicarpini** [comment]
changed in https://github.com/asascience/oceansmap-3/commit/9128873d2f77b47708fe846fc87b65e8c89e6cfe

**Comment by ndellicarpini** [comment]
PR: https://github.com/asascience/oceansmap-3/pull/108
