### ISSUE TITLE
Look at the Accuracy of the Scatter Index and RMS Values Inside the Validation Tool

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#135]
Per our discussion with Chris and Jeff today (Oct 12), lets take a look at the way the Validation tool calculates RMS and Scatter Index. Jeff uses a 0 - 100 scale for Scatter Index and we are using 0-1.

**Comment by jamesdoyle21** [comment]
From Jeff - A description of Scatter Index 

https://incois.gov.in/HYCOM/1BY12_grid/node5.html

**Comment by jamesdoyle21** [comment]
[Jeff Hanson error_stats.txt](https://github.com/asascience/ott-coops/files/7333452/Jeff.Hanson.error_stats.txt)

Here is Jeff's MatLab code he sent us with the error statistics he uses (saved as a .txt)

**Comment by mpiannucci** [comment]
Jeffs own stats use a 0-1 range so for now well leave that as is

**Comment by jamesdoyle21** [comment]
Did we find anything wrong with RMS?
