### ISSUE TITLE
View Map with NOAA Chart Basemap

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#14]
Google Sheet Row Number: 33

Want to be able to: view a chart overlay for the spatial data
So that he can: we think in charts

Does Oceans Map already have this functionality?: Yes
Located where in OM?: Backgrounds -> ENConlineCharts

Notes: All look and feel items can be resolved by making sure the user knows they can save a permalink. MAKE THIS OBVIOUS FOR USER

Need to show scalar speed with direction over the top (clean up what we already have) is backend data ok? Think about what we want to show for the default

"1.  The ENC WMS layer -- Displays continuous ENC coverage for all S-57 charts (features are available based on zoom level), using the S-52 presentation library specification edition 3.4.  (My guess is that this layer might be the one OM uses; it provides the best coverage in one place, with updates as available from OCS).

2.  ENC Direct REST Services -- Significantly more granular control / selection of all S-57 ENC data, also using S-52 display spec, (use the map services, feature access also based on zoom level, and updated as available).

3.  Navigational Chart Data REST Services -- This is also linked on the website, (REST Services via ENC Direct to GIS).  It is more specific navigational data then an overall view like the ENC / RNC layers would be.  I haven't used them, and personally have found the above content much more helpful for local GIS and web maps / applications."

**Comment by mpiannucci** [comment]
For myself....

https://nauticalcharts.noaa.gov/enconline/enconline.html

https://gis.charttools.noaa.gov/arcgis/rest/services/MCS/ENCOnline/MapServer/exts/MaritimeChartService/MapServer/export?bbox=-9404574.512759868%2C4273718.685531777%2C-8018924.0640061945%2C5290025.413611478&size=1133%2C831&dpi=96&format=png&transparent=true&bboxSR=3857&imageSR=3857&layers=show%3A0%2C1%2C2%2C3%2C4%2C5%2C6%2C7&f=image

**Comment by mpiannucci** [comment]
![Screen Shot 2021-06-30 at 4 28 52 PM](https://user-images.githubusercontent.com/1832671/124026911-43d65400-d9c0-11eb-929d-05451c86dc01.png)

**Comment by mpiannucci** [comment]
Have to look reaaaallllyyy hard to see current arrows

**Comment by mpiannucci** [comment]
![Screen Shot 2021-06-30 at 4 30 15 PM](https://user-images.githubusercontent.com/1832671/124027089-74b68900-d9c0-11eb-944f-186ee3f88d01.png)

**Comment by jamesdoyle21** [comment]
JH - We need to expand map view to model errors/validation
