### ISSUE TITLE
Add "Themes" Functionality

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#145]
Replicate "Themes" tab from OceansMap 1. Ask stakeholders to come up with useful themes and what the default view for each should be. @cpaternostro

**Comment by mpiannucci** [comment]
OM1 themes config https://github.com/asascience/OceansMap/blob/master/oceansmap/static/json/themes.json

**Comment by jamesdoyle21** [comment]
We discussed adding themes as a category in the data layers list. The category should go on top (above Waves) and differentiate from the rest of the categories (different color, border, etc)

**Comment by mpiannucci** [comment]
This is blocked by permalink functionality

**Comment by jamesdoyle21** [comment]
I have some notes when we spoke last about the UI for this, I'll make a rough mockup and put it here

**Comment by mpiannucci** [comment]
## Technical details

Could live in the catalog section of the config:

```ts
export interface CatalogTheme {
    id: string, 
    title: string, 
    description: string, 
    // Same utility as OM where user encodes the pieces of the state and it updates the state of the app
    state: Pick<OMState, keyof OMState>,
}

...
catalog?: {
    url: string,
    edsKey?: string,
    themes: { [k: string]: CatalogTheme }
}
```

**Comment by jamesdoyle21** [comment]
For now, let's replicate the Themes from Maracoos' current version of OM https://oceansmap.maracoos.org/#

Winds
Waves
Currents
Water Level
Water Temp
Salinity
Active Tropical Cyclones
Fishing
Offshore Wind

**Comment by ndellicarpini** [comment]
> OM1 themes config https://github.com/asascience/OceansMap/blob/master/oceansmap/static/json/themes.json

any chance you can send me this file? I don't have access to the OM1 repo

**Comment by mpiannucci** [comment]
Here we are from the `maracoos-assets` branch: [themes.txt](https://github.com/asascience/ott-coops/files/7620253/themes.txt)

**Comment by jamesdoyle21** [comment]
I am working on a mockup, but for now here are some notes:

- We are treating themes like another category in the data layers list
- Gray background color slightly darker than other categories to show the user it isn't treated the same
- By default, themes should be minimized
- Only 1 theme can be active at a time
- Remove magnifying glass and settings buttons but keep the info button on the right.
       - Info button (i) will give a 1 sentence description of what is activated for that theme
- Themes turn on and off certain layers. When a theme is activated, the user can manually change settings or layers on and off but once they do, the theme becomes unchecked

@mpiannucci @ndellicarpini chime in if there's anything to add or if this workflow doesn't make sense

**Comment by ndellicarpini** [comment]
Would it make sense for the theme to become checked if the user individually enables all of the layers in a particular theme?

**Comment by jamesdoyle21** [comment]
![image](https://user-images.githubusercontent.com/82955395/143926509-688fb881-f189-4b1a-8f59-ed9225bbacbe.png)

**Comment by jamesdoyle21** [comment]
@ndellicarpini that would make sense if it is simple to include

**Comment by ndellicarpini** [comment]
@mpiannucci @nguyandy  How do you guys feel about the format of the theme json files? I'm definitely not a fan due to strangely named & unused fields. If I could I would want to remake the json file.

My ""Improvements""
```
id -> identifier
nice_name -> title
image_url (delete)
show_name (delete)
active (delete)
parameters -> parameters
default_on_layers -> children
```

Note: the names I chose are to match the catalog json, as from what I've worked on so far using CatalogItem for themes would make things much simpler. Also I could just make these field key changes when I read the json, but just wondering if we should just remake the file.

**Comment by mpiannucci** [comment]
That looks good but I dont think even parameters needs to be there either tbh. The simpler the better

**Comment by mpiannucci** [comment]
> Would it make sense for the theme to become checked if the user individually enables all of the layers in a particular theme?

No

**Comment by ndellicarpini** [comment]
Don't mind me, just using github as a file server.
[themes_clean.txt](https://github.com/asascience/ott-coops/files/7637049/themes_clean.txt)

NOTE: I deleted 'None Selected' as it doesn't really seem to make sense given our implementation

**Comment by nguyandy** [comment]
Don't mind me, just using github as a file server.
[themes_clean2.txt](https://github.com/asascience/ott-coops/files/7637555/themes_clean2.txt)

**Comment by mpiannucci** [comment]
FYI this can only be seen in the maracoos branch for now so we can just sign off on it when deployed and revisit for bugs later

**Comment by ndellicarpini** [comment]
Do we want to update from the themes json I am getting from github? I can probably create a new json with updated layer ids for us to put into s3.

**Comment by mpiannucci** [comment]
Yes please do

**Comment by ndellicarpini** [comment]
So looking at the layers each theme item enables, most of the layers are actually eds layers, and so I'm not sure if they have direct translations to the layers we currently use. Is maracoos going to want to use the same catalog as maracoos OM1? If so maybe we should just leave the themes as they are?

**Comment by jamesdoyle21** [comment]
Am I able to test this?
