### ISSUE TITLE
Add Box Area Zoom

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#151]
Same as MARACOOS version

**Comment by nguyandy** [comment]
Hey @jamesdoyle21, can you elaborate on this functionality?

**Comment by jamesdoyle21** [comment]
Sure, so looking to replicate this button in the MARACOOS version. It allows the user to drag a rectangle over the map, the map then zooms to the extents of that rectangle.

![image](https://user-images.githubusercontent.com/82955395/138747477-f3030857-52d0-4057-9fdf-7195be997de6.png)

**Comment by nguyandy** [comment]
Ahh! Gotcha, thanks

**Comment by mpiannucci** [comment]
https://docs.mapbox.com/mapbox-gl-js/example/using-box-queryrenderedfeatures/

That example lets the user draw a rectangular region and then the system reads the coords of the box drawn and highlights the features that overlap the bounds. We just want to make it even simpler so that the user can draw a rectangle and then the map zooms to the location when the tool is clicked.

**Comment by mpiannucci** [comment]
This is going to need the `onActivate` tool config option that is set to be added with nicks PR https://github.com/asascience/oceansmap-3/pull/120

There is no UI for this plugin, it should just set up the event handlers and then zoom the map. Ideally we use the `flyTo` state object but maybe overkill to do so

**Comment by mpiannucci** [comment]
![boxzoom_desktop](https://user-images.githubusercontent.com/1832671/142032166-39970693-f109-4aff-9e4b-21be203c09f8.gif)

![boxzoom_mobile](https://user-images.githubusercontent.com/1832671/142032185-ba2ff037-8927-4249-af32-f46f243cd687.gif)

**Comment by jamesdoyle21** [comment]
Functionality looks good, and response is fast. Moving this back into In Progress though because the bottom obs drawer opens with each bbox click when a layer is turned on on the map

https://user-images.githubusercontent.com/82955395/142051199-56fe22a7-dfba-45f3-9faf-90c9feacf82f.mp4

**Comment by mpiannucci** [comment]
Good find! Will patch that up
