### ISSUE TITLE
Add Mouse Over Help Tips to Active Layers and Timeslider Buttons

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#153]
List of mouse over tips to add:

- Active Layers Button (top right), "Active Layers Legend"
- Time slider Clock (bottom right), "Active Time"
- Time slider Calendar (bottom right), "Time Slider Range"
- Left Carrot (bottom left), "Back 1 Hour"
- Right Carrot (bottom left), "Forward 1 Hour"
- Any Point in the Time Slider, (bottom), "mm/dd/yy, hr:min AM/PM (show the date and time of which the cursor is hovering over)"

![image](https://user-images.githubusercontent.com/82955395/138943754-d1495091-33b9-4052-8f7a-c49ffb971109.png)

**Comment by ndellicarpini** [comment]
PR: https://github.com/asascience/oceansmap-3/pull/104

**Comment by jamesdoyle21** [comment]
@ndellicarpini round to nearest hour and edit size of box so it never uses 2 lines
