### ISSUE TITLE
Layers don't show if "Show Coastlines" is disabled

### ISSUE THREAD

**Issue by ndellicarpini** [asascience/ott-coops#154]
When loading a layer with "Show Coastlines" is disabled, the layer never shows and the console repeatedly spits the Error `Layer with id 'coastlines-layer' does not exist on this map` until the layer is disabed.

**Comment by mpiannucci** [comment]
This can be fixed by editing the before Id section of MapWmsLayer.tsx

**Comment by mpiannucci** [comment]
Im taking this issue back because it relates directly to the new layer API
