### ISSUE TITLE
Duplicate Stations in Validation Tool

### ISSUE THREAD

**Issue by ndellicarpini** [asascience/ott-coops#156]
Sometimes when scrolling/searching the "Select a Station (Baseline)" combobox, a duplicate key error occurs that will cause weirdness in the dropdown list.

**Comment by ndellicarpini** [comment]
Looking at this a bit more, this could be a backend/data issue? There are different stations being pulled that have the exact same title, for instance there are 2 different stations with the name "Station 44088 - Virginia Beach Offshore, VA (171)" (id:`data.oceansmap.com:44088` & id:`data.oceansmap.com:urn:ioos:station:wmo:44088`). These titles are used as keys for when a user is searching with the station combobox, so it's no surprise this causes an error.

**Comment by mpiannucci** [comment]
```
Warning: Encountered two children with the same key, `Station 44088 - Virginia Beach Offshore, VA (171)`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    in div (created by ResizeObserver)
    in ResizeObserver (created by Filler)
    in div (created by Filler)
    in Filler (created by List)
    in div (created by List)
    in div (created by List)
    in List (created by OptionList)
    in OptionList (created by ForwardRef(Select))
    in div (created by SelectTrigger)
    in div (created by Align)
    in Align (created by CSSMotion)
    in DomWrapper (created by CSSMotion)
    in CSSMotion (created by PopupInner)
    in PopupInner (created by Popup)
    in div (created by Popup)
    in Popup (created by Trigger)
    in ForwardRef (created by Trigger)
    in Trigger (created by SelectTrigger)
    in SelectTrigger (created by ForwardRef(Select))
    in div (created by ForwardRef(Select))
    in ForwardRef(Select) (created by Select)
    in Select (created by ForwardRef(InternalSelect))
    in ForwardRef(InternalSelect) (at ValidationTool.tsx:76)
    in div (at ValidationTool.tsx:74)
    in ValidationInputRow (at ValidationTool.tsx:560)
    in div (at ValidationTool.tsx:547)
    in div (at ValidationTool.tsx:546)
    in ValidationTool (at OceansMap.tsx:284)
    in div (created by Drawer)
    in div (created by Drawer)
    in div (created by DrawerChild)
    in div (created by DrawerChild)
    in div (created by DrawerChild)
    in DrawerChild (created by DrawerWrapper)
    in div (created by DrawerWrapper)
    in DrawerWrapper (created by Drawer)
    in Drawer (created by DrawerWrapper)
    in DrawerWrapper (at OceansMap.tsx:266)
    in div (at OceansMap.tsx:260)
    in MediaQuery (at OceansMap.tsx:259)
    in div (at OceansMap.tsx:242)
    in OceansMap (at App.tsx:15)
    in LocaleProvider (at App.tsx:12)
    in div (at App.tsx:11)
    in App (at src/index.tsx:10)
    in StrictMode (at src/index.tsx:9)
```

**Comment by jamesdoyle21** [comment]
I'm going to close this issue, but did we ever decide if there was a good way to distinguish the duplicate station names in the validation tool?

![image](https://user-images.githubusercontent.com/82955395/141343527-70c72007-b9f2-4eae-8e14-d52d07f190e0.png)

**Comment by ndellicarpini** [comment]
I don't think so. As far as I remember the main issue is that although both of those are technically the same station, they monitor different features. Maybe they can be distinguished in some way by using their source? Maybe something can be added that can successfully get the source of the station data, but I haven't looked into that yet.

**Comment by mpiannucci** [comment]
No thats the source data. Different issue than this being a UI issue. The names are grabbed from the harvested stations so we dont really have control over it. We could add a string with teh source of the data but thats really busy adn probably too much info
