### ISSUE TITLE
Update 'Map View' Filters when Map BBox Moves

### ISSUE THREAD

**Issue by ndellicarpini** [asascience/ott-coops#157]
Currently, the 'Map View' filters don't update when the map is moved. Rather, for the data layer list to update based on the map bbox after the map has been moved, the filter needs to be disabled and re-enabled.

Update the filter so that when the map zoom/bbox changes, the data layer list is automatically updated to be based on the new bbox.

**Comment by ndellicarpini** [comment]
PR: https://github.com/asascience/oceansmap-3/pull/115

**Comment by mpiannucci** [comment]
We decided to filter as user moves around. From my testing perf seems to be unaffected but we can adjust later if needed
