### ISSUE TITLE
Sometimes Layers will never finish loading & will not show on map

### ISSUE THREAD

**Issue by ndellicarpini** [asascience/ott-coops#160]
Occasionally when activating a data layer, the layer will finish receiving responses from the server; however, the layer will never show and the loading spinner will never stop.

This is speculation, but I believe this happens when the last tile that comes in from the server throws an error. This should not normally prevent the layer from finishing loading.

**Comment by ndellicarpini** [comment]
I think this only happens when applying a layer's settings, not when enabling a new layer.

**Comment by ndellicarpini** [comment]
PROOF:

https://user-images.githubusercontent.com/22432482/142933213-32c0e3ad-a3f3-4d2e-be34-2676cd86529a.mp4

**Comment by ndellicarpini** [comment]
I have been unable to recreate this issue as of 11/24. This is probably thanks to the fix @mpiannucci pushed where tiles no longer come in & error, but I'll leave this issue open a little longer in case anyone runs into this again.

**Comment by jamesdoyle21** [comment]
Let's close it. If anyone runs into it again we can always reopen.
