### ISSUE TITLE
Hover information for a Virtual Station does not get removed if station is deleted

### ISSUE THREAD

**Issue by ndellicarpini** [asascience/ott-coops#161]
If selecting / hovering a virtual station and then deleting the virtual station while its still selected, the virtual station will still show its hover details even after the station is deleted. 

Seen here :
![Screenshot 2021-11-08 120028](https://user-images.githubusercontent.com/22432482/140786204-5ee8fc04-8202-4ad5-aadc-0bacabd6da42.png)

**Comment by mpiannucci** [comment]
Great find
