### ISSUE TITLE
Hover Tooltip Weirdness for Point OBS Station Layers

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#164]
Hover Tooltips for data stations and virtual stations is displayed when the user pans the map view. It looks like it shows the station closest to the mouse click. The tooltip then disappears sometime later (few seconds). See video below

UPDATE: This only happens when something is loading

https://user-images.githubusercontent.com/82955395/140803724-5948428d-0f6b-4f49-be9f-79998a80ae44.mp4

**Comment by jamesdoyle21** [comment]
It looks like this only happens when there is a data layer loading in the background. A fix here would be to disable tooltips when something is loading. We need to make sure the loading bar is always spinning when this is happening however. This issue pointed to issue #166

https://user-images.githubusercontent.com/82955395/140804741-cb648c7d-1996-44a4-bebd-65218bad3e57.mp4

**Comment by ndellicarpini** [comment]
This only happens when data is loading, and it actually doesn't open the tooltip nearest to the click, rather it opens the tooltip of the station that the mouse last hovered on.

**Comment by mpiannucci** [comment]
@ndellicarpini make sure this isnt fixed with master before diving too deep.

**Comment by jamesdoyle21** [comment]
Note: The other hover tooltips seem to work fine when a layer is loading, so don't disable those while the loading wheel is spinning.
