### ISSUE TITLE
Excessive # of calls when loading WMS layers + layer disappears after map click

### ISSUE THREAD

**Issue by nguyandy** [asascience/ott-coops#165]
Trying to load the NOAA Puerto Rico (NAM) layer w/ the date range from Oct 1 - Oct 2.

Steps to reproduce:
- set the timeslider range to Oct 1 - Oct 2
- open data layer list, zoom to NOAA Puerto Rico (NAM) first, let the fly over complete.
- enable the layer NOAA Puerto Rico (NAM)
- wait until network activity stops

I have my window set really small to reduce the number of calls.
However we're still making over 50+ calls.

Once all the layers are loaded.
If you click on the map, the layer (Puerto Rico NAM) disappears... sometimes. 

It's weird cause it looks like the WMS layers load successfully within the first 20 calls, but then it shoots off a bunch more.

**Comment by mpiannucci** [comment]
okay I think this is because of the metadata loading not being finished before the layers are added to the map. So it adds the layers to the map before the metadata has been fetched and then immediately fetches again with a specific time (if applicable). I think I can fix/optimize this.
