### ISSUE TITLE
Loading Wheel Stops Spinning if User Hovers Over a Station

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#166]
When either virtual stations or Point OBS stations are turned on, t\if the user activates a layer and then hovers over a station, the spinning bar stops.

https://user-images.githubusercontent.com/82955395/140805370-b4c5f526-4186-4c1e-b03c-a1e6a1133dfa.mp4

**Comment by mpiannucci** [comment]
Thats interesting one, and probably goes back to nicks point about errors not being reset correctly

**Comment by jamesdoyle21** [comment]
Related to this, when the user hovers over a layer in the layer list, the spinning loading button flickers. It looks like it does this because it is showing that is is loading the bounding box that shows on the map when they hover over a layer. This should be able to be fixed but turning off loading to the bounding box display.

UPDATE: This is its own task #167 

https://user-images.githubusercontent.com/82955395/140805788-2a380e5c-0bc5-40ae-b2ef-c7fa82c76785.mp4

**Comment by mpiannucci** [comment]
Yeah in the map loading icon we should try and filter what layers are loading somehow but it is a bit inconsistent with mapbox

**Comment by jamesdoyle21** [comment]
@mpiannucci I'll make an issue specific to that (Issue #168). We can plan to discuss how we want to show the user what is loading in the meeting tomorrow. I know OM1 does it but we probably want to rethink how we want to display that to the user.

**Comment by ndellicarpini** [comment]
PR: https://github.com/asascience/oceansmap-3/pull/133

This isn't fully fixed, check the note in the PR for why.
