### ISSUE TITLE
Unlink Bounding Box to Loading Wheel

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#167]
When a user hovers over a data layer a bounding box on the map is shown. This right now is linked to the loading wheel and causes problems when there is something loading in the background. Unlink the loading wheel to this action.

https://user-images.githubusercontent.com/82955395/140806304-cc3e5ffe-6633-4d4f-ae68-b3d557998565.mp4

**Comment by mpiannucci** [comment]
At the moment all layers are linked with the laoding wheel, even the basemap. Theres some argument to be made that it shows whenever anything is loading but yea those bounding box ones are annoying

**Comment by ndellicarpini** [comment]
PR: https://github.com/asascience/oceansmap-3/pull/133

This isn't fully fixed, check the note in the PR for why.
