### ISSUE TITLE
Show the User What Layers are Loading when Loading Wheel is Activated

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#168]
Right now the loading wheel is activated when a layer is loading but the user does not know what is driving that wheel. Old versions of OceansMap (Like Maracoos) have this capability. We could sync up our loading wheel with a small one next to the data layer that is loading, like how Maracoos does it. Also open to other suggestions.

https://user-images.githubusercontent.com/82955395/140808448-b4ce6465-35db-4105-a32a-4560428b3296.mp4

**Comment by ndellicarpini** [comment]
Would these individual loading spinners make more sense in the Data Layer List or in the Active Layer List?

**Comment by mpiannucci** [comment]
Maybe both, but getting the list of currently loading layers to be accurate is probably the hardest part

**Comment by ndellicarpini** [comment]
PR: https://github.com/asascience/oceansmap-3/pull/133

**Comment by mpiannucci** [comment]
The PR has been merged to track what layers are loading, next is determining the best UI for showing what is currently loading
