### ISSUE TITLE
Allow User to Display Stations on Map for Validation Tool

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#173]
When the user is looking for a station to use in the validation tool, it would be helpful if they had the ability to display the available stations within the bounds of the active map view. A button next to the "Map View" button would most likely be best, but we need to think about how to display stations when the user has a Point OBS layer turned on (thus creating duplicate pins on the map). Feedback welcome here.

![image](https://user-images.githubusercontent.com/82955395/141141564-658f19e5-bc33-491c-9f7c-358cc3482672.png)

**Comment by ndellicarpini** [comment]
Should I also try to add this functionality (https://github.com/asascience/ott-coops/issues/231) to the 'Select a Station (Baseline)' search when 'Show Stations' is enabled?

**Comment by jamesdoyle21** [comment]
Yes, that would be great if we could get that for the validation tool too
