### ISSUE TITLE
Contours Only Showing in Yellow Sections of Traffic Light Layer

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#177]
When the user activates a layer and turns on contours and a traffic light rule from inside the settings button of the layer, contours will only show up inside the yellow areas. For some reason the contour range is set to the low and high values of the traffic light tool.

Steps to reproduce:
1. Activate Atlantic Wave Height
2. Navigate to the settings for Atlantic Wave Height and turn on contours and traffic light
3. Edit range accordingly to see all 3 colors on the map

![image](https://user-images.githubusercontent.com/82955395/141157093-1ba90051-0268-400d-b9d2-9022184ed2ce.png)

**Comment by mpiannucci** [comment]
This is more of a big picture question as this feature (in pyxms) is driven by FMIS and we cant break their spec. Will post details hear as ai Talk through them with OZ

**Comment by mpiannucci** [comment]
This is by design
