### ISSUE TITLE
Allow the User to Turn On/Off Gray Sections of the Traffic Light Tool

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#178]
The way the traffic light tool works currently is it applies a gray cover to the areas outside the bounds of the traffic light. We want to allow the user to turn this off so they can see the basemap behind the gray areas.

Note: the traffic light option within a spatial layer (like Atlantic Wave Height) works so that there is never the gray area outside the bounds of the layer.

Traffic light tool:
![image](https://user-images.githubusercontent.com/82955395/141158585-5558878c-db12-4167-89f2-e63fbad29dca.png)

Traffic light in spatial layer settings:
![image](https://user-images.githubusercontent.com/82955395/141158495-e9b4c023-1d43-4ab9-aa95-6138950c6ffd.png)

**Comment by ndellicarpini** [comment]
@mpiannucci is this pyxms work?

**Comment by mpiannucci** [comment]
Yes this is pyxms. We can discuss but it's not a priority
