### ISSUE TITLE
Validation Tool No Response

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#182]
After selecting all 4 parameters for the validation tool I am getting no response. The layer I am using, Atlantic Wave Height is loading on the map fine. 

Issues/ Solutions could be:

- If the data is loading, the loading wheel should be activated
- If the data is throwing an error, we should display this below the date range in the validation tool
- If selecting the 4th parameter is not triggering the validation tool to run we should fix this, or add a "Save" button like the traffic light tool has

![image](https://user-images.githubusercontent.com/82955395/141511267-4edeece8-a186-447e-9a34-6e247e31e225.png)

**Comment by mpiannucci** [comment]
What is the valid time of the layer? Agree this is an issue, I think the layers being out of date hurts it too

**Comment by kvmartin001** [comment]
The code that gets the input values from the validation tool is not returning the correct values, so when it goes to find a matching parameter in `availableParameters`, the `array.find()` returns nothing, and the corresponding values in the React state stay undefined:
![image](https://user-images.githubusercontent.com/56608780/141529165-97ba11ac-6e56-467c-bebe-680a5a06b902.png)

The incorrect values are only off by 1 character - for some reason, a number is getting added to the string.

**Comment by kvmartin001** [comment]
I can use `substring` to make things work temporarily:

`const selectedParam = availableParameters.find(p => p.title === v.substr(0,v.length-1));`

and ditto for `selectedStation`, `selectedModel`

Edit: Found the real solution. The index # of each list item was getting tacked on to the list value.  I removed that and things seem to be working.

**Comment by mpiannucci** [comment]
Good find, thanks Kevin!
