### ISSUE TITLE
Tooltip for Stations Disappears when Clicked

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#183]
When the user hovers over a point obs station or a virtual station a tooltip shows up giving details. This tooltip disappears when the station is clicked. The tooltip should remain up.

https://user-images.githubusercontent.com/82955395/141832702-fec274f0-bd4e-4fde-9076-ded60e45f5f1.mp4

**Comment by kvmartin001** [comment]
@jamesdoyle21 The color palettes are coming through the wms at `https://eds.ioos.us/wms/`, and are just very slow. If I wait a minute or two, all palettes eventually come in (testing on the `ott-coops-dev` catalog)
