### ISSUE TITLE
Color of Bounding Box on Data Layer Hover Needs Updating

### ISSUE THREAD

**Issue by nguyandy** [asascience/ott-coops#184]
When hovering over an item in the list of data layers, the bbox preview is no longer rendered on the map.

**Comment by nguyandy** [comment]
nvm my screen brightness was too high and I didn't see the bbox. false alarm!

**Comment by jamesdoyle21** [comment]
You bring up a good point though Andy, the color for the bbox is terrible, especially with the new basemap. I will update this task to change the color to make it more noticeable for the user.

Thinking a darker gray perhaps? Or another color that is noticeable, but not distracting. @kvmartin001 use your best judgement here

**Comment by jamesdoyle21** [comment]
![image](https://user-images.githubusercontent.com/82955395/141837936-2dfedead-ca04-4828-9951-022b1840241a.png)

**Comment by mpiannucci** [comment]
Use the same color OceansMap.maracoos uses
