### ISSUE TITLE
Color Palette in Layer Settings is Spelled Wrong and Thumbnails not Showing

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#185]
Palette* not pallette. Also the thumbnails are not loading

![image](https://user-images.githubusercontent.com/82955395/141835310-71c09729-604e-47be-93ed-ef9d7dd73875.png)

**Comment by kvmartin001** [comment]
@jamesdoyle21 The color palettes are coming through the wms at `https://eds.ioos.us/wms/`, and are just very slow. If I wait a minute or two, all palettes eventually come in (testing on the `ott-coops-dev` catalog)
