### ISSUE TITLE
Traffic Light Tool - Switching Layer from Wind to Temperature/Salinity Causes Crash

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#188]
When any wind layer is selected and then a different 3D layer is selected (temp or salinity) OM3 crashes. This does not happen when the user switches from temp to wind. Crash also happens when user goes from Wind > any layer > temp/salinity.

Steps to reproduce:
1. Open Traffic light tool, create layer, add rule
2. Select layer - any of the 3 3D Wind layers
3. Select layer - any temperature or salinity layer

Also occurs if there is a layer selected between steps 2 and 3.

https://user-images.githubusercontent.com/82955395/142059096-87718a34-0cbe-4238-a02c-c40774470df3.mp4

**Comment by kvmartin001** [comment]
@jamesdoyle21 Is this still happening? I have master checked out right now, and I can't replicate the bug.
I've tried all combinations of 3D wind and salinity on the ott-coops-dev catalog.
![image](https://user-images.githubusercontent.com/56608780/143294172-0f7dec18-7b14-4365-960a-4afde2e824b0.png)

**Comment by jamesdoyle21** [comment]
@kvmartin001 you're not seeing this?
https://user-images.githubusercontent.com/82955395/143297242-36378391-09a9-420f-9b7f-0a3135531bfd.mp4

**Comment by jamesdoyle21** [comment]
@ndellicarpini are you able to replicate this bug?

**Comment by ndellicarpini** [comment]
It still happens for me on master

**Comment by kvmartin001** [comment]
@jamesdoyle21 Oh I just misunderstood. I'm seeing it now. It even happens if you save and close the traffic light tool in between steps.
