### ISSUE TITLE
Import Virtual Stations not Working

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#189]
If you create a few virtual station, export to a csv, then try to import that same file, it is not working. 

Also we should change the message when 0 stations imported. Instead of saying 0 imported successfully in green it should give an error or warning in red.

![image](https://user-images.githubusercontent.com/82955395/142233869-d01a87bb-a985-41b9-b41f-21df242b8175.png)

**Comment by kvmartin001** [comment]
Was this known to be working at any point, or is this the first time you've tried exporting and then re-importing the same file?

**Comment by nguyandy** [comment]
> Was this known to be working at any point, or is this the first time you've tried exporting and then re-importing the same file?

@kvmartin001 Yup this was working. I'm guessing the Unified Layers update broke something.
https://github.com/asascience/oceansmap-3/commits/master/frontend/src/components/VirtualStationTool

**Comment by nguyandy** [comment]
And here's a video of it in action.
https://www.youtube.com/watch?v=oHCL0PsPLu4&t=410s

**Comment by kvmartin001** [comment]
@jamesdoyle21 This was fixed by Andy's permalink fixes https://github.com/asascience/oceansmap-3/pull/137

https://user-images.githubusercontent.com/56608780/144082591-c2824683-a834-45cd-8c73-dbc3be6d6226.mp4

I will change the message to a red warning if 0 stations were successfully imported.

**Comment by jamesdoyle21** [comment]
@kvmartin001 This issue is fixed but it brought up an older issue we had seen before. There used to be a check that does not allow the user to import stations more than once. In this example below, the stations should not import because they are already on the map.

https://user-images.githubusercontent.com/82955395/144125146-4cd445e4-443f-4f3e-9311-b3b86e52d0db.mp4
