### ISSUE TITLE
Data Layer List lag when Permalink tool is open

### ISSUE THREAD

**Issue by ndellicarpini** [asascience/ott-coops#198]
While the permalink panel is open, any interaction with the data layer list panel is really laggy. This lag is the most obvious when mouse hovering over a layer. When the permalink panel is closed, the lag immediately disappears.

**Comment by ndellicarpini** [comment]
It is also laggy when quick adding virtual stations while the permalink panel is open.

**Comment by mpiannucci** [comment]
There is noticeable lag all over the place in the permalink tool that was not happening before. Not really sure what changed

**Comment by mpiannucci** [comment]
Im actually not seeing this lag on the demo site or master... Can you test there and if you see it make a video?

**Comment by ndellicarpini** [comment]
Its actually way less pronounced on the demo site, although it is still there a little bit. It might honestly be good enough on the demo site.

Demo Site:

https://user-images.githubusercontent.com/22432482/143904442-03384530-e709-44e2-a11e-79bcc6105533.mp4

I still have a lot of lag running master though.

**Comment by mpiannucci** [comment]
Yeah it seems like its the compression that is doing it, its not async because its cpu bound. ill look into it> I get it really bad on master when I have picked a vector basemap for some reason that makes no sense to me

**Comment by ndellicarpini** [comment]
oh wow yea, for me it the whole app effectively grinds to a halt if I open the permalink tool with a vector basemap. Those basemaps have a lot more data & they have interaction points on every pixel, but I don't know if this is related.

**Comment by mpiannucci** [comment]
@ndellicarpini Can you pull master and give it a test now, I pushed an update that should help significantly

**Comment by ndellicarpini** [comment]
> @ndellicarpini Can you pull master and give it a test now, I pushed an update that should help significantly

yea wow, that seemed to have completely fixed the issue, I'll close this for now.
