### ISSUE TITLE
Enable searching for specific stations and showing them

### ISSUE THREAD

**Issue by mpiannucci** [asascience/ott-coops#200]
In OM1 you can search for a specific station and that will enable a user to turn a specific station on and off. Should be able to do the same in OM3

**Comment by mpiannucci** [comment]
![buoys](https://user-images.githubusercontent.com/1832671/143934543-20c4e932-7661-4cae-bc72-a1b896a57ef5.gif)

**Comment by nguyandy** [comment]
> ![buoys](https://user-images.githubusercontent.com/1832671/143934543-20c4e932-7661-4cae-bc72-a1b896a57ef5.gif)

Didn't know OM1 can do this lol

**Comment by mpiannucci** [comment]
This is sneaky kinda hard tbh, curious how this interacts with the full point obs layer

**Comment by mpiannucci** [comment]
Works well for me. the one thing we can do in the future is only show the matching stations but thats tricky with the UI so we can revisit that later
