### ISSUE TITLE
Permalink - Copy to Clipboard Button not Working

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#201]
Tried Google Chrome and Bing and neither worked for me. Manually selecting and copying works fine

**Comment by mpiannucci** [comment]
Chrome on your computer didnt work??? What version of chrome do you have

**Comment by jamesdoyle21** [comment]
![image](https://user-images.githubusercontent.com/82955395/144085424-9d27fd53-4907-4e3d-8c6a-6f1eca3dc439.png)

https://user-images.githubusercontent.com/82955395/144085304-38872e96-6dbd-4ff6-8c87-d7f8c18edb9b.mp4

**Comment by jamesdoyle21** [comment]
@ndellicarpini @kvmartin001 you guys seeing this too?

**Comment by ndellicarpini** [comment]
Yea, the copy to clipboard button doesn't work for some reason on the demo site. When you click it, this error is logged:
![Screenshot 2021-11-30 114208](https://user-images.githubusercontent.com/22432482/144089863-93609bd1-eab2-4bfb-983b-37a03a94f153.png)

**Comment by mpiannucci** [comment]
Ahhhh yeah it only works on https sites :( or localhost

**Comment by ndellicarpini** [comment]
> Ahhhh yeah it only works on https sites :( or localhost

huh, that wouldn't have been my first guess. TIL

**Comment by kvmartin001** [comment]
> Ahhhh yeah it only works on https sites :( or localhost

@jamesdoyle21 This is what I'm seeing. On http://20.85.242.58/, it throws the error Nick posted, but on localhost it works for me.

**Comment by ndellicarpini** [comment]
Should this issue just be closed? or should I look for a way to copy to clipboard that doesn't use `writeText` ?

**Comment by jamesdoyle21** [comment]
If that button is not an option, let's take it out and just instruct the user to copy it manually. Let's leave this issue open until we sort that out

**Comment by mpiannucci** [comment]
The button will always work on https sites

We dont have https enabeld for the demo site, but it will be on a real site. So the label would just be temporary

**Comment by mpiannucci** [comment]
Fallback text for non https sites

![Screen Shot 2021-12-28 at 2 22 14 PM](https://user-images.githubusercontent.com/1832671/147599988-a53344bc-e3d4-4918-9f3e-7873e5f0bbc7.png)
