### ISSUE TITLE
Permalink Window is Getting Cut Off

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#202]
The Traffic Lights section of the permalink bar is getting cut off in Chrome. Scroll bar should fix this and will be needed when we add more items to the customize list

![image](https://user-images.githubusercontent.com/82955395/144083760-ee0d0318-cb83-4703-a8c9-61ad33355fb6.png)

**Comment by mpiannucci** [comment]
Scrolls fine on mobile 

![Screen Shot 2021-11-30 at 11 44 19 AM](https://user-images.githubusercontent.com/1832671/144090073-b0cbd252-eb31-4a51-80ef-a31aa91f1c13.png)

And tries to on desktop but it still clips:

![Screen Shot 2021-11-30 at 11 44 59 AM](https://user-images.githubusercontent.com/1832671/144090204-67b31859-a6d8-412c-be21-863a5902bac6.png)

**Comment by ndellicarpini** [comment]
The layer legend has the same exact behavior
