### ISSUE TITLE
Data Layers not Loading if Station Layer is Selected First

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#205]
If the user turns on a station layer (Like NDBC) before turning on a data layer (like Atlantic wave height) the second data layer never loads in. Once the station layer is turned off, the data layer loads.

https://user-images.githubusercontent.com/82955395/144120498-6bb6f0cd-f945-4de4-a381-c213cde6ff2b.mp4

**Comment by mpiannucci** [comment]
Dude how the hell did this happen

**Comment by mpiannucci** [comment]
okay fixed, sorry bout that
