### ISSUE TITLE
Changes to Profile and Timeseries Plots (Units, Axes Titles, etc)

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#206]
A few small things I noticed as I was able to get 3D Wind to load in the profile plots:

- The date and time as the title on the plot can be cleaned up
- Y-axis should be "Height (m)" or ft if imperial
- X-axis should have units listed, "Wind Velocity (kts)"
- Timeseries plot should have units on Y-axis

![image](https://user-images.githubusercontent.com/82955395/144123901-7840facb-2955-4788-8d65-74c3d7e73746.png)

**Comment by jamesdoyle21** [comment]
@nguyandy I gave this to @ndellicarpini but I know this was your area so feel free to hop in here if it makes more sense for you to tackle it

**Comment by nguyandy** [comment]
I'll hijack this one, I need to make some changes in there for units so I'll tackle these issues along the way.
