### ISSUE TITLE
Add Tooltip(s) to the Elevation Slider 

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#207]
Add tooltips to the elevation slider. When it is elevation above the waterline, use "Height" and when it is below the waterline, use "Depth"

This differentiates the two when both are shown on the map. It is also useful if there is only one timeslider there.

**Comment by mpiannucci** [comment]
If Height and Dpeth take up too much horizontal space we can also use an Arrow glyph to indicate up or down instead

**Comment by mpiannucci** [comment]
Just prefix depth values with `-`. Do the exact same thing that the timeslider does, see @ndellicarpini if you need some pointers
