### ISSUE TITLE
Currents layers show plots as wind

### ISSUE THREAD

**Issue by mpiannucci** [asascience/ott-coops#209]
![Screen Shot 2021-12-01 at 10 30 14 AM](https://user-images.githubusercontent.com/1832671/144263468-cd41fc63-8af5-49fa-919f-ebc911d3b4c1.png)

The plot also doesnt look quite right, might need some digging to see how accurate this is coming out 

For context, the current layers are listed as `u_eastward:v_northward-group` for each layer.

**Comment by nguyandy** [comment]
<img width="2128" alt="Screen Shot 2021-12-01 at 2 31 43 PM" src="https://user-images.githubusercontent.com/43226410/144301133-9d9605bf-1cd9-4da7-8ceb-22013d1f9680.png">

So one issue is that we're missing units for current.
@mpiannucci , do you know how I can grab this?

This was how we handled wind velocity
https://github.com/asascience/ott-coops/issues/112#issuecomment-974330384

**Comment by mpiannucci** [comment]
Does `-mag` not work? 

![Screen Shot 2021-12-01 at 2 51 33 PM](https://user-images.githubusercontent.com/1832671/144303864-14c31750-a772-4c74-9eaf-33f0cb6376ca.png)

**Comment by nguyandy** [comment]
it does! sorry figured it out and forgot to update the comment
