### ISSUE TITLE
Gliders / vector layers tooltip issues

### ISSUE THREAD

**Issue by kvmartin001** [asascience/ott-coops#211]
Address these vector layer tooltip issues:

- After closing a glider tooltip with the "X", hovering over the glider will re-enable the tooltip
(X button functionality should be the same as double-clicking the tooltip, which unlocks it)
- Tooltips remain on the map after the associated layer is turned off
(Clear the tooltip when the catalog item is deselected)

**Comment by kvmartin001** [comment]
I have fixed the second bullet point, but the first bullet point is giving me trouble:

> After closing a glider tooltip with the "X", hovering over the glider will re-enable the tooltip

@jamesdoyle21 @nguyandy To accomplish this, the Map component needs to know if the "X" button has been clicked or not. The MapboxGL popups are just dynamically generated `innerHTML`, so any button inside the popup can't affect the state of the Map component. So, I think to solve this problem we would need to convert the popup to a React component which could be tricky. There is an npm package that allows you to do this, but adding it would probably have huge ripple effects: [react-map-gl](https://visgl.github.io/react-map-gl/)

![image](https://user-images.githubusercontent.com/56608780/144641846-62e27392-6c21-4891-b59c-6d87dd9efde9.png)

**Comment by mpiannucci** [comment]
yea were not using react-map-gl... 

There is another place in the code I am rendering react content in a tooltip so you should be able to find that somewhere. But its a pretty small bug tho so im not that mad about it tbh
