### ISSUE TITLE
Virtual station count increases when you edit a station.

### ISSUE THREAD

**Issue by nguyandy** [asascience/ott-coops#213]
Virtual station count increases for some reason when we edit an existing virtual station.
This messes up the exported permalink, and probably some other side effects we haven't seen yet.

https://user-images.githubusercontent.com/43226410/144310941-073fc6cc-3508-480c-baea-d07c16945854.mov

**Comment by mpiannucci** [comment]
Damn I thought I fixed that

**Comment by mpiannucci** [comment]
@nguyandy Ill take this one
