### ISSUE TITLE
Disable Highchart features - only keep data download/exports 

### ISSUE THREAD

**Issue by nguyandy** [asascience/ott-coops#214]
Remove Highchart options that are not required (fullscreen, print, view data table etc.. ) - to match OM1.

<img width="622" alt="Screen Shot 2021-12-06 at 12 15 14 PM" src="https://user-images.githubusercontent.com/43226410/144891511-5be11bdb-79ac-4ae4-84ea-ee0621cb7c77.png">

OM1 options:
![image](https://user-images.githubusercontent.com/43226410/145053332-3cc4b202-a173-4afd-bcfc-630636f6b45a.png)

**Comment by nguyandy** [comment]
Checking OM1, we just have exporting options for the plots, so maybe we should just disable those options and call it a day?
<img width="441" alt="Screen Shot 2021-12-06 at 12 29 58 PM" src="https://user-images.githubusercontent.com/43226410/144893380-22502d3c-7ad8-49f2-a6ba-936582361548.png">

**Comment by mpiannucci** [comment]
Yup sounds good to me

**Comment by jamesdoyle21** [comment]
Yeah, lets keep it consistent with OM1
