### ISSUE TITLE
Create the GIS Layer Tool (Measure, Area, Shape Import and Export)

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#215]
Create a tool that measures the distance between two points.

We may want to expand on this in the future, but let's just keep it simple for now.

**Comment by nguyandy** [comment]
In terms of UX, any thoughts on how we should implement this?

Do we add the option into this row?
<img width="240" alt="Screen Shot 2021-12-07 at 9 50 17 AM" src="https://user-images.githubusercontent.com/43226410/145051308-e86e795e-b3fd-4791-9632-03a65bb6a2a4.png">

I'm thinking it'll be a tool where a user draws a line(s) on the map.

Question is, how should we display the distance? 
How about a map tooltip/popup that's placed on the drawn line?

**Comment by mpiannucci** [comment]
Yeha andy I was thinking it would go right in that row.

That works for me... its basically adding a layer to the map, it can have a UI too if we want to let the user add mutlitple measurements to the map and then they can be saved in permalinks and stuff too. that would be pretty powerful I would think

**Comment by jamesdoyle21** [comment]
Sounds like this ties into the polygon tool that has been discussed too. Or whatever we are calling the tool that allows the user to mark a section of the map (like an offshore windfarm location)

**Comment by mpiannucci** [comment]
Yeah we could just make like one master drawing tool and then make a setting where the user chooses if they want measurement info on the amp or something

**Comment by jamesdoyle21** [comment]
Agreed, Matt. And keep it all in one icon in the top right.

**Comment by nguyandy** [comment]
Oooo.. then this would also tie into the GIS Layer tool then, where we can draw/import/export shapes.
Might as well if we're going to draw polygons in the master tool.

So really, this is just going to be the GIS Layer Tool that's available in OilmapWeb, but it'll include some extra info (distance, area?)

**Comment by mpiannucci** [comment]
Yes!! Exactly andy

**Comment by jamesdoyle21** [comment]
Just talked to Andrew about this, he wants to make sure we include,

- Area inside a shape tool
- Radius tool (choose a point on the map and set a radius so a circle is drawn on the map)
- Distance tool for a line with multiple points (i.e. for measuring the length of coastline impacted by an oil spill)

These do not need to happen for the Maracoos release, but we just want to make sure they are on our radar as we develop the measure tool

**Comment by jamesdoyle21** [comment]
Ok, another update here. @nguyandy don't start working on this yet. I am waiting to hear back if Maracoos wants to add this to the scope or not for their release

**Comment by jamesdoyle21** [comment]
It sounds like we do not need this for the MARACOOS release, so no need to rush to get it in, but we can start working on the GIS Layer Tool as a whole. We can use this issue to cover the whole tool and make more specific tickets as we go.

**Comment by jamesdoyle21** [comment]
Andrew brought this up today. Let's discuss Monday

**Comment by mpiannucci** [comment]
https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-draw/
https://github.com/mapbox/mapbox-gl-draw
