### ISSUE TITLE
Add Sized Arrows to Vector Styles

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#220]
There should be an option for sized arrows in the vector style dropdown for layers with vector arrows. This option sizes the arrows based on the magnitude.

![image](https://user-images.githubusercontent.com/82955395/145285709-aabe35d9-5a1f-4420-902e-7129f2c94894.png)

**Comment by mpiannucci** [comment]
Fixed with andys catalog changes
