### ISSUE TITLE
Changing Data density (Currents) to sparse moves grid to be askew 

### ISSUE THREAD

**Issue by cpaternostro** [asascience/ott-coops#222]
Activating Currents layers -> settings -> Data density
Changing to anything other than "Dense" causes the resulting layers to display on a grid that is askew from the correct map boundaries of the bay
It changes the grid from being correctly aligned like this:
![image](https://user-images.githubusercontent.com/62911145/145270769-8b831903-85eb-445b-90f0-53ca8c615881.png)

To be erroneously aligned like this:
![image](https://user-images.githubusercontent.com/62911145/145286197-3dd45d38-821a-4e28-a66a-d4a115aaae18.png)

CBOFS and DBOFS both displayed this error, both skewing the layer to be SE of the true model domain.

**Comment by ndellicarpini** [comment]
@mpiannucci @nguyandy could this be a pyxms issue? From my testing it seems like any layer request with a density that is not a power of 2 returns a layer with improperly placed arrows.

**Comment by mpiannucci** [comment]
Yes its a pyxms issue

**Comment by jamesdoyle21** [comment]
Disable this feature, for now
