### ISSUE TITLE
Use closest available date when requesting vertical profiles

### ISSUE THREAD

**Issue by nguyandy** [asascience/ott-coops#226]
Issue is noticeable when requesting the GFS 3D Winds.
Time availability is sparse compared to other datasets.

Vertical profile requests returns nothing when we don't request a valid time - which leads to the profile plot closing since there is no data available to show.

With catalog_extents, we can now find the closest available timestep and make a verticalprofile request using that time, instead of plugging in the current map time.

<img width="1136" alt="Screen Shot 2021-12-09 at 12 00 42 PM" src="https://user-images.githubusercontent.com/43226410/145442171-5a1f472f-6122-4141-9658-73499d04eb6d.png">

<img width="1136" alt="Screen Shot 2021-12-09 at 12 02 39 PM" src="https://user-images.githubusercontent.com/43226410/145442159-23a51903-2c25-45aa-9b05-50fec0404c81.png">

**Comment by nguyandy** [comment]
Yesterday while Matt was demo'ing, the profile plot would pop open and close.
This was because we were requesting the verticalProfile plot using the currentMapTime, which was not available for GFS Wind.

Now that we check and use the closest available time, this is no longer an issue, the profile plot loads for a valid time.

This introduces a new case to cover though...
The profilePlot is supposed to display data for a single slice in time, if we use the closest available time, there could be multiple timestamps for the profile plot.

<img width="1119" alt="Screen Shot 2021-12-09 at 1 03 54 PM" src="https://user-images.githubusercontent.com/43226410/145451511-d52551fd-8869-4f6d-b0e3-f2c4fcdd6476.png">

In this profile plot, Wind velocity is actually for 10AM, not 12PM (current maptime + salinity time);

@jamesdoyle21 @mpiannucci 
How should we handle these types of scenario?
Do we want to allow multiple times in the profile plot? 

If we do allow multiple times, I'm thinking of removing the top timestamp, and displaying the matching timestep in the hover tooltip.

**Comment by mpiannucci** [comment]
Put the time in the tooltip and remove it from the header

**Comment by jamesdoyle21** [comment]
This looks great with all the info in the tooltip. Much cleaner.
