### ISSUE TITLE
Turn off all layers button - doesn't allow for layers to be turned back on

### ISSUE THREAD

**Issue by cpaternostro** [asascience/ott-coops#227]
Data Layers ->  Choose some random layers, let them load.
Click Data Layers -> Turn off all layers. (no eyeball symbol)
This clears all the layers (good) but,
After that I can not turn on any new layer.  I've tried many times.  and clicked many things in-between, but it seems that ALL layers are permanently OFF.  
I have to refresh the screen to start anew, which is generally the same state so as clearing all the layers, so....

**Comment by jamesdoyle21** [comment]
Good find, Chris. I am seeing this too.
