### ISSUE TITLE
Improve the Look of the Color Palette Option in Vector Layer Settings

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#229]
This is low priority, but the color palette icons in the settings dropdown are essentially unreadable without zooming way in and feel much older than the rest of the interface. Open to discussion with how we should present these options, but the most obvious is to just make the arrows/barbs and text below bigger.

![image](https://user-images.githubusercontent.com/82955395/146058434-bf0146f0-f848-4c32-9485-6431622ba459.png)

**Comment by jamesdoyle21** [comment]
Also, in the image above you can see that use user has arrows selected for style, but barbs are still showing up in the palette dropdown

**Comment by jamesdoyle21** [comment]
The legend bar should be updated as well

![image](https://user-images.githubusercontent.com/82955395/146058930-32443c3e-2c84-401f-a18f-dcc553d58b83.png)

**Comment by mpiannucci** [comment]
As a note, the legends come directly from pyxms, so its controlled there.
