### ISSUE TITLE
Integrate Screenshot Tool Allowing for Easy Print Outs

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#23]
Google Sheet Row Number: 49

Want to be able to: make print outs of data that pilot uses to make decisions
So that he can: Show vessel captain to communicate the pilotage plans

Does Oceans Map already have this functionality?: Yes
Located where in OM?: FMIS Screenshot tool, maybe with some tweaks

Feasibility: Yes

Notes: We have this already - screenshot tool

**Comment by mpiannucci** [comment]
https://github.com/watergis/mapbox-gl-export

We should try and use mapbox specific functionality instead of an FMIS like microservice because it is faster, less wasteful, and lets everything be self contained to the modular philosophy that we have going on currently.

**Comment by jamesdoyle21** [comment]
Adding this to the current sprint. Once the base functionality is in we can talk about making tasks for additional features since we agreed the FMIS one can be improved

**Comment by mpiannucci** [comment]
We didnt use the fmis tool. And its wayyyyyy faster now with andys merge!

**Comment by mpiannucci** [comment]
https://github.com/asascience/oceansmap-3/pull/93
