### ISSUE TITLE
Allow User to Display a Single Station using the Search in Data Layers Tool

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#231]
We now allow the user to search for a station number in the Data Layers tool but they need to display the entire group of stations. We would like to allow them to display just the exact station they searched for. MARACOOS OM1 has this feature.

**Comment by mpiannucci** [comment]
A little more info on this one, this basically means that the active filters should track through to the point obs stations being shown.

IE if i have entered 44097 into the search bar, and then select the buoy layer, when i check that layer, only stations matching 44097 should show on the map. With that checked, when the user updates the search bar, I *think* the layer should update to show matching layers, but thats open for discussion.

**Comment by jamesdoyle21** [comment]
Included in this is to change the text of the search box from, "Search layers..." to "Search..."

![image](https://user-images.githubusercontent.com/82955395/146797912-059b86fb-142d-474d-88fe-22cc8f4e5b83.png)
