### ISSUE TITLE
Traffic Light Tool - Allow User to Set a Custom Range when Creating a Rule

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#232]
For now, the traffic light tool reads the max value from the data (i.e. wind velocity = 40 m/s) There will be situations where the user will want to set a max higher than the threshold from the data.

So the two tasks here are:

- Set no maximum for traffic light rules
- Set minimum to 0 (except for temperature layers)

**Comment by jamesdoyle21** [comment]
![image](https://user-images.githubusercontent.com/82955395/146590895-6645c3a4-a472-4746-ae32-e6dbafebc8b8.png)

**Comment by jamesdoyle21** [comment]
@kvmartin001 for this issue, the upper value listed on the traffic light rule slider represents the max value from the data? If so we should add a tool tip explaining this.

Also, it appears there is some limit on the slider where if the user clicks on the bar too far from either of the circles, nothing happens.

When the user hovers over the min or max text, the cursor changes, but clicking it doesn't do anything. I would expect the high or low to move to that value.

![image](https://user-images.githubusercontent.com/82955395/149838567-9c8404f1-eff3-45a0-921a-3b23427dce31.png)

**Comment by jamesdoyle21** [comment]
https://user-images.githubusercontent.com/82955395/149838704-93c4f0f7-8779-406e-9983-de145f5b158d.mp4

**Comment by jamesdoyle21** [comment]
Also a few min/max things:

- Wave direction should have a max of 360 deg
- Salinity min is currently 5 PSU, should be 0
- Air pressure should have a min of 0 Pa

**Comment by kvmartin001** [comment]
@jamesdoyle21 Yes, the two numbers that appear on the slider represent the data min & max. Tooltips are a good idea to make it clear.

The slider can be expanded/contracted with the up/down buttons in each input box above the slider. Typing a number higher than the current slider range will also expand it. You can't change the slider range by moving the slider itself.

The cursor change is just default behavior of the slider for some reason. No need to have a different cursor there, so I'll fix that.

**Comment by ndellicarpini** [comment]
@kvmartin001 I could take this issue if you have other work, as I'm currently working a bunch in the traffic light tool.

**Comment by kvmartin001** [comment]
@ndellicarpini Sure, have at it! Thanks
