### ISSUE TITLE
Add site metadata

### ISSUE THREAD

**Issue by nguyandy** [asascience/ott-coops#233]
As we're approaching a public release, we should start setting up metadata for OM3.
This is a big nice to have, especially for sharing and seo.

<img width="835" alt="Screen Shot 2021-12-17 at 11 49 27 AM" src="https://user-images.githubusercontent.com/43226410/146579416-54b3ebae-3519-420f-ae12-499e9b046ff2.png">

Since we're not doing SSR atm, this should be relatively quick and simple - and generic'ish

**Comment by mpiannucci** [comment]
Yeah this also leads into the fact that we need some better infrastructure for swapping metadata, and themes (colors) on the fly

**Comment by nguyandy** [comment]
Putting this on hold til we have SSR in place.

**Comment by mpiannucci** [comment]
Been fighting nextjs all day and I think long term it's a good solution to our injecting configs problem, but it's very hard...

In the meantime, I did find this, and with us being able to control colors dynamically now we can specify our metadata in env vars that gets us to where we need to be for the maracoos release https://create-react-app.dev/docs/adding-custom-environment-variables/

**Comment by mpiannucci** [comment]
Nextjs is super SSR dependent and we dont benefit enough for the effort needed. Instead we can use .env to mess wiht most of the metadata and it works pretty well. 

Maybe long term we get SSR going but its not worth the time sink right now

**Comment by jamesdoyle21** [comment]
Is this issue all set @mpiannucci ?
