### ISSUE TITLE
Traffic Light Layers & Out-of-Date Data

### ISSUE THREAD

**Issue by ndellicarpini** [asascience/ott-coops#234]
Currently traffic light layers don't exhibit the same behavior as the data layers when it comes to out of date data. It doesn't trigger an error message, nor does it load the most recent valid data like catalog layers do. This behavior happens whether the traffic light layer is enabled through the wms settings or through the traffic light layer too.

https://user-images.githubusercontent.com/22432482/146799912-39a9fc89-e120-4fd4-84ad-d9981582eddf.mp4

**Comment by ndellicarpini** [comment]
would it make sense for me to not allow users to enable traffic light layers where there are no shared times between all of the enabled rules?

**Comment by jamesdoyle21** [comment]
Can you elaborate @ndellicarpini

**Comment by ndellicarpini** [comment]
@jamesdoyle21 To create a traffic light layer, you combine any number of layers (rules) from the data layer list. Each data layer has a list of times when data was collected (valid times). Because of this, it is very possible for a user to enable 2 different rules that have completely different lists of valid times.

My current approach to handle out of date data is to find all of the shared times between the rules, and then compare those shared times to the current time similarly to how we handle data layer times, which obviously doesn't work if there are no shared times between rules.

**Comment by jamesdoyle21** [comment]
Ok, got it. So if the user selects a time in which one of the rules has out of date data, you are just looking for the closest time in which both rules have shared times of data, correct? And you are asking what to do if there are no overlapping shared times?

Thoughts:
1. When you round to a shared time that is not the time the user selected, we need to add a notification that tells the user this
2. If there are no shared times between rules, yes you can disable the layer, pop up a notification that tells the user that no overlapping times exist, and force the user to change the rules in order to enable the layer
3. Is there a limit in how far from the time the user selected you will go? If the closest time is 2 years ago I don't think we want to show this..

**Comment by mpiannucci** [comment]
@ndellicarpini You should really look at the pyxms source to consult how the time is handled there and make sure the UI just amkes that clear. Traffic lights are built to spec for FMIS so we dont want to mess with logic too much

**Comment by ndellicarpini** [comment]
Responses:

1. I'm going to use the same notification system that we currently have for out of date data layers, but just add traffic light layers.
2. I probably won't do a notification to show this, I would just not allow the user to save the traffic layer, and add some error text next to the save button.
3. There is no limit to the max time difference between current time & layer time. If we wanted to add this max difference, it would probably have to be a global rule?

**Comment by ndellicarpini** [comment]
@mpiannucci I've just been checking the catalog extents of each rule for the valid times & getting the shared times. Is this not a valid approach?

**Comment by mpiannucci** [comment]
I believe that makes sense, but im just saying that you should check the way those layers are actually created by pyxms to make sure your erros line up with what pyxms is doing

**Comment by jamesdoyle21** [comment]
1. Sounds good.
2. Sounds good. I like that better.
3. Hold off on making any rules for this for now. This is a conversation we can have with the client.

**Comment by jamesdoyle21** [comment]
@ndellicarpini can you explain how we ended up handling this? Or point me to where it is explained? Thanks

**Comment by ndellicarpini** [comment]
@jamesdoyle21 I can break down how I handled it.

So every layer has a list of times where it has data, and to get data you need to request the layer at one of these times. So for a traffic light layer with 1 rule, I treat it the same as we do regular data layers: it finds the nearest time where the layer has data (I'm going to call that a valid time from here on out) that is less than/equal to the current map time. Then that valid time is compared against the map time, and we determine if the layer is considered "out of date" the same way we determine it for regular data layers.

If a traffic light layer has multiple rules, we get the list of valid times for every rule that the traffic layer has, and we find all the common valid times shared between all of the rules. Then from this shared list of valid times, we calculate if the layer is "out of date" the same way as described above. If the traffic light layer rules do not have any shared times, then it shows an error notification telling the user that the rules do not share common times, and tries to request the traffic light layer at the current map timestamp. Although this could theoretically provide a layer back, every time I have requested a traffic light layer where some of the rules are missing the requested time, it has always come back blank.

**Comment by jamesdoyle21** [comment]
Ok, to make sure I understand, when the traffic light layer is out-of-date, we still show it on the map, but we give the warning notification, correct?

And when 2 layers do not have an overlapping time, we give the error notification and the traffic layer does not show up on the map, yes?

**Comment by ndellicarpini** [comment]
>Ok, to make sure I understand, when the traffic light layer is out-of-date, we still show it on the map, but we give the warning notification, correct?

Correct, and it will show the data for the out-of-date time

>And when 2 layers do not have an overlapping time, we give the error notification and the traffic layer does not show up on the map, yes?

Correct, but the traffic light layer request is still sent to the backend, it's just the backend will respond with blank data for the layer.

**Comment by jamesdoyle21** [comment]
Ok cool, that sounds good to me. I'll close this
