### ISSUE TITLE
Traffic Light Layer Incorrect Colors

### ISSUE THREAD

**Issue by mpiannucci** [asascience/ott-coops#243]
https://github.com/asascience/OceansMap/blob/d01e46fc781643793ec98aa095ba5f0829a70769/oceansmap/static/config.js#L67

**Comment by jamesdoyle21** [comment]
Using the traffic light tool inside the data layer setting page is not updating at all. It only shows yellow for any layer. It seems to be working fine inside the traffic light tool tab though.

https://user-images.githubusercontent.com/82955395/148398836-3f9bae81-2523-453a-92fe-bee01f4ae619.mp4
