### ISSUE TITLE
Allow Permalink to Save the Stations Displayed on the Map

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#245]
This came up in our meeting today when Matt was demoing the new search for an individual station tool. It would be nice if the user can save this with a permalink.

**Comment by ndellicarpini** [comment]
This is definitely possible, but I think the way it would have to work is by actually setting the data layer filter text on permalink load, so it would look like this when om loads.

![Screenshot 2022-01-12 124524](https://user-images.githubusercontent.com/22432482/149194149-f1ca29ec-714e-4317-b657-a727b7777e6e.png)

If this is ok, I can go ahead and implement it. Also if I'm working in the permalink tool, I think I could slightly reduce the length of the permalink. I probably won't be able to make a huge difference as there is just too much info that needs to be saved, but I could give it a try.

**Comment by mpiannucci** [comment]
Yea sure permalinks are very important
