### ISSUE TITLE
Include the Data Category in the Legends Bar

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#246]
When we removed the data category name from the layer title to reduce the lengths in the data layers tool menu, they never were added back in when displaying them in the legend. This becomes confusing when the user turns on similarly named layers.

The legend items should have "Currents", "Salinity", and "Water Temperature" labeled

![image](https://user-images.githubusercontent.com/82955395/148118156-eaac458a-8470-410c-89f0-292f70e6d88e.png)

**Comment by mpiannucci** [comment]
Kevin took an approach I ahdnt considered, it works but @jamesdoyle21 please let us know if you want the layer type label to be in the main title instead

**Comment by mpiannucci** [comment]
![Screen Shot 2022-01-05 at 10 38 45 AM](https://user-images.githubusercontent.com/1832671/148245260-d3352d7f-6eb8-46ad-b5b7-5a228cf7b7bb.png)

**Comment by nguyandy** [comment]
It does get a bit tricky when the category doesn't exactly fit the layer.

<img width="298" alt="Screen Shot 2022-01-05 at 10 32 45 AM" src="https://user-images.githubusercontent.com/43226410/148245356-59c939e0-542e-47dd-b041-6b5ffde5163f.png">

**Comment by jamesdoyle21** [comment]
I like the look of this. I agree @nguyandy it is a bit odd with waves, but all waves layers will have the description needed in the title. Unless you guys can think of a data layer we may add in the future that will not work with this formatting, I would say this is all we need.

**Comment by kvmartin001** [comment]
I was about to use `getLayerNameFromCatalogItem`, which is used in the Observation Drawer, but it includes the label "3D" as in "3D Wind". I thought that would look odd in the legends.

I could move the category text above the layer title so it would fit better, to @nguyandy's point:

WAVES
NOAA Mt Holly/Philadelphia Wave Direction (NWPS)

**Comment by jamesdoyle21** [comment]
Yeah that should look better above the layer title. It looks a bit like the color palette title where it is now. As long as it is clearly associated with that layer and not the one listed above it.

**Comment by jamesdoyle21** [comment]
I am holding off on closing this issue until we can see how the label looks placed above the title, just a heads up.

**Comment by kvmartin001** [comment]
@jamesdoyle21 

Since the original PR is merged, I moved the labels in my latest PR. This is how they look. What do you think?

![image](https://user-images.githubusercontent.com/56608780/148794863-682a03f4-21b8-4d05-bc78-1c8ad0b34587.png)

**Comment by mpiannucci** [comment]
that looks a lot better to me

**Comment by kvmartin001** [comment]
@jamesdoyle21 is it ok to move this back to PR submitted?

**Comment by mpiannucci** [comment]
yes

**Comment by jamesdoyle21** [comment]
@kvmartin001 that looks much better on top with the gray surrounding box. Nice
