### ISSUE TITLE
Organize Layer List in Traffic Light

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#252]
Selecting a layer in the traffic light tool can take some searching because there appears to be no order to them. As a user I would expect these to be ordered alphabetically.

https://user-images.githubusercontent.com/82955395/148269484-d4718fb6-35d2-432b-b863-93ac2dc31d23.mp4

**Comment by jamesdoyle21** [comment]
We may want these shown in the same order as they are in the data layers tool (by category). Open to discussion here.

**Comment by ndellicarpini** [comment]
What do you think about this? Keeps the order of the data layer list with the collection titles in brackets on the left.
![Untitled](https://user-images.githubusercontent.com/22432482/151190779-4c6bd55b-6985-4bc1-8335-1572b5a91c0f.png)

**Comment by jamesdoyle21** [comment]
Ooo I like this. Are the collection titles grouped together? Also, do any of the data layers get cut off? That would be a show stopper

**Comment by nguyandy** [comment]
> Ooo I like this. Are the collection titles grouped together? Also, do any of the data layers get cut off? That would be a show stopper

We can always extend the width of the dropdown to fit the text if needed!

**Comment by ndellicarpini** [comment]
> Are the collection titles grouped together?

Yes

> We can always extend the width of the dropdown to fit the text if needed!

This is what extending the width of the dropdown looks like, let me know if this is ok:
![Untitled](https://user-images.githubusercontent.com/22432482/151199062-f37aaab8-b485-4063-b044-372a6d4a80ca.png)

Note: this will extend the dropdown to match its contents, so if there's ever a layer title that's ~2x the length of our current max it will probably look pretty bad.

**Comment by jamesdoyle21** [comment]
Nice, I think this looks good.

Are you able to set a max character limit for the width?

**Comment by ndellicarpini** [comment]
> Are you able to set a max character limit for the width?

Not max chars, but I was able to set the max width to the size of the traffic light rule box.
