### ISSUE TITLE
Data Layers Disappear when the User Changes the Basemap

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#254]
When the user has data layer(s) activated and changes the basemap, the data layers disappear from the map even though they still show as active in the data layers tool and the legend.

https://user-images.githubusercontent.com/82955395/148289027-1a4a1e4a-77a3-4ced-b6b9-34146256a00b.mp4

**Comment by mpiannucci** [comment]
Do not work on this... should be fixed by nicks layer PR

**Comment by kvmartin001** [comment]
Yeah this is layer priority stuff

**Comment by ndellicarpini** [comment]
PR: https://github.com/asascience/oceansmap-3/pull/162
