### ISSUE TITLE
Change Default File Name of Screenshots

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#255]
To be consistent with other areas of OM3 that the user can export files from, we should change the default filename of screenshots to something like OceansMap_Screenshot(1).pdf

![image](https://user-images.githubusercontent.com/82955395/148290612-7aa4b455-d265-48a8-9fe6-05364cad8295.png)

**Comment by mpiannucci** [comment]
We should also let the user specify the file name if they want

**Comment by jamesdoyle21** [comment]
They can currently
