### ISSUE TITLE
CSS Issues

### ISSUE THREAD

**Issue by ndellicarpini** [asascience/ott-coops#257]
- Hover Tooltip for markers are incorrectly placed
- Resizing the window cuts off elements from MapTools

**Comment by nguyandy** [comment]
btw the tooltip issue seems to be an issue w/ importing the mapboxgl style.

adding `import 'mapbox-gl/dist/mapbox-gl.css';` fixes the issue.
But I'm not sure how this happened.

**Comment by ndellicarpini** [comment]
`import 'mapbox-gl/dist/mapbox-gl.css'` fixes the resizing & tooltip bugs, good call andy. 

Through testing this a bit more, I've noticed very small changes in the style (ie. the observation drawer small error text has bigger line spacing, and buttons are now rounded rather than complete rectangles), but I haven't found any more bugs.
