### ISSUE TITLE
Support Channels

### ISSUE THREAD

**Issue by nguyandy** [asascience/ott-coops#258]
<img width="809" alt="Screen Shot 2022-01-11 at 12 32 37 PM" src="https://user-images.githubusercontent.com/43226410/148992663-befac0f0-3b7e-4722-9d28-8323720766ca.png">

Missing this in OM3 atm. 
catalogItem structure: https://oceansmap.maracoos.org/api/catalog?q=Fence

**Comment by nguyandy** [comment]
Use `andys-catalog.json` to use the maracoos catalog.

**Comment by kvmartin001** [comment]
I had the same idea as @nguyandy for this:

> Tried to take the least invasive approach and add two layers manually for trajectory layers, and upon removal, remove an additional identifier+'-point' map layer.

(from the Gliders PR https://github.com/asascience/oceansmap-3/pull/179)

Currently have channels working that way:
```
    const features = type === "line" ?
        [{
            type: "Feature",
            properties: {
                type: "channelLine",
                identifier: `${catalogItem.identifier}-line`,
                title: catalogItem.title,
                lat: catalogItem.geo_extents[0][1],
                lon: catalogItem.geo_extents[0][0],
                parent: catalogItem.identifier
            },
            geometry: channelLine.geometry
        }] :
        channelPoints.map(point => ({
            type: "Feature",
            properties: {
                type: "channelPoint",
                identifier: `${catalogItem.identifier}-points`,
                title: point.properties.name,
                name: point.properties.name,
                short_name: point.properties.short_name,
                lat: point.geometry.coordinates[1],
                lon: point.geometry.coordinates[0],
                parent: catalogItem.identifier
            },
            geometry: point.geometry
        }));
```


Was hoping to find some way to do layer grouping within Mapbox, and it looks like the geometry filter is going to work for that. I will change my channels layers to work the same as Andy's glider update.
