### ISSUE TITLE
Glider layer updates

### ISSUE THREAD

**Issue by nguyandy** [asascience/ott-coops#259]
Missing legend for gliders.
Missing the glider path head on the map.
Missing handling for "drifters" - same as gliders

**Comment by nguyandy** [comment]
drifters can vary in color :( 
![image](https://user-images.githubusercontent.com/43226410/149190853-24731f4b-a1a5-46ea-b5e8-c9173aa11c56.png)

**Comment by mpiannucci** [comment]
Is this defined in the catalog?

**Comment by nguyandy** [comment]
Yea, there's a extras.drifter_type field 👍 
Shouldn't be an issue, just gotta create a map for it.

https://oceansmap.maracoos.org/api/catalog?q=drifter

Odd thing is that drifter / drifter_type isn't even handled in OM1.
I guess because they're all unmanned (black) atm 😆

**Comment by mpiannucci** [comment]
hahah ahhhh gotcha great! sounds like we can handle it

**Comment by jamesdoyle21** [comment]
I will review this when gliders are back
