### ISSUE TITLE
Bring FMIS Stop Light into OM3 and Allow User to Customize

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#26]
Google Sheet Row Number: 54, 60, 68 (Maritime), 9 (Offshore Wind)

Want to be able to: have a multivariable stop light view of model data
So that he can: synthesis all the data

Does Oceans Map already have this functionality?: Yes
Located where in OM?: FMIS Traffic Light

Feasibility: Yes

Notes: My acceptable conditions are these. Outputs stop light. Exists in FMIS, need to bring to OM3

**Comment by mpiannucci** [comment]
pyXMS and the OM backend support this. To get this into OM3 we need to make sure any layers that will use this functionality use pyXMS. Non pyxms layers can not use this feature.

**Comment by mpiannucci** [comment]
Vision for implmentation: Multivariate traffic light will live as a separate app that the user can use to create the custom traffic light layers. When the user adds the traffic light layer, it will show in the Active Layers legend area where it acts like any other layer.

**Comment by jamesdoyle21** [comment]
JH - This could be a separate map layer (data field)
