### ISSUE TITLE
Missing Color Palettes option for EDS (coastmap) layers

### ISSUE THREAD

**Issue by nguyandy** [asascience/ott-coops#260]
I could've sworn we had these. 

<img width="329" alt="Screen Shot 2022-01-11 at 2 48 41 PM" src="https://user-images.githubusercontent.com/43226410/149011176-0c4cbd42-b544-40da-905a-e7ba7aa4259d.png">
<img width="367" alt="Screen Shot 2022-01-11 at 2 48 25 PM" src="https://user-images.githubusercontent.com/43226410/149011180-969243e1-01c9-4b72-9b0b-4cfef17e53b6.png">

**Comment by mpiannucci** [comment]
![Screen Shot 2022-01-12 at 4 54 06 PM](https://user-images.githubusercontent.com/1832671/149228995-0ca949db-71c8-4492-8b4d-c710b408f27e.png)

Unsure if this was always here

**Comment by mpiannucci** [comment]
uhhh where do these come from? Catalog? Or are they hard coded for EDS layers? 

![Screen Shot 2022-01-12 at 5 05 11 PM](https://user-images.githubusercontent.com/1832671/149230443-b9fa1947-eb97-4dc1-b7ce-74ab4b886ca9.png)

**Comment by mpiannucci** [comment]
Not sure what the best way to handle this is... do we host these ourselves? Do we just draw them?

**Comment by nguyandy** [comment]
Just sitting in the OM1 codebase.
https://github.com/asascience/OceansMap/blob/master/oceansmap/static/json/color_ramps.json

**Comment by mpiannucci** [comment]
Yeah it is just hard coded to look up from that for EDS Or does that come from catalog

**Comment by nguyandy** [comment]
EDS -> data-catalog gives us the available style options for a layer + the recommended style.
The style images are also stashed in the codebase. Have to do more digging to see how this all fits together.

**Comment by mpiannucci** [comment]
I can take a peek at putting together all the pieces tomorrow. Thanks!

**Comment by mpiannucci** [comment]
I think I need to setup a general static content directory for the backend, and have the react app install to a second different static directory

**Comment by mpiannucci** [comment]
Laid groundwork... waiting for https://github.com/asascience/oceansmap-3/pull/183 to hit master before mucking around in wms settings.
