### ISSUE TITLE
Active Tropical Cyclones layer not working

### ISSUE THREAD

**Issue by nguyandy** [asascience/ott-coops#261]
No network calls made, no errors seen. 
Not sure what happened here. 

The other GIS layers are working without issues though.
<img width="711" alt="Screen Shot 2022-01-11 at 2 54 19 PM" src="https://user-images.githubusercontent.com/43226410/149011886-a940e3ae-c34e-4216-8382-f11bf60feb9c.png">

Might be an issue with the arcgis token handling?

**Comment by mpiannucci** [comment]
Its probably the tokens

**Comment by nguyandy** [comment]
Was a problem with the OM1 maracoos catalog.

https://github.com/asascience/data-catalog/pull/969
OM1 was being hacky with the cyclone layers and didn't use a proper endpoint. 
Also had to add a additional category to the layer `gis_layers`

We're back up and running w/ the updated catalog.
<img width="1056" alt="Screen Shot 2022-01-12 at 9 55 15 AM" src="https://user-images.githubusercontent.com/43226410/149164394-d09bcda9-41b3-4fb2-b46b-d6c98ed8439f.png">

**Comment by mpiannucci** [comment]
@nguyandy did you merge this into data-catalog?
