### ISSUE TITLE
Current Layers Color Palettes not Showing

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#265]
![image](https://user-images.githubusercontent.com/82955395/150152049-84e7f6c9-6d61-44bf-bf10-e36bee095b4f.png)

**Comment by mpiannucci** [comment]
Don't touch this one yet

**Comment by mpiannucci** [comment]
This is just an artifact of the OFS layers being down. please dont test them until thye are fixed.

**Comment by jamesdoyle21** [comment]
Ah ok good to know that happens when the layers are down

**Comment by kvmartin001** [comment]
Yep I have seen this happen when layers are down for any reason
