### ISSUE TITLE
EDS Layer Settings Don't Show Units

### ISSUE THREAD

**Issue by mpiannucci** [asascience/ott-coops#267]
The units are not shown for EDS layers. This also means that the ranges dont update when the unit systems change, they are effectively unitless

PYXMS Layer settings: 
![Screen Shot 2022-01-19 at 10 59 31 AM](https://user-images.githubusercontent.com/1832671/150167989-5426f58c-462f-4923-9517-3fb70c3ac1ca.png)

EDS Layer Settings:
![Screen Shot 2022-01-19 at 10 59 41 AM](https://user-images.githubusercontent.com/1832671/150168013-d3688a98-8ff2-406d-8276-efb61a862579.png)

**Comment by nguyandy** [comment]
Been playing around with this one. Doesn't look like units are available from EDS in getcap, not included CatalogItem either.

**Comment by nguyandy** [comment]
Lol went to go check how OM1 deals with this... they don't 
<img width="330" alt="Screen Shot 2022-01-21 at 9 56 21 AM" src="https://user-images.githubusercontent.com/43226410/150548515-9fddc67d-16f1-4eaa-8d6c-b7a4b0bd52ac.png">

Just talked to Tim, doesn't look like there's a way to pull units atm besides GFI requests. He's gonna try to get the units included in the getCap by default for the maracoos catalog.

**Comment by mpiannucci** [comment]
ohhhh mannnn

**Comment by jamesdoyle21** [comment]
Well that annoying..

**Comment by jamesdoyle21** [comment]
As it stands, if the user changes from metric to imperial, the numbers do not change in these layers. It's a pretty big deal if they think they are looking at 2 foot waves and they turn out to be 2 meters.. Can we at least add a tooltip or something notifying the user what units these actually are, even if we can't change them?

**Comment by mpiannucci** [comment]
Yup leave this open

**Comment by jamesdoyle21** [comment]
@CoryMartinRPS @hluchka @tgiguere

**Comment by mpiannucci** [comment]
Talked with the EDS team today: EDS supports units only in the legends. The colors never change with the units, just the legend adjusts to match. So take a 0-3 meter wave layer looking like this: 

https://coastmap.com/ecop/wms.aspx?service=WMS&request=GetMap&version=1.1.1&layers=NWPSBOX_WAVE_HEIGHT&styles=WAVE_HEIGHT_STYLE-Jet-0-3-ft&format=image%2Fpng&transparent=true&colorscalerange=0%2C3&autoscalerange=false&time=2022-02-15T20%3A00%3A00Z&exceptions=application%2Fvnd.ogc.se_xml&width=1255&height=889&srs=EPSG%3A3857&bbox=-10117685.482491987%2C3635890.5748159406%2C-7047974.4265593095%2C5810371.155472636&ABOVEMAXCOLOR=extend&BELOWMINCOLOR=extend

![Screen Shot 2022-02-15 at 8 55 02 PM](https://user-images.githubusercontent.com/1832671/154181429-fc8770e8-4c0d-4461-ba24-73ff7c92f707.png)

If we then ask for the legend, it looks like this: 

https://coastmap.com/ecop/wms.aspx?SERVICE=WMS&request=GetLegendGraphic&version=1.1.1&layers=NWPSBOX_WAVE_HEIGHT&styles=WAVE_HEIGHT_STYLE-Jet-0-3-ft&format=image%2Fpng&transparent=true&colorscalerange=0%2C3&autoscalerange=false&time=2022-02-15T20%3A00%3A00Z&exceptions=application%2Fvnd.ogc.se_xml&srs=EPSG%3A3857

![Screen Shot 2022-02-15 at 8 55 51 PM](https://user-images.githubusercontent.com/1832671/154181503-145a2dfd-9e38-4a30-9200-713ad1a98fc2.png)

We can also ask for it in meters: 

https://coastmap.com/ecop/wms.aspx?SERVICE=WMS&request=GetLegendGraphic&version=1.1.1&layers=NWPSBOX_WAVE_HEIGHT&styles=WAVE_HEIGHT_STYLE-Jet-0-3-m&format=image%2Fpng&transparent=true&colorscalerange=0%2C3&autoscalerange=false&time=2022-02-15T20%3A00%3A00Z&exceptions=application%2Fvnd.ogc.se_xml&srs=EPSG%3A3857

![Screen Shot 2022-02-15 at 8 56 31 PM](https://user-images.githubusercontent.com/1832671/154181571-2a6f7bd3-29bd-44fa-ba21-9afbb7b1f813.png)

Notice that the colors are the same but the legend scales to the given unit system. 

Okay, so the only part left we need is to know the default unit system, so @CoryMartinRPS is working to get this added to the `GetCapabilities` response so we can just save it from there or harvest it with data catalog or whatever. I think that gets us to exactly where we need to be.

**Comment by CoryMartinRPS** [comment]
GetCapabilities requests will now return a node for Units in the XML document. The string contained within will be the default units used by WMS when drawing the layer. 

https://coastmap.com/ecop/wms.aspx?service=WMS&REQUEST=GetCapabilities&Version=1.1.1&key=rpstest

**Comment by mpiannucci** [comment]
This is perfect, thanks Cory!
![Screen Shot 2022-02-18 at 11 31 50 AM](https://user-images.githubusercontent.com/1832671/154723562-0bc1eaf6-9cc1-45cf-965f-c54cc277eba9.png)

**Comment by mpiannucci** [comment]
Im going to tackle the first part of this which is having data catalog read EDS units and populate the metadata for each layer

**Comment by mpiannucci** [comment]
Data catalog for OM3 is deployed with EDS units update

**Comment by nguyandy** [comment]
Thanks for the update @CoryMartinRPS @tgiguere 





**edit: Problem solved, no questions :)** 

I have a question about the units for Wind/Current layers.
The default unit for these layers are in "Knots", I was wondering what units are accepted for its conversion (for legends)?


ex: GFS Wave Height is `m` by default, but we can get the the converted label "ft" by adding `-ft` to the styles parameter
https://coastmap.com/ecop/wms.aspx?service=WMS&request=GetLegendGraphic&version=1.1.1&layers=WW3_WAVE_HEIGHT&styles=WAVE_HEIGHT_STYLE-jet-0-3&format=image/png&transparent=true&time=2022-02-21T12:00:00.000Z&srs=EPSG:3857
to
https://coastmap.com/ecop/wms.aspx?service=WMS&request=GetLegendGraphic&version=1.1.1&layers=WW3_WAVE_HEIGHT&styles=WAVE_HEIGHT_STYLE-jet-0-9-ft&format=image/png&transparent=true&time=2022-02-21T12:00:00.000Z&srs=EPSG:3857

Is there an accepted unit name that we can use to convert knots?
I've tried `m/s, ms, kph, mm, kpm`, but they all return back Knots as the legend label.

![legendms](https://user-images.githubusercontent.com/43226410/154960798-d8f622bc-65b7-4d66-b42f-2a5b2b90588a.png)

https://coastmap.com/ecop/wms.aspx?service=WMS&request=GetLegendGraphic&version=1.1.1&layers=GFS_WINDS&styles=WINDS_VERY_SPARSE_GRADIENT-false-1-0-25.72-m/s&format=image/png&transparent=true&time=2022-02-21T12:00:00.000Z&srs=EPSG:3857

**Comment by mpiannucci** [comment]
Looking at om1 and I see cm/s for some

**Comment by nguyandy** [comment]
Ahh thanks @mpiannucci, looks like `cms` is the unit for knots.

![legendms](https://coastmap.com/ecop/wms.aspx?service=WMS&request=GetLegendGraphic&version=1.1.1&layers=GFS_WINDS&styles=WINDS_VERY_SPARSE_GRADIENT-false-1-0-2572.22-cms&format=image/png&transparent=true&time=2022-02-21T12:00:00.000Z&srs=EPSG:3857)

**Comment by mpiannucci** [comment]
https://coastmap.com/ecop/wms.aspx?SERVICE=WMS&request=GetLegendGraphic&version=1.1.1&layers=GFS_WINDS&styles=WINDS_VERY_SPARSE_GRADIENT-false-2-mps&format=image%2Fpng&transparent=true&colorscalerange=0%2C50&autoscalerange=false&time=2022-02-21T15%3A00%3A00Z&exceptions=application%2Fvnd.ogc.se_xml&srs=EPSG%3A3857

meters per second is `mps`, which we should prob use by default instead of `cms` if possible
