### ISSUE TITLE
EDS Layers need to be image layers instead of tile layers

### ISSUE THREAD

**Issue by mpiannucci** [asascience/ott-coops#269]
EDS realllllyyy isnt built for tiling layers, so instead these layers should be image sources with raster layers

**Comment by jamesdoyle21** [comment]
![image](https://user-images.githubusercontent.com/82955395/150810791-36af2c1b-c59f-407d-9f1c-44877aebef5c.png)

**Comment by mpiannucci** [comment]
https://coastmap.com/ecop/wms.aspx?service=WMS&request=GetMap&version=1.1.1&layers=RTOFS_3D_SALINITY_FORECAST&styles=SST_USCG-winter-0-40&width=256&height=256&format=image/png&transparent=true&time=2022-01-24T15:00:00.000Z&srs=EPSG:3857&bbox=-7748880.1794380285,4148390.399093084,-7670608.662474008,4226661.916057106

![Screen Shot 2022-01-24 at 10 27 52 AM](https://user-images.githubusercontent.com/1832671/150812327-40422c53-841f-4cbe-a014-9591d62b2dd5.png)

**Comment by kvmartin001** [comment]
@mpiannucci Check this out (on the maracoos catalog)
It's like EDS is only including raster cells in the tile if a cell is 100% inside the tile area. Cells that overlap the edges are getting cut off.

![image](https://user-images.githubusercontent.com/56608780/150832977-deee4953-68a7-46fa-bdbd-809fe8dd037a.png)

**Comment by mpiannucci** [comment]
There is no built in way to do this with mapbox that correctly determines image layer size for you. So to do this, we need to precompute how big the layer should be or adjust everytime the user moves around but thats kind of a shitty solution

**Comment by mpiannucci** [comment]
https://dev.oceansmap.com/maracoos-next/?permalink=N4IgtghgDgQjD2APEAuUB9Azgd1aANgHYDmqAtAJwBMAdFQAwDM9AjPRQOwCsXAHAGxVeAGhD4IAF1RV+NCpwpcOnDvS4VeHAL6j0hAKZ4xJcupqMWvdVxaL1HfgBZR4qSkeOavDxX71eVlwMvIyOWjrg0ADKEgCe+IZoIACWACaoIBAATgDGAOLJmAAq8FDwxFnQABbJOSCihBBgiSAlZRXVtfUgElUArmAARo3J+BlVEhJQmCgA9LOY+lkAbks02TnEhfCE+MkGNDnwYLMbW5izWfqYEgtLy7XXswDq8Fn4qeht8OgAstCzf5QKL3JazCSjfSzejQ6HdG7xRKgVZZTDJHaoEQgTDwPq5a5GCSlcqVKA1OpJOJQFqVG5LboQhKYVAAbRAEymM3mixWazO212+30h2Op1y50u11uPIeOSer3en2+fwBQJBvKy4Mhs2AAC8tDrYgbgIgtCAALqiRn6KLJXWJKhcfiiSQSLLJQZ9CEYlAgEDhFwQWJLZkoFmgNIZIntUnkhmxakZWkSemiHF4uVR4kdMldURgfa6+DHVD0fMQRBFksoKhULTmgMgbBgTAgyb7Yih4ARHJ4q6ECRAorJZp0qAZBi1sisMhUDhFFj8FD0ejL+g0Ff0ABa3UgUGHo5TUAAShASIk2ZOqNOWLOuEU1Gu1xuVzvRFeb7OKA+uE+Vy-twtUQ+kIZIJCiWI6TADJmjdPNsTeFNUgAGSDJYAEkABFQzZfRUkwdAsiJAAzAjGE+TAID2UC4nQYi3n0HIIBubojmYiRqIJBsgA

**Comment by kvmartin001** [comment]
> There is no built in way to do this with mapbox that correctly determines image layer size for you.

Can't we do it with the `image` source type? If the bbox coordinates are precise enough, that should be enough to place and skew the image the right way

**Comment by mpiannucci** [comment]
> Can't we do it with the image source type? If the bbox coordinates are precise enough, that should be enough to place and skew the image the right way

Yeah but we need to pass the size of the image we want to the WMS GetMap service so it looks high resolution enough and not warped, unfortunately mapbox wont do that for us i dont think

**Comment by mpiannucci** [comment]
On hold while we talk to Tim

**Comment by mpiannucci** [comment]
From Tim: 

> Right, sorry, you were on the list to get back to.
>  
> For the blank image as a response, that shouldn’t be a big deal. Let me look into it a little more and I’ll get one of the guys on it.
>  
> For the lines between the tiles…..my guess is it’s something like the request is asking for data in the middle of a cell, so the data at the missing lines are just not included in the request. I don’t think EDS WMS was really set up to deal with tiles specifically, it really just is good for one image. I think the only thing we can do is to inflate the incoming rectangle a bit to ensure we’re including data around the edge. Of course that might (probably will) result in overlapping images at the borders. It *shouldn’t* be noticeable, one would expect the data at a point will be the same no matter what. But with EDS, most things are not as easy as you would hope.

So Will try without tiling and see how that works out

**Comment by mpiannucci** [comment]
I have no idea how to handle this.... requesting an EDS layer for the given amount of pixels on the map and the bounding coords gives me this... EDS DOESNT ALIGN THE IMAGES TO THE COORDINATE SYSTEM?!?!?!??!: 
![Screen Shot 2022-02-02 at 12 52 44 PM](https://user-images.githubusercontent.com/1832671/152209800-62a10bff-2364-4a1f-b999-a544e79e09e7.png)

https://coastmap.com/ecop/wms.aspx?service=WMS&request=GetMap&version=1.1.1&layers=WW3_WAVE_HEIGHT&styles=WAVE_HEIGHT_STYLE-jet-0-3&width=1605&height=1064&format=image/png&transparent=true&time=2022-02-02T17:00:00.000Z&srs=EPSG:4326&bbox=-349.789908591466,-79.31797596155579,191.70178104819956,85.05112877980659

![image](https://user-images.githubusercontent.com/1832671/152209910-71feaf4c-260b-4890-8af0-f82eb196eb84.png)

IDK how to deal with this, i am totally at a loss... how does OM1 handle this?? Am i doing something wrong here??

**Comment by mpiannucci** [comment]
Going back on the backburner

**Comment by mpiannucci** [comment]
@ndellicarpini Please see my existing work as a potentail starting point for this: 

https://github.com/asascience/oceansmap-3/tree/miannucci-eds-layer-type

This creates EDS layers as an image layer but the proprotions are wrong and the way EDS returns the images does not align with how mapboxgl shows it on the map. Hopefully you can something I am missing here
