### ISSUE TITLE
Directional data crash when Time Range is several months back

### ISSUE THREAD

**Issue by kvmartin001** [asascience/ott-coops#272]
Unsure if this is a Data Catalog issue or OM3 issue, but this crash happens when:

- the Time Slider is set to a range far in the past (example: October 20-28, 2021)
- directional data (e.g. wind direction, current direction) is selected in the Observation Drawer

Permalink to an example of the crash:
(CO-OPS station)

[http://localhost:3000/?permalink=N4IgtghgDgQjD2APEAuUB9Azgd1aANgHYDmqAtAOwBsAdAKwAMAjABwUAsbATM3RXQBoQ+CABdUAZloBOBlQYUGEruwXSK0gL5D0hAKZ5hJctRpcqU+RfbS6LNkJHiUEijQYMeFJu3PsqTD6a2uDQAMqiAJ74BmggAJYAJqggEABOAMYA4vGYACrwUPDEadAAFvEZIEKEEGCxIAVFJeWV1SCiZQCuYABGtfH4KWWiolCYKAD0k5h6aQBuczTpGcS58IT48fo0GfBgkytrmJNpepiiM3PzleeTAOrwafiJ6E3w6ACy0JPfUGHXOaTUSDPSTBjg8HtC7RWKgRZpTDxDaoFhCTDwLqZc6GUSFYqlKAVKpxKJQBqlC5zdogmKYVAAbRAIzGE2mswWSyO6022z0u32h0yx1O50uHJuGTuj2er3eXx+fwBnLSwNBk2AAC9NBrIjrgIhNCAALpCWl6MLxTWxLh0KhCMSiNLxXpdEEolAgEDBRwQSJzekoBmgJIpPHNQnEmmRckpSmianozHYsP4lpEtpCMDbTXwfaoBhZiCIXP5lBcLiaY0+kDYMCYAGjbbEQPAEIZLFnQiiP55eL1KlQFI8LhMMhMBhkLgsPIMdgoDwLhjuDwALXakCgfYHCagACUICRYkyR2OJ1OGLP54uPCuGOuhKfx5Pp1el0u7+vTSAuoR4qIwkiKkwBSeonUzEAMTSBNEgAGT9OYAEkABFAyZPZCkwdA9nwGIMndQh2j2CALi2fR6W-RIxAgABhaj8GKAAxQYEzSQwLmdYxPQyXo5AYb1NCAA](http://localhost:3000/?permalink=N4IgtghgDgQjD2APEAuUB9Azgd1aANgHYDmqAtAOwBsAdAKwAMAjABwUAsbATM3RXQBoQ+CABdUAZloBOBlQYUGEruwXSK0gL5D0hAKZ5hJctRpcqU+RfbS6LNkJHiUEijQYMeFJu3PsqTD6a2uDQAMqiAJ74BmggAJYAJqggEABOAMYA4vGYACrwUPDEadAAFvEZIEKEEGCxIAVFJeWV1SCiZQCuYABGtfH4KWWiolCYKAD0k5h6aQBuczTpGcS58IT48fo0GfBgkytrmJNpepiiM3PzleeTAOrwafiJ6E3w6ACy0JPfUGHXOaTUSDPSTBjg8HtC7RWKgRZpTDxDaoFhCTDwLqZc6GUSFYqlKAVKpxKJQBqlC5zdogmKYVAAbRAIzGE2mswWSyO6022z0u32h0yx1O50uHJuGTuj2er3eXx+fwBnLSwNBk2AAC9NBrIjrgIhNCAALpCWl6MLxTWxLh0KhCMSiNLxXpdEEolAgEDBRwQSJzekoBmgJIpPHNQnEmmRckpSmianozHYsP4lpEtpCMDbTXwfaoBhZiCIXP5lBcLiaY0+kDYMCYAGjbbEQPAEIZLFnQiiP55eL1KlQFI8LhMMhMBhkLgsPIMdgoDwLhjuDwALXakCgfYHCagACUICRYkyR2OJ1OGLP54uPCuGOuhKfx5Pp1el0u7+vTSAuoR4qIwkiKkwBSeonUzEAMTSBNEgAGT9OYAEkABFAyZPZCkwdA9nwGIMndQh2j2CALi2fR6W-RIxAgABhaj8GKAAxQYEzSQwLmdYxPQyXo5AYb1NCAA)

**Comment by ndellicarpini** [comment]
Alright from my testing this is way more annoying than just issues with old data. What's actually happening is that Highchart is crashing when trying to create a windbarbs chart with over 1000 data points, which in our case is any timeseries that is greater than ~6 days long. 

@nguyandy @mpiannucci What would be the solution here? I can also push a temp branch up / create a video & show that is is exactly 1001+ data points that crash.

**Comment by nguyandy** [comment]
> Alright from my testing this is way more annoying than just issues with old data. What's actually happening is that Highchart is crashing when trying to create a windbarbs chart with over 1000 data points, which in our case is any timeseries that is greater than ~6 days long.
> 
> @nguyandy @mpiannucci What would be the solution here? I can also push a temp branch up / create a video & show that is is exactly 1001+ data points that crash.

Well that's a crazy find.. 
At first I thought it might be due to the Highchart datagrouping, so I turned it off.
But nope, still crashes with the date range.

And if we disable data-grouping, then we run into the issue where the chart becomes too cluttered.
<img width="877" alt="Screen Shot 2022-01-27 at 2 27 51 PM" src="https://user-images.githubusercontent.com/43226410/151432076-f04beb0c-10f6-4a3b-ad7b-51854079534b.png">

If the issue is happening at 1000+, should we algorithmically slim down the number of points?
Highchart's datagrouping is already not 100% representative of the data because of the sequencing.
https://www.highcharts.com/docs/stock/data-grouping


<img width="1273" alt="Screen Shot 2022-01-27 at 2 51 16 PM" src="https://user-images.githubusercontent.com/43226410/151433421-567a3f11-8922-45b0-8c1a-2f8245f6b60f.png">
OM1 limits users to a 1 week interval for the charts. I wonder if they encountered a similar issue.

**Comment by mpiannucci** [comment]
Yeah we should just thin the chart on an even interval i think, better to show something over the time than nothing

**Comment by kvmartin001** [comment]
Well that was an unexpected find @ndellicarpini . I thought 1000 was an oddly specific number so I researched it and found this - 
https://api.highcharts.com/highcharts/plotOptions.series.turboThreshold

I guess the threshold could be increased or disabled by setting it to `0`. It's there for performance reasons though

**Comment by ndellicarpini** [comment]
@kvmartin001 What a great find! I'm going to try and play with more, but by forcing the param it seems to avoid the crash.
