### ISSUE TITLE
Legend Style missing in Screenshots

### ISSUE THREAD

**Issue by ndellicarpini** [asascience/ott-coops#274]
![Untitled](https://user-images.githubusercontent.com/22432482/151213850-ffe08a6d-10d7-4b06-8b45-8ce7682231a6.png)

**Comment by mpiannucci** [comment]
Whats missing?

**Comment by ndellicarpini** [comment]
This is what the actual legend looks like for the same layers, namely the font styling is missing

![Untitled](https://user-images.githubusercontent.com/22432482/151244117-b1e3d7cb-dcf4-4e5f-880c-359e637a713e.png)
