### ISSUE TITLE
Customize Multivariate Traffic Light Legend

### ISSUE THREAD

**Issue by mpiannucci** [asascience/ott-coops#275]
The multivariate traffic light legend should show a better view of what it is actually representing, basically duplicate what is shown in the traffic light tool 

![Screen Shot 2022-01-26 at 5 28 55 PM](https://user-images.githubusercontent.com/1832671/151258037-e28c25ff-c9a4-4457-8c3b-7dcbd5e91055.png)

Permalink for reference: 

http://20.85.242.58/?permalink=N4IgtghgDgQjD2APEAuUB9Azgd1aANgHYDmqAtAIwCcFAdAGwAc9ATCwMwDsV9F1FLADQh8EAC7kqtNuyrsALAFZ6nee1kVFAX2HpCAUzwiS5DtIAM59o3Wr6i8y05CR41PXO0B8losZ+bCnNGFi0dcGgAZTEAT3xDNBAASwATVBAIACcAYwBxJMwAFXgoeGJM6AALJOyQYUIIMASQYtLyqpq6kDFKgFcwACMGpPx0yrExKEwUAHoZzH1MgDdF2izs4gL4Qnwkg1ps+DAZ9c3MGcz9TDF5xaWaq5mAdXhM-BT0Vvh0AFloGb+UEid0WMzEI30M3MUKhXWucQSoBWmUwSW2qEYwkw8F6OSuRjEJTKFSg1VqiViUGaFWuiy64PimFQAG0QONJtM5gtlqtTlsdnt9AcjiccmcLlcbtz7tlHi83h8vr9-oDgTzMmCITNgAAvLTamL64CILQgAC6wgZ+kiSR1CV89GE4jEmSSA164PRKBAIDCwlEMUWTJQzNAqXShLaJLJ9JiVPSNLEdKxOLxEaJ7VJnWEYD2OvgR1Q5hzEEQ+cLKDYWjNfpA2Vxl0IYkBhSSTVpUHSLEcLDI5goZBY9EKbBQljHnks5gAWl1IFBW+2k1AAEoQEgJVndth9gcseSFcyKCcT2hT2fCbe9-uDxiH4-jyxnyyzi0gXqEJJiSIxWlgdJNC62bdBUABmoE1AAMkkxDjJBECBiiRgUPQ7AUPI5gQOwZCMPoFCcGQ8igewvYQPIVAEZwEC8PQTApIwVAsAMRgBnSiTht6KFoRhWE4XhBFESRZBkRRZBUTRdEMUxXQNE06S5Pg8ADBA+AAARPBAKxMsIJQQNkX4xKgQTFiAmS9PERiHIQKRfmihDpAAZDJ8ASCgoEqQswhmYyLJhmk3rEIpyn4OgxCgZg6DYJp+joJU+gweMXQQfo7zyQAYpE6BPAAggAagAouguSQQA8jA2WQTMNrEJ+EHZOuYixfFsGNfAoHoIcgyCh82B7D10UReuHw4ClIWYLi7myklSQpSkAByjTNBpKyqQAEs14yqQAAqpClKSp6nRWtG1iKpAAUuQZYdKwAJRdEsKm9JuFCCCwb69BW4BdCk+jueZYgAKqff+OlUhUhKZOkhAuegAz6GI2D6Po9k6H56SBftIVhRFUUrOgYNomkwjJal3qXZlOUFUVpXlZVAAKrqQJkMSRdF6BNOu+OLITWATXphjEzN7wLXJ3rLfoql09z8ApNtu1BQd4uS9LssXVd4t3cID34E9LKKIIQTvZ92kgD9f34IDxtdCUiziK8UMw3DCNIyjNbCNgYCYADbwrgWrkgCcUBJDMHuYAA-Li+AALzslMswzPoKSYLQaLwMnvTnKHMxdKxkPeiwjCcPoBcF7w7D6GhLCMawzAUOw2QkVXTcqMXITMBwFeKM3pccA3deOIxg+COTWV5YVxVlRVVUwbVNQNU1CWte1nUDN1kV9azWnoENWCI-gY187Kw8ZaPVMT7TMwM22WQs7jMUc4QXOujLvOZJNAumeZ+gACJXNkrpQE9IQYMoBygu3SBAVSAA+VSQhVIDGgapIIXRAz73gLgTiqkAA8qlIE4LgYobB8CiHIK8onCBJDBDEJwYoX0-oEKLEBEYJW61F5yz2sFa6EtWEtXOuTLhd1vQQC6ErKWz9ZY7Q4YrI6YjCZ8PVtFQRIBmJhFrNiTISYUjwUQgASW-sGVkXF0KYWwrhfChFiKkXIpRaiKFJKMWYsIQ4EBri7AMEyGsQA

**Comment by ndellicarpini** [comment]
I also made some slight tweaks to how rules are displayed. Right now I'm not the biggest fan of how this looks, but I'd like to get your opinion.

1 Rule Layer:
![Screenshot 2022-01-28 092109](https://user-images.githubusercontent.com/22432482/151563207-7775bf93-4fbf-4e39-b92e-456bec38cf88.png)


3 Rule Layer:
![Screenshot 2022-01-28 092148](https://user-images.githubusercontent.com/22432482/151563241-dd4ed2ce-d055-471c-837d-db594e0f9268.png)

**Comment by mpiannucci** [comment]
I like your changes, can you just change the yellow to match the yellow thats on the map, and you can get rid of the original pyxms legend, we dont need both
