### ISSUE TITLE
AVHRR Out of Date Notification is not correct 

### ISSUE THREAD

**Issue by mpiannucci** [asascience/ott-coops#277]
AVHRR is a 7 day composite layer and it lags behind current time, need to rethink how notifications are calculated for observation layers that will never have data up to the current hour. For context, current maracoos site doesnt show an error at this same time. THis is proabbly an issue for Maracoos Radar layers too which are important to get right 

![Screen Shot 2022-01-27 at 11 09 20 AM](https://user-images.githubusercontent.com/1832671/151397869-c0d86058-936c-4374-9234-57f33bdfe859.png)

**Comment by kvmartin001** [comment]
@mpiannucci What is the lag time supposed to be for this layer? The average timestep is only a few hours. There should probably be a config option to adjust the tolerance for this.

The config could be an object like `overrideLayerOrder`

```
        overrideTimeWarning: {
            "avhrr": n,
            .
            .
            .
        },
```

**Comment by mpiannucci** [comment]
That requires knowing every layer ahead of time. So it probably needs to come from the catalog. Let me look

**Comment by mpiannucci** [comment]
@kvmartin001 Please consult OM1 code to see how they are checking so we can take that into consideration since that looks correct for this layer right now

**Comment by kvmartin001** [comment]
OceansMap uses a 6-hour threshold to determine if layer/station data is out of date.

**Comment by mpiannucci** [comment]
ok well have to think about this one

**Comment by mpiannucci** [comment]
@jamesdoyle21 can you weigh in here

**Comment by jamesdoyle21** [comment]
Can we customize that threshold for each layer? We can set it to values that make sense for us now, then if the client comes back and wants it changed it should be easy to swap, right?

**Comment by jamesdoyle21** [comment]
Or maybe per customize it per data category would be better/easier. Like Matt said the other day, if water temperature is a few days behind, it's not a huge deal, but if wave height is then the user will want to know.

**Comment by mpiannucci** [comment]
There are way too many layers to do it for every single layer unless its in the catalog, but even that is not perfect. Maybe for observation category stuff we use 6 hours, models we use otherwise

**Comment by kvmartin001** [comment]
In my PR I did it by layer name for now, but the criteria can be changed easily. Should I make it by category?

**Comment by mpiannucci** [comment]
Just hard code it for now so that observation categories use the 6 hour threshold

**Comment by jamesdoyle21** [comment]
Do we want to revisit this one later? Or is what we have now enough?

**Comment by mpiannucci** [comment]
ITs good how it is now with the 6 hour defaults
