### ISSUE TITLE
Change Traffic Light Legend to Include AND and OR

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#287]
When the user creates a layer with multiple rules, all of them must be true in order to display green. So instead of commas for green, use AND. Instead of commas for yellow and red, use OR

![image](https://user-images.githubusercontent.com/82955395/151880258-da3d2669-bf30-46a2-b8a4-5585d95df0da.png)

**Comment by jamesdoyle21** [comment]
I wonder if a tooltip would be helpful here too, explaining a bit further.

**Comment by ndellicarpini** [comment]
Making a tooltip is certainly possible, but I have trouble imagining A.) where the user should hover that would activate the tooltip B.) what would be on the tooltip, as I'm not sure what it would look like with a lot of text to explain the rules.

**Comment by ndellicarpini** [comment]
This is what it looks like without tooltips:
![Screenshot 2022-02-01 111808](https://user-images.githubusercontent.com/22432482/152006993-fd7f215a-2bcd-4f6e-a791-2731a2287736.png)

**Comment by ndellicarpini** [comment]
Maybe we should use programming syntax instead? like `&&` and `||`? I don't know if it's appropriate for our target users though.

**Comment by jamesdoyle21** [comment]
I like it the way it is for now. Let's test with a few outside users and go from there.
