### ISSUE TITLE
Layers being dropped from permalink

### ISSUE THREAD

**Issue by ndellicarpini** [asascience/ott-coops#288]
It seems like only 1 layer is being activated after permalink loads? Requires more testing but something is definitely wrong.

**Comment by mpiannucci** [comment]
Good catch: heres a permalink http://localhost:3000/?permalink=N4IgtghgDgQjD2APEAuUB9Azgd1aANgHYDmqAtAOwUB0AbAKwAMDFAzPbawCy0BMXAGhD4IAF1SsAHNQCMAThmS5vWnw5SZtAL5D0hAKZ5hJchRnUuXOd0kUuZ2nLmDhY1F0Z1Gkmc3p2rCn4tHXBoAGVRAE98QzQQAEsAE1QQCAAnAGMAcQTMABV4KHhidOgACwTMkCFCCDA4kELi0oqqmpBRcoBXMAAjOoT8VPLRUShMFAB6Kcx9dIA3eeoMzOI8+EJ8BINqTPgwKdX1zCn0-UxRWfmFqoupgHV4dPwk9Gb4dABZaCmfqHCN3mU1EQ30U0YEIhHUuMTioCW6UwCU2qEkQkw8G6WQuRlERRKZSglWq8WiUEaZUu8w6oNimFQAG0QKNxpMZnNFstjhstjt9HsDkcsiczhcrpzbpl7k8Xm8Pt9fv9AVz0iCwVNgAAvLSaqK64CILQgAC6Qjp+nCCS1cV4HCEYlE6QSfW6oNRKBAIBCQhEUXmDJQjNAyVS+JaRJJtKiFNSVNENIxWJxYYJrWJ7SEYB2WvgB1QjCzEEQufzKF4vC0Jp9IGwYEwgLGO2IgeAoUy2POhFE-3yCQa1KgqV4jArZFH45k+U0KEYjFnnjnjAAWh1IFA+wOE1AAEoQEhxZkjseMGRkViMfKMegLhfUJeroTH3jjl+MVhXm9zu8P01CbqEAkojhFE1JgKkDROpmICYukCZJAAMhA-rpAAkgAIoGzKENgEzoBm6DlAytS4Zg+GVOgSTgUI+wQJc2wGAy1ZAA

![Screen Shot 2022-02-01 at 11 33 52 AM](https://user-images.githubusercontent.com/1832671/152010026-29f42cc3-d845-4338-9fc7-b50a0e92af82.png)
