### ISSUE TITLE
Handle EDS depth/elevation layers

### ISSUE THREAD

**Issue by nguyandy** [asascience/ott-coops#290]
example: RTOFS 3D layers

Need to handle non-sigma 3d layers from EDS.

**Comment by ndellicarpini** [comment]
Are Maracoos CBEFS 3D layers non-sigma as well? On OM1 the depth is listed as sigma, but these layers do not render on OM3.

**Comment by nguyandy** [comment]
CBEFS 3D layers are sigma. That's weird, some CBEF layers aren't loading, but some do (ex: CBEF temperature).
I'll create a new issue for that. Thanks Nick
