### ISSUE TITLE
Elevation slider remains after disabling layers that use it

### ISSUE THREAD

**Issue by ndellicarpini** [asascience/ott-coops#291]

**Comment by jamesdoyle21** [comment]
Happens in both OTT and MARACOOS

**Comment by mpiannucci** [comment]
@ndellicarpini you and @nguyandy  both reported this so duke it out amongst yourselves who wants to work on it :)

**Comment by nguyandy** [comment]
@ndellicarpini if you didn't start on this yet, I can take it.
I'm dealing with some other 3d issues already so this is a nice addition to my list :)

**Comment by ndellicarpini** [comment]
@nguyandy you caught me just in time, it's all yours
