### ISSUE TITLE
Add Legend Category Labels to All Layers

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#292]
The labels inside the legend that sort the layers there are great, so we should expand this to every layer that shows up there. In this example, there are Point OBS Stations, GIS Layers, and a Traffic Light Layer

![image](https://user-images.githubusercontent.com/82955395/152024025-f23ba54f-d9f4-4069-85e4-a04e114943df.png)

**Comment by kvmartin001** [comment]
@jamesdoyle21 I'll add this to the Markers PR since I'm already working on legends in there

**Comment by jamesdoyle21** [comment]
This would look cleaner if we could pair multiple layers in one category title. But this may not work if the Legend always displays the layers in the order they appear on the map. Thoughts?

![image](https://user-images.githubusercontent.com/82955395/153653861-9b473b30-a530-4ea4-bfd1-9389e2ed57e7.png)

**Comment by kvmartin001** [comment]
> This would look cleaner if we could pair multiple layers in one category title. But this may not work if the Legend always displays the layers in the order they appear on the map. Thoughts?

I agree. It's kind of repetitive right now. I'll give it a whirl and see if I can get it to look identical on the screenshots
