### ISSUE TITLE
Permalink - add deep-links into open properties on graphs

### ISSUE THREAD

**Issue by cpaternostro** [asascience/ott-coops#293]
When creating a Permalink, including a link into the properties of an open graph can really enhance the usability of the Permalink.
In this example, it would be nice to have the Permalink contain information about the opened station, and its One Minute Water Level graph.

![image](https://user-images.githubusercontent.com/62911145/152031570-0bb0e8ee-6ff0-480e-bd07-5dbb997e96ff.png)

**Comment by mpiannucci** [comment]
Agreed this is the next step to accomplish with the perma-linking for sure
