### ISSUE TITLE
EDS 3d velocity plots not working

### ISSUE THREAD

**Issue by nguyandy** [asascience/ott-coops#295]
Setup 3d velocity plots for EDS sources

ex: NOAA CBOFS 3D Currents

+ tooltip not working for bottom drawer

**Comment by nguyandy** [comment]
+ wrong units are displayed
<img width="381" alt="Screen Shot 2022-02-02 at 11 41 40 AM" src="https://user-images.githubusercontent.com/43226410/152197667-05b3d735-84c9-4da2-805e-bcd5abbeed2d.png">

**Comment by jamesdoyle21** [comment]
No current layers are working for me right now. Are there other layers I can test this with?
