### ISSUE TITLE
Traffic Light not Showing Anything for Global Wind and Waves Together, but Work Separately. 

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#297]
@ndellicarpini this might be because the date ranges for valid data do not line up. If that is the case, we need to notify the user somehow because it just looks like a bug here.

https://user-images.githubusercontent.com/82955395/152058047-45c73c87-1cdf-4cf5-a655-5ff7da18cc80.mp4

**Comment by ndellicarpini** [comment]
This is a pyxms issue that happens when multiple rules are used and 1+ of those rules uses elevation.
