### ISSUE TITLE
CBOFS Channel Layer not Showing Tooltips on Timeseries Plot

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#298]
https://user-images.githubusercontent.com/82955395/152058837-e7b3acda-86b6-444b-ab31-9316c8602ff6.mp4

**Comment by kvmartin001** [comment]
@jamesdoyle21 When this happened, did you do anything else right before opening these layers? The tooltips look fine on my end

https://user-images.githubusercontent.com/56608780/152456394-41376f3e-f9d4-4b19-b464-96b2800bf5f4.mp4
