### ISSUE TITLE
Notification flashes if triggered while "Active Layers" is open 

### ISSUE THREAD

**Issue by ndellicarpini** [asascience/ott-coops#308]
If you enable a out-of-date layer, or trigger a notification in any other way, while the active layers pane is open, the notification will show for a second and then immediately close.

**Comment by jamesdoyle21** [comment]
Was the fix for this to not show the notification at all because the information is in the active layers legend?

**Comment by ndellicarpini** [comment]
@jamesdoyle21 Yes, but that can be changed if you want.

**Comment by jamesdoyle21** [comment]
That workflow seems right to me, but I will plan to bring these warning notification questions to Chris in our next meeting.
