### ISSUE TITLE
Some layers show "undefined" as valid time in legend

### ISSUE THREAD

**Issue by ndellicarpini** [asascience/ott-coops#309]
For example, all of the climatology layers in Maracoos cause this.

**Comment by kvmartin001** [comment]
@ndellicarpini are there any other layer types currently doing this? The climatology layers aren't time dependent so they don't have time extents.

So there should be a case to handle non-time-dependent layers, but also the climatology layers are sending blank tiles ATM.

https://wms.oceansmap.com/wms/?service=WMS&request=GetMap&version=1.1.1&layers=HFR_Fall_Climatology/u_mean:v_mean-group&styles=arrows%2Fx-Rainbow&width=256&height=256&format=image/png&transparent=true&srs=EPSG:3857&bbox=-8140237.7642581295,3130860.6785608195,-7827151.696402049,3443946.7464169003

**Comment by mpiannucci** [comment]
@kvmartin001 same with the extrema layers for floodMap

**Comment by ndellicarpini** [comment]
@kvmartin001 probably not, I imagine it's only layers with no time extents that do this. So we should just create some way to handle layers without time extents.

As for returning blank tiles, that's probably a pyxms bug, as OM1 can get data for the climatology layers.
