### ISSUE TITLE
Layers that support both arrows and barbs don't show palettes for arrows

### ISSUE THREAD

**Issue by ndellicarpini** [asascience/ott-coops#310]
In layer settings, if that layer supports arrows and barbs, the color palettes will not show if the style is selected as arrows.

**Comment by mpiannucci** [comment]
I could have sworn that I fixed this... But looks like it somehow got reverted

**Comment by mpiannucci** [comment]
See also #229

**Comment by mpiannucci** [comment]
I *think* that this is a pyxms regression... it was definitely working a while back.

**Comment by mpiannucci** [comment]
See https://eds.ioos.us/wms/?REQUEST=GetLegendGraphic&LAYERS=GFS/u-component_of_wind_height_above_ground:v-component_of_wind_height_above_ground-group&STYLES=arrows/x-Rainbow&width=240&height=90&colorbaronly=true
