### ISSUE TITLE
Changing style on some layers doesn't work

### ISSUE THREAD

**Issue by ndellicarpini** [asascience/ott-coops#312]
(Other: ChesROMS Alkalinity 3D) doesn't update when updating the style.

Also, as a little bonus, the colorscale range using a unit with such a long name breaks the styling of the layer settings page.
![chesroms](https://user-images.githubusercontent.com/22432482/152176182-70243323-b995-4b47-b27f-3eb9e4e9c55a.png)

**Comment by kvmartin001** [comment]
I think the alkalinity unit is supposed to be milliequivalents per cubic meter (not sure what meter-3 is supposed to mean). But alkalinity is usually measured in mEq / liter.

**Comment by jamesdoyle21** [comment]
I'm still seeing some weirdness with color range and contours here

![image](https://user-images.githubusercontent.com/82955395/155035475-189e69e7-3028-4f7d-a228-b87c0bfe96c7.png)

**Comment by ndellicarpini** [comment]
what happened to this layer? I no longer see it on the Maracoos catalog

**Comment by nguyandy** [comment]
Removed!

https://github.com/asascience/ott-coops/issues/401
