### ISSUE TITLE
Layer setting groups should hide based on different user selections

### ISSUE THREAD

**Issue by ndellicarpini** [asascience/ott-coops#315]
- if user sets style to contour -> both the Color Palette & Colorscale Range sections should hide.
- if user enables traffic light -> the style section should hide

**Comment by mpiannucci** [comment]
The colorscalerange is used for contours, it tells pyxms what the range of the data to draw the contours in, so dont hide that one

**Comment by kvmartin001** [comment]
Suggestion:

- if user sets style to contour -> "Color palette" text should become "Contour interval", and "Colorscale range" should become "Contour range"

**Comment by jamesdoyle21** [comment]
What exactly does "Contour Interval" change? It doesn't look like it is doing anything. If that is the case, we should hide it.

Also, the text still reads "Colorscale Range" for now

![image](https://user-images.githubusercontent.com/82955395/153652345-11b92871-9262-4fab-b6ed-55a1581cf77e.png)

**Comment by kvmartin001** [comment]
> What exactly does "Contour Interval" change? It doesn't look like it is doing anything. If that is the case, we should hide it.
> Also, the text still reads "Colorscale Range" for now

The text change got overwritten by a merge on Friday.
I think calling it "contour interval" wasn't accurate because that's what the less/more slider is for. It's kind of tough to tell because the contours load so slowly for me.

I'll address in my current branch.

**Comment by mpiannucci** [comment]
It is the `colorscalerange`, it is the lower and upper range of what possible contour lines will show on the layer. So if you have 5 as the low and 80 as the high, the largest contour possible will be 80, the lowest will be 5.

**Comment by jamesdoyle21** [comment]
Hide the "Contour Interval" section
