### ISSUE TITLE
EDS & WMS layers have different default data densities

### ISSUE THREAD

**Issue by ndellicarpini** [asascience/ott-coops#317]
WMS:
![wms density](https://user-images.githubusercontent.com/22432482/152181750-2d476ad8-0d8b-4a0a-9e05-a61ef6c15b58.png)

EDS:
![eds density](https://user-images.githubusercontent.com/22432482/152181782-e1196595-c639-46f0-aae3-c43d515ca672.png)

**Comment by mpiannucci** [comment]
Thats on prupose, those functions do different things
