### ISSUE TITLE
Legend uses 'degrees' for unit rather than symbol

### ISSUE THREAD

**Issue by ndellicarpini** [asascience/ott-coops#318]
![degreesC](https://user-images.githubusercontent.com/22432482/152182191-74e51888-f3b0-4816-9b25-45a2d017fbd0.png)

**Comment by nguyandy** [comment]
@ndellicarpini @kvmartin001 

This issue is up for grabs if you guys are light.

**Comment by mpiannucci** [comment]
Just change legend image query where `units=degreesC` to `units=°C`
