### ISSUE TITLE
Adjust "Zoom to Layer" to be slightly outside of the bbox

### ISSUE THREAD

**Issue by ndellicarpini** [asascience/ott-coops#320]
Currently, zooming to a layer sets the map bounds to match exactly the greatest axis of the bbox (either width or height). This should probably be adjusted to set the map bounds to the layer bbox + ~10%, as I don't know if matching the bbox exactly is desirable.

**Comment by jamesdoyle21** [comment]
Going to veto this one. I like the way it is now, plus this might get screwed up for global layers
