### ISSUE TITLE
Data layer list should keep scroll position when closing layer settings

### ISSUE THREAD

**Issue by ndellicarpini** [asascience/ott-coops#321]
This might be applicable to all sidebar tools, but it definitely is the most obvious with the data layer list. When returning from a sub-pane (such as layer settings) of a sidebar tool (such as data layer list), the sidebar tool should be at the same scroll position it was at when the sub-pane was opened.

This was the bane of my existence while testing layers.

**Comment by jamesdoyle21** [comment]
Yeah this is more noticeable with the big Maracoos catalog. Would be nice, but lets save it for later

**Comment by ndellicarpini** [comment]
@jamesdoyle21 if I'm working on this, should I change the layer list behavior so that the area circled in red remains pinned to the top of the list when a user scrolls? Currently it scrolls with the rest of the list, but its basically a matter of preference which is better.

![Untitled](https://user-images.githubusercontent.com/22432482/152862203-e3de35c9-1d22-4323-945b-96fff88caf4f.png)

Also can you put a charging label on this issue?

**Comment by jamesdoyle21** [comment]
Ohhh yeah that would be nice. If you can pin that section to never scroll, I think that would be best. There has been times where I want to see the bottom of the data layers list and use the search and filter functions

**Comment by jamesdoyle21** [comment]
This is much nicer
