### ISSUE TITLE
Display error message for failed profile plot requests instead of auto-closing profile plot

### ISSUE THREAD

**Issue by nguyandy** [asascience/ott-coops#324]
relating to https://github.com/asascience/ott-coops/issues/289

When a profile plot request fails, it returns empty data.
Instead of closing the profile plot when there's no data, display in UI that there's an issue, instead of closing the profile plot.

Will bundle this task with this issue https://github.com/asascience/ott-coops/issues/299

**Comment by ndellicarpini** [comment]
have you started this yet Andy? if not I think I am going to create a generic add notification function for https://github.com/asascience/ott-coops/issues/326

**Comment by nguyandy** [comment]
I have not! Go for it 👍

**Comment by ndellicarpini** [comment]
in tandem w/ this, should we try to improve how the observation drawer handles errors? Right now all errors come back are categorized as "no data at this date", but 9 times out of 10 it's just the server timing out.

**Comment by mpiannucci** [comment]
> in tandem w/ this, should we try to improve how the observation drawer handles errors? Right now all errors come back are categorized as "no data at this date", but 9 times out of 10 it's just the server timing out.

That would be useful I think

**Comment by jamesdoyle21** [comment]
Yeah go for it Nick, this is a good issue to tackle
