### ISSUE TITLE
Set layer status on fetch extents

### ISSUE THREAD

**Issue by ndellicarpini** [asascience/ott-coops#326]
For layers that fail on fetching extents, we can throw an appropriate error notification. Additionally, I think this change would allow the loading spinner to work with particle layers, which it currently doesn't.

**Comment by jamesdoyle21** [comment]
@ndellicarpini is there a layer you know of I can test this with?

**Comment by ndellicarpini** [comment]
@jamesdoyle21 the way I was testing is after the site loads, disconnect from the internet and then try to load a layer.
