### ISSUE TITLE
Hide Color Palettes if there is only 1 option

### ISSUE THREAD

**Issue by ndellicarpini** [asascience/ott-coops#328]
Should we hide the layer settings color palette if there is only 1 option? Layers like `Active Tropical Cyclones` and the gis layers only have 1 color palette.

![Untitled](https://user-images.githubusercontent.com/22432482/152393374-860576f5-a77f-481f-bab9-7c1ac206ea23.png)

**Comment by jamesdoyle21** [comment]
Disable Color Palette for Layers with no options
