### ISSUE TITLE
NWPS Wave Direction Layers Arrow Density Issue with Zoom

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#329]
At different zoom levels, the arrow density becomes out of whack

![image](https://user-images.githubusercontent.com/82955395/152830814-79a7f2e3-e87a-448a-96fc-d6f6f1cff701.png)

**Comment by jamesdoyle21** [comment]
Boston does this too

![image](https://user-images.githubusercontent.com/82955395/152831498-229279ed-c5b9-4472-a267-5605b5c277b4.png)

**Comment by ndellicarpini** [comment]
this might be fixed with https://github.com/asascience/ott-coops/issues/269

**Comment by mpiannucci** [comment]
Yup this is more EDS sucks at tiling issues

**Comment by mpiannucci** [comment]
![Screen Shot 2022-02-15 at 1 40 07 PM](https://user-images.githubusercontent.com/1832671/154127507-190c357b-a36c-4fd9-8879-65eb8d973884.png)

**Comment by mpiannucci** [comment]
Nick just tagged you for credit, looks fixed to me now
