### ISSUE TITLE
HFR Climatology Layers Treated as Currents

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#331]
In the observation drawer, the label "Currents" is used. The style is arrows and the color palette are vector arrows, but it is a spatial layer

![image](https://user-images.githubusercontent.com/82955395/152835045-7aa85bbb-c5f6-4282-aac6-9166d1b1b574.png)

**Comment by jamesdoyle21** [comment]
Also, the units, cm/s, do not update when changed to imperial

**Comment by nguyandy** [comment]
units are working now, but it's converting from cm/s -> knots.
We can create a new conversion to do cm/s -> in/s? 

also with these climatology layers, the layer isn't queryable, so the obs drawer shouldn't be opening, and shouldn't show the layer as a parameter.
