### ISSUE TITLE
GFS, NAM, NDFD Wind Data Density Issue

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#333]
The arrows are so sparse by default, the spatial layer doesn't tell the user anything. The data density slider is not working

https://user-images.githubusercontent.com/82955395/152838472-618d85b1-e1e5-4619-ae24-80a3272cc4af.mp4

**Comment by ndellicarpini** [comment]
I think this is a duplicate of https://github.com/asascience/ott-coops/issues/334

**Comment by jamesdoyle21** [comment]
Yeah, it is similar. I'll close this and add a comment to the other
