### ISSUE TITLE
PyXMS Data Density Slider not working for any Layer

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#334]

**Comment by ndellicarpini** [comment]
Does this happen with all layers or just when a layer's style is set to barbs? If the former, can you give an example layer where this happens? I know for barb layers, the data density is actually hard-coded in pyXMS for some reason, so changing it would have no effect.

What I did notice is if you change the style to barbs from something else (if the layer has a default style barbs -> change it to something else & then back to barbs), the data density slider disappears. So maybe we should always disable the data density slider if the style is set to barbs?

**Comment by ndellicarpini** [comment]
Wait, after looking at https://github.com/asascience/ott-coops/issues/333 is this just an issue for eds layers? If so I don't know if anything I've said applies.

**Comment by jamesdoyle21** [comment]
The end of this video shows an example. This is Global GFS Wind
https://user-images.githubusercontent.com/82955395/152850521-41d4d5ee-37f2-483b-9672-0744f214dc1b.mp4

**Comment by ndellicarpini** [comment]
I think this issue is specific to EDS layers. I think there might just be a lot of issues with EDS layers that aren't color rasters, such as no data density slider where there should be, color palettes where there shouldn't be, and the density slider not even working.

**Comment by jamesdoyle21** [comment]
I just made an "EDS Issues" label. @ndellicarpini can you tag the open issues you are referencing with this label and we can plan to bring them all to the EDS team so we aren't looking at each individually

**Comment by ndellicarpini** [comment]
I can definitely tag the issues appropriately, but I think these are still issues on how we handle EDS layers in oceansmap, not issues with the EDS data. However, I can't say that for certain for all of our EDS issues.

**Comment by jamesdoyle21** [comment]
Make sure that the default arrow density for these layers is appropriate. It is far to sparse at any zoom level currently. Similar to #334

**Comment by ndellicarpini** [comment]
It seems like data density is an issue across the board 
1. For wms layers, the density of barb layers is always overwritten to be `16`, and if I remember correctly trying to change the density led to some very unexpected results, so there's a good reason it's being overwritten. 
2. https://github.com/asascience/ott-coops/issues/222 
3. For eds layers, the `GetCapabilities` request shows that all layers mentioned in https://github.com/asascience/ott-coops/issues/333 only support `VERY_SPARSE` as their styling. This issue also exists in OM1, and maybe is an issue with `GetCapabilities`

**Comment by mpiannucci** [comment]
Moving out of the backlog. EDS Layer desnity option works and is in current OM3. Pyxms layer denisyt options give weird results, this is a pyxms tracking issue now

**Comment by mpiannucci** [comment]
Closed in favor of #222
