### ISSUE TITLE
Traffic Light slider "min" value is broken in temperature layers

### ISSUE THREAD

**Issue by kvmartin001** [asascience/ott-coops#339]
The min data value in temperature layers is often below zero. When that is true, the tick mark on the traffic light slider gets messed up. I think the dot's position is on the wrong side of zero, so in the example vid it should be at -5, but shows up at 5.
When you look in the HTML, the label part of the tick mark is actually there and positioned where -5 would be. The left side boundary of the slider isn't correct, but the right side is good.

We should also be able to "push" the slider range further negative by using the arrow buttons in the "low value" selector, but that's not working either.

https://user-images.githubusercontent.com/56608780/153076275-0ab2e5be-6828-4c3b-a0ec-faf77767cb85.mp4

**Comment by ndellicarpini** [comment]
it breaks bc the layer isn't recognized as a temperature layer, so the fix would probably be to expand the `isTemperature` check in `TrafficLightControl.tsx`
