### ISSUE TITLE
Handle GIBS layers

### ISSUE THREAD

**Issue by nguyandy** [asascience/ott-coops#342]
We have one layer in MARACOOS, "NASA GHRSST"

This layer uses GIBS for the map layers
https://wiki.earthdata.nasa.gov/display/GIBS/

Seems like it's the only layer that we use that uses this data source type.

This will need a data-catalog update as well since the layer data_url given is not valid (OM1 handles these layer tile requests manually in their backend)

**Comment by mpiannucci** [comment]
We can also just bring over the backend code if we need to
