### ISSUE TITLE
Climatology Traffic Issues

### ISSUE THREAD

**Issue by ndellicarpini** [asascience/ott-coops#346]
- climatology traffic lights don't work from layer settings
- climatology traffic lights trigger time extents error because they have no time extents.

**Comment by nguyandy** [comment]
these dang climatology layers eh?

**Comment by jamesdoyle21** [comment]
I'm getting no response here

![image](https://user-images.githubusercontent.com/82955395/153661146-10d1cd2f-b9d2-4249-8016-953ba1e2cbac.png)

**Comment by ndellicarpini** [comment]
@jamesdoyle21 climatology traffic lights activated from the layer settings do not work yet, it's a pyxms bug that I have a pr open for.
