### ISSUE TITLE
When a Station has Out-of-Date Data, Move the Warning to the Tooltip

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#347]
In order to save space in the Legend, Kelly and Chris agreed we do not need to list the icon for out-of-date stations there. Instead we can include it as a warning in a hover tooltip. The differenct color shade for the pin can stay the same.

Also, we can remove the lat and long info in the tooltip for all stations to make room for the out-of-date warning

![image](https://user-images.githubusercontent.com/82955395/153301021-2fcc8cc8-2bd0-4b8d-8f35-73d39eb3ea90.png)

**Comment by kvmartin001** [comment]
Nice, that's a great idea.
