### ISSUE TITLE
LayerList being cut off.

### ISSUE THREAD

**Issue by nguyandy** [asascience/ott-coops#351]
CO-OPS station is missing from the OTT LayerList even though it appears in the catalog.
Turns out it is there, it just doesn't show because the list is being cut off. 

<img width="1164" alt="Screen Shot 2022-02-11 at 10 51 16 AM" src="https://user-images.githubusercontent.com/43226410/153623652-770b131e-02e9-4a73-b67b-e1cdd1cc69cc.png">

**Comment by jamesdoyle21** [comment]
Wait I think this is happening with Maracoos too. I couldn't find Drifters yesterday

![image](https://user-images.githubusercontent.com/82955395/153623968-33f591ad-327b-4f05-9d35-9920d19ecb5b.png)
