### ISSUE TITLE
Include Out-of-Date and Error Notifications Even when Legends Window is Open

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#352]
The way things work now is if the legend is open the notification will not show. This becomes a problem when there are multiple layers in the legend and the newly activated layer populates at the bottom, below the view of the user. To fix this, let's always show the notification. Even if it populates behind the legends window, that is ok.

https://user-images.githubusercontent.com/82955395/153655052-b873112b-15a3-435d-b3b3-d1e943c87e09.mp4

**Comment by jamesdoyle21** [comment]
@ndellicarpini feel free to take this one too if you're looking

**Comment by ndellicarpini** [comment]
@jamesdoyle21 the notifications wouldn't show up below the legend, they would show above. If this is fine then this is a very easy change.
