### ISSUE TITLE
Validation Tool Parameter and Comparison Should Pre-Populate when Data is Selected in Obs Drawer

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#354]
Workflow:

- Turn on a data layer (say Atlantic Wave Height)
- Turn on a data station layer (NDBC)
- Select a station
- Check a station parameter (Wave sig height)
- Check a model data (Wave height)
- Select "Validate"

I would expect the Paramter and Comparison in the Validation tool to be pre-populated.

This seems like a bug because Parameter will pre-populate if no model data is selected in the obs drawer.

https://user-images.githubusercontent.com/82955395/153943133-f1458044-9283-4f04-9876-569d4c982724.mp4

**Comment by mpiannucci** [comment]
the parameter autofills when a comparison isnt selected, so some byproduct going on

**Comment by mpiannucci** [comment]
So how do we want to handle autofilling if the user has more than one parameter selected? Currently we force the user to choose in that case, which i think makes sense probbaly?

**Comment by jamesdoyle21** [comment]
Yeah, I would say making the user choose makes sense.
