### ISSUE TITLE
Handle permalinks to layers that are not available in the catalog

### ISSUE THREAD

**Issue by nguyandy** [asascience/ott-coops#356]
Right now, the app crashes if a permalink layer is not found in the catalog.

http://localhost:3000/?permalink=N4IgtghgDgQjD2APEAuUB9Azgd1aANgHYDmqAtABwAsAdFQEwDsAzAJz0CsjFAjJ1QDYANCHwQALqmYcaABlkDOTCsx5cqHAL4j0hAKZ5RJcgJmNG9AbMYMeFRl2YixklAzqz6sjmorWBzBSsApra4NAAyuIAnvgGaCAAlgAmqCAQAE4AxgDiiZgAKvBQ8MQZ0AAWiVkgIoQQYPEgRSVlldW1IOIVAK5gAEb1ifhpFeLiUJgoAPTTmHoZAG4LNJlZxPnwhPiJ+jRZ8GDTaxuY0xl6mOJzC4vVl9MA6vAZ+MnoLfDoALLQ079QCK3BbTcTDPTTWSQyGdK6xeKgZYZTCJLaoCgiTDwHrZS6GcTFUrlKBVGoJGJQJrlK4LTpguKYVAAbRAYwmU1m8yWKxOm22uz0+0Ox2yp3Ol2uXLuWQez1e70+Pz+AKB3IyoPB02AAC9NFronrgIhNCAALoiel6CKJbXxTjCdLjDKJfo9MFolAgEChZwQaILRkoJmgFJpAmtYmkunRSlpaniWmY7G4sOEtokjoiMC7bXwQ6oWRZiCIXP5lD0eiaU0+kDYMCYIHjXbEQOgCCLCoZDLoaxYK66CCYCCGUOe+MgnIACQAShEIgV0AAZKg-ACq0-QQIgm5xADMIDKPnowJTyuIcQYs7tyBwi8gUNIRMk9PuevhxN9rygyLeQM-X++vz3o+XTlLuu7VJ+hAFhaYEQVkQFSIWIDlCQegFNUADWgZMj+QiFrePCFmoQheKRt7MIW0jmiAej1P0cTThAaGoOIGQ9HoIh0RADHoXB1SLokxBjKx7GcbR9FxAAwlsBI4oGbEcSIByEHJGQyfgLxpAAxPIemyJ0-4QG+4gyapyYaVpnq6fpBlcZJegAAoXPM4iBvu+DzE+L7Ge+zmXHobkAPLQSgHleX+Pkmf5rlAnEWQJqkKCEG++AiFALmBThNFiP6GRBVAB6JDEqBEchVzOs+MEocxxAIuAX54eEwFaN5AHiKuZYgFJnQ9F1AANPU1lkOIXKpAIYY0NJQGkXgVmQnhkGoBR2Cg8hrbIcjyAAWp0kBQJNEp6FATEsUGIBzfQC1XTwzAFN4G0bVtsi7SIl3XUtjD3Rwj3yM9u00T0hDFRE0Q0mAaSNGxmYgFiGSJYufoLAAkgAIjh6QJYkyzoGxxTVBA+DoFk0RZJp+iMlxySYOg2DYMwtPtno6AVHoQkiVTNN0wz2BM+gySJBcWNoiIxA7M+GTJAexPwPg8XutBynwIO4g7BTdJVDTEC7OI6DbhchPoLltLVkAA

**Comment by jamesdoyle21** [comment]
What is the desired outcome here? To open OM3 without that layer activated?

**Comment by mpiannucci** [comment]
Yes, previously it would crash and show a blank screen. It should also show a notification that the layer is not available now i think

**Comment by nguyandy** [comment]
Here's a permalink to a non-existing layer

https://dev.oceansmap.com/maracoos-next/?permalink=N4IgtghgDgQjD2APEAuUB9Azgd1aANgHYDmqAtABwAsAdFQEwDsAzAJz0CsjFAjJ1QDYANCHwQALqmYcaABlkDOTCsx5cqHAL4j0hAKZ5RJcgJmNG9AbMYMeFRl2YixklAzqz6sjmorWBzBSsApra4NAAyuIAnvgGaCAAlgAmqCAQAE4AxgDiiZgAKvBQ8MQZ0AAWiVkgIoQQYPEgRSVlldW1IOIVAK5gAEb1ifhpFeLiUJgoAPTTmHoZAG4LNJlZxPnwhPiJ+jRZ8GDTaxuY0xl6mOJzC4vVl9MA6vAZ+MnoLfDoALLQ079QCK3BbTcTDPTTWSQyGdK6xeKgZYZTCJLaoCgiTDwHrZS6GcTFUrlKBVGoJGJQJrlK4LTpguKYVAAbRAYwmU1m8yWKxOm22uz0+0Ox2yp3Ol2uXLuWQez1e70+Pz+AKB3IyoPB02AAC9NFronrgIhNCAALoiel6CKJbXxTjCdLjDKJfo9MFolAgEChZwQaILRkoJmgFJpAmtYmkunRSlpaniWmY7G4sOEtokjoiMC7bXwQ6oWRZiCIXP5lD0eiaU0+kDYMCYIHjXbEQOgCCLCoZDLoaxYK66CCYCCGUOe+MgnIACQAShEIgV0AAZKg-ACq0-QQIgm5xADMIDKPnowJTyuIcQYs7tyBwi8gUNIRMk9PuevhxN9rygyLeQM-X++vz3o+XTlLuu7VJ+hAFhaYEQVkQFSIWIDlCQegFNUADWgZMj+QiFrePCFmoQheKRt7MIW0jmiAej1P0cTThAaGoOIGQ9HoIh0RADHoXB1SLokxBjKx7GcbR9FxAAwlsBI4oGbEcSIByEHJGQyfgLxpAAxPIemyJ0-4QG+4gyapyYaVpnq6fpBlcZJegAAoXPM4iBvu+DzE+L7Ge+zmXHobkAPLQSgHleX+Pkmf5rlAnEWQJqkKCEG++AiFALmBThNFiP6GRBVAB6JDEqBEchVzOs+MEocxxAIuAX54eEwFaN5AHiKuZYgFJnQ9F1AANPU1lkOIXKpAIYY0NJQGkXgVmQnhkGoBR2Cg8hrbIcjyAAWp0kBQJNEp6FATEsUGIBzfQC1XTwzAFN4G0bVtsi7SIl3XUtjD3Rwj3yM9u00T0hDFRE0Q0mAaSNGxmYgFiGSJYufoLAAkgAIjh6QJYkyzoGxxTVBA+DoFk0RZJp+iMlxySYOg2DYMwtPtno6AVHoQkiVTNN0wz2BM+gySJBcWNoiIxA7M+GTJAexPwPg8XutBynwIO4g7BTdJVDTEC7OI6DbhchPoLltLVkAA
