### ISSUE TITLE
NASA GHRSST Missing Observation Data API

### ISSUE THREAD

**Issue by mpiannucci** [asascience/ott-coops#357]
![Screen Shot 2022-02-15 at 1 24 22 PM](https://user-images.githubusercontent.com/1832671/154125175-2f82eec1-1769-4004-8211-48e7b33d546a.png)

Original 
![Screen Shot 2022-02-15 at 1 24 11 PM](https://user-images.githubusercontent.com/1832671/154125200-05d60b4c-c126-4292-b10e-1edfb8bda43b.png)

**Comment by nguyandy** [comment]
:O 

Oh snap, thanks for catching this.
