### ISSUE TITLE
Add an Info Button to the Tools

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#363]
We discussed the fact that some of the tools are not self-explanatory and that an info button would be helpful.  We can use the same circle around the i icon, like we do for the data layers and place it in the top right corner of each tool.

![image](https://user-images.githubusercontent.com/82955395/154339519-fc33dcfe-c112-4e4b-870c-edb7bb86b089.png)

**Comment by nguyandy** [comment]
Any thoughts on how to implement this?
How detailed are we planning to make the info content?

If detailed, it might be worth using a drawer for this type of stuff.

https://user-images.githubusercontent.com/43226410/157305870-84715f11-85a9-41f0-8da9-39f8c1568e8c.mov

**Comment by mpiannucci** [comment]
My initial thought was just a push of another drawer over the current one they have open

**Comment by kvmartin001** [comment]
I like the idea of having example screenshots in the drawer. Which layers could be used for screenshots? That would be useful in the traffic light tool and validation tool

**Comment by jamesdoyle21** [comment]
@kvmartin001 I have the descriptions for these. When you start working on this let me know.

**Comment by ndellicarpini** [comment]
@jamesdoyle21 if the descriptions are done I can take this issue

**Comment by jamesdoyle21** [comment]
Yeah @ndellicarpini I can send you these
