### ISSUE TITLE
Elevation is not passed to EDS layers

### ISSUE THREAD

**Issue by mpiannucci** [asascience/ott-coops#370]
The elevation slider works but is not passed in the GetMap request

![Screen Shot 2022-02-17 at 3 30 42 PM](https://user-images.githubusercontent.com/1832671/154565623-48920199-68fd-4088-bdb7-587fa9377188.png)

**Comment by ndellicarpini** [comment]
What? this is the layer in your picture, the layer doesn't look like its changing but the `GetMap` request definitely has the elevation param http://localhost:3000/api/wms?url=https://coastmap.com/ecop/wms.aspx?service=WMS&request=GetMap&version=1.1.1&layers=RTOFS_3D_SALINITY_FORECAST&styles=SST_USCG-winter-0-40&width=1372&height=897&format=image/png&transparent=true&time=2022-02-17T21:00:00.000Z&elevation=1500&srs=EPSG:3857&bbox=-9720806.847149324,3857589.570143777,-7167539.27518042,5526890.5993391825

**Comment by mpiannucci** [comment]
Am i blind??? Maybe haha

**Comment by mpiannucci** [comment]
The elevation needs to be passed to EDS as the index of the elevation, not the value: 
https://coastmap.com/ecop/wms.aspx?service=WMS&request=GetMap&version=1.1.1&layers=RTOFS_3D_SALINITY_FORECAST&styles=SST_USCG-winter-0-40&format=image%2Fpng&transparent=true&colorscalerange=0%2C40&elevation=38&autoscalerange=false&time=2022-02-17T18%3A00%3A00Z&exceptions=application%2Fvnd.ogc.se_xml&width=1470&height=889&srs=EPSG%3A3857&bbox=-10542194.94109151%2C3673869.327498713%2C-6946597.130556819%2C5848349.908155407&ABOVEMAXCOLOR=extend&BELOWMINCOLOR=extend
