### ISSUE TITLE
NOAA RTOFS Salinity Bug in Profile Plot

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#371]
Profile plots for this layer are coming back with multiple values at certain depths:

![image](https://user-images.githubusercontent.com/82955395/154569532-031ec049-e3c4-4086-b3a8-bcafb92281e9.png)

**Comment by mpiannucci** [comment]
@kvmartin001 Andy is stranded, can you look at this in the meantime for a bit?

**Comment by kvmartin001** [comment]
Yep, I'll take this

**Comment by kvmartin001** [comment]
This is very strange. It can almost be explained by gaps in the data, but the gaps seem to be showing up on the plot as random points. For example the point I'm hovering over here is supposed to be a data gap (the one between 800 and 700m in the console)

It's almost like random points are getting added to the end of the plot too. (@ 4000 and 5000m)

![image](https://user-images.githubusercontent.com/56608780/154722922-e7a1a478-83cc-426a-b61b-46fe48e079fb.png)
