### ISSUE TITLE
Data Layer Search Hides Stations and Closes Obs Drawer

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#372]
This came up in a recording today when I was trying to turn on a wave layer with a data station selected. Typing "wave" in the search bar hid all of the station pins and closed the obs drawer.

In the very least, the selected station should remain visible on the map and the obs drawer should stay open.

Up for discussion though is what to do with all the other station pins that disappear. If the user is searching for a specific station it makes sense for them to disappear, but if they are searching for a data layer, it would be better if all pins remained visible. 

https://user-images.githubusercontent.com/82955395/154571490-3858bedf-962b-4fb5-b8c3-097d0c9ae151.mp4

**Comment by mpiannucci** [comment]
@ndellicarpini more complex filtering behavior for you to think about..

**Comment by ndellicarpini** [comment]
I can probably force the selected station to never be filtered out, but there really is no way to tell if the user is searching for a layer or a station without making either the layer search or the station filtering less robust (something like not filtering the stations if the string exists in a layer name is something I would consider a bad workaround).

Maybe we can support search modifiers kind of like google? For instance, if the user would type `station: xyz` then that would only search stations. If they don't put a modifier, the search would basically work the same way it does now (outside of filtering the selected station). Also, maybe we can tie this in with https://github.com/asascience/ott-coops/issues/268.

Although this would be pretty powerful, it might be too complicated? I would appreciate any other suggestions.

**Comment by mpiannucci** [comment]
Yeha I like that but i am worried that it would be too complicated for people. We probbaly have to shoot for what oceansmap.maracoos.org does currently as a first pass

**Comment by ndellicarpini** [comment]
> Yeha I like that but i am worried that it would be too complicated for people. We probbaly have to shoot for what oceansmap.maracoos.org does currently as a first pass

Wait does om1 even support filtering stations? if so how do you it?

**Comment by mpiannucci** [comment]
It does, just type the station name into the search bar before adding the layer

**Comment by ndellicarpini** [comment]
I can't get the stations to actually filter, even if I use the full name of the station. It seems like the layer list can filter by station names but the stations on the map are either all there or all not.

**Comment by ndellicarpini** [comment]
so what is the way forward with this issue? are search modifiers a good idea here?

**Comment by mpiannucci** [comment]
I think we need to leave this to discussion with clients a bit. OM1 got around this by always showing selected layers, that would work here but is kind of confusing behavior

**Comment by mpiannucci** [comment]
@jamesdoyle21 lets discuss expected behavior for this with chris today

**Comment by jamesdoyle21** [comment]
Sounds good

**Comment by jamesdoyle21** [comment]
This is fixed
