### ISSUE TITLE
Validation Tool - Move "Number of Points" to Top of Error Statistics Table & Add Export

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#377]
From Jeff, "In the error statistics table, move the number of points to the top row (above bias).  Also is there a way to download these like the plots?  I did it with copy/paste."

![image](https://user-images.githubusercontent.com/82955395/155024008-18f0fca3-9c30-4bc1-bec4-0aac6b57f31d.png)

**Comment by nguyandy** [comment]
The plot downloads are a built-in feature from HighCharts.
We don't have a method to export tables at the moment.

How fancy do we want these validation exports?
We can stay super simple and export the table as a .csv file, export the table as an image, export the table as a .html file

Or we could create a validation template and give users the option to export the validation data as a pdf - similar to how our "Print" tool works. We can include the validation parameters, data table, plots in the pdf

**Comment by jamesdoyle21** [comment]
If we are just trying to check this box, a simple .csv file is all we need. But I do see how a pdf like the screenshot tool would be cool to have. If it is a big effort, don't bother, but if you think it's easy / want to dive into this, feel free @nguyandy
