### ISSUE TITLE
Think About How to use Less Real Estate with the Obs Drawer

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#379]
We have been getting quite a bit of feedback recently suggesting we try not to cover as much of the map as we do now. For the observation drawer, there are a few things we can do to reduce the height. The main focus is maximizing the height of the plot inside the obs drawer. Some ways to do this:

- Move validate button
- Move legend to the side of the plot?
- Don't allow the x-axis labels to take up 3 lines (reduce the number of labels and extend the text along one line)
- Move the station name to above station parameters and remove white space

This should allow the drawer to be noticeably shorter.

![image](https://user-images.githubusercontent.com/82955395/155410267-3595325e-a91a-4877-8054-24ef6a107b80.png)

**Comment by nguyandy** [comment]
I don't think we need to move the validate button, once the whitespace is removed, it fits in that corner nicely. 

Still some tinkering to be done, but here's a quick first pass.
This is just shrinking down the padding/margin for the charts, allowing us to reduce the height of the obs drawer by 65px.

https://user-images.githubusercontent.com/43226410/155439488-f40567c6-0098-4957-b67c-5065c4088697.mov

Even though the drawer is smaller, the plot is still the same size.
We can shrink it down even further once we move the station names.

Definitely a lot of potential to use up less real estate.

**Comment by mpiannucci** [comment]
Nice! Yeah that looks like a good start

**Comment by jamesdoyle21** [comment]
That looks good Andy, already a good amount of space saved. We will probably want to think about this for all other drawers too

**Comment by mpiannucci** [comment]
One comment from Kelly was about redundancy with the timestamps but in some cases they are not uniform so how do we handle?

![Screen Shot 2022-02-24 at 1 40 11 PM](https://user-images.githubusercontent.com/1832671/155587094-64e17d1f-6f09-40d8-8044-0692730a4f3b.png)

**Comment by mpiannucci** [comment]
For the observation drawer title, Keep the name in it, remove the @ symbol, Surround the Lat lng with parentheses and make it lighter grey color to be less distracting

**Comment by mpiannucci** [comment]
When there is no data, simply just disbale the row and put "No Data" in the results

**Comment by mpiannucci** [comment]
Show chart title only in exports https://www.highcharts.com/forum/viewtopic.php?t=42972#p151429

**Comment by mpiannucci** [comment]
Validate and Add to Virtual Stations buttons should move to right side of the header bar

**Comment by mpiannucci** [comment]
Dont show layers that are not available at a given location in the observation drawer param list. IE clickoing outside of models BBOX

**Comment by nguyandy** [comment]
Should we also deal with ordering the parameters? Display ones with data at the top, move the 'No data' to the bottom?

**Comment by mpiannucci** [comment]
> Should we also deal with ordering the parameters? Display ones with data at the top, move the 'No data' to the bottom?

My thought is yes, but there is something to be said for maintaining consistent order as well
