### ISSUE TITLE
CoOps Markers are not aligned correctly in legend 

### ISSUE THREAD

**Issue by mpiannucci** [asascience/ott-coops#386]
![Screen Shot 2022-03-01 at 2 15 59 PM](https://user-images.githubusercontent.com/1832671/156236556-020f06fe-6936-4034-ae80-c2b654800321.png)

**Comment by kvmartin001** [comment]
I fixed this issue here: https://github.com/asascience/oceansmap-3/pull/247
Maybe I should remove it from that PR and just quickly get this on Master

**Comment by mpiannucci** [comment]
> 

No rush really just had to mark it down
