### ISSUE TITLE
Wave direction is upside down in Observation View chart 

### ISSUE THREAD

**Issue by mpiannucci** [asascience/ott-coops#393]
http://20.85.242.58/?permalink=N4IgtghgDgQjD2APEAuUB9Azgd1aANgHYDmqAtAOwUB0AnAMy0AcTFATAGwCMADB7QFY2AGhD4IAF1T0aFLkwE8ubLvQ4AWCuq7qAvqPSEApnjElyHDtTYDabHp27qOA9aPFSU6ttba07TPTq9DwCTAy6+uDQAMoSAJ74JmggAJYAJqggEABOAMYA4qmYACrwUPDEOdAAFql5IKKEEGDJIGUVVbX1jSASNQCuYABGzan4WTUSElCYKAD085hGOQBuK9S5ecTF8IT4qcbUefBg81s7mPM5RpgSSyur9bfzAOrwOfjp6B3w6ACy0HmgKgMUeK3mEnGRnmPFhsN6d0SyVA6xymFSe1QTFEmHgA3yt1MEnKlWqUDqDRSCSgbWqdxWvShSUwqAA2iApjM5otlmsNhddvtDkZjqdzvlLtdbvc+U88i93p9vr8AUCQWD+TlIdD5sAAF66PXxI3ARC6EAAXVEzKMMVS+uSNg4okkEhyqWGAyhWJQIBAkXcEHiK1ZKDZoAyWRJnXJlKZ8VpWXpEkZuPxhOjpK6FJ6ojAh318FOqB4+YgiCLJZQbDYuktgZA2DAmDB00OxDDoEI2Fm6Akw2w6BqXbSmT99uIhFSADN6hBCBJh0ZUsQpuh4DP0CcRiLvthDvuIOtMOgF98cEZ8PgsASZxAFYiEklkxAGTleid8B8AAoQJLTHSb6ptqiBkAA8nkeQtL04ghjk4FQA+qQJKgvBliAdweukyQYdUJAouAhyluWyAoLwUQFoQJHRGRXACKIOH3gM+ASP8xEoBhTEQCxbEVmhXFGMxrEAKrVuAvQDOJYBMtUM5znk7HUeRNpyQpgJkSIIBGM0wxJAASguxDJO6AxGKIOkQHpRglGp9QADKrlMqCmeZ2m6UkADCewkgSYauaI+HGSU9QANZhmyZb0MILq0MIyjxQIDauhI4iLvU6DEDOp7YMeRjLk5nigF+v7-kYgGvu+8zpKkqxkPp6QwAMZCHKsvRBYRVE0ZAdEcJRHFkDw1BcLQI1+DopGoLQ1A8EwzjqLYLogFJMl+jOUiqRA8n1Ep0jWEws1uH0dmKfxKBWAI3AcDiIAnIuGb+TkZlRJIaVQnkmXZeguXrOgNU3HkPrKQQwYrIhyGoSgiiNnkBI3IuIIha0DJQFk9i1oN9BkDYJTKJxPD4zNPA8AAWr0kBQEjMpGFAhkEeyIDo2wmPY-QJQ8Oo+OE8TpO9EzLP0Fw7Oc8T3PE2T1rLdOEgxPEDKrWkYC0h6-69E8OQSAM-5xJImKEKORh8KEnDpGQQjpLQZDqMMeTqGQtCWFjzhcHkfgCFwWhGOophRn6hscMbHCm+blvW7b9uO1b3Cu4IHvqF7vTNK0WQAGqpBrWv4AABDrQOwZIqDaMNo0cOw9BsPQQT0Ao7i+pQXDUPQl2jUI40HdFIA4ZgeQelAed+uTuShSs3nfh+foUJdTfDAGUTLEkgNGOkacZ9rEi63sEXaUbQhB2bbAW1bNt2w7HBO9Hbtxwnkt4hrS-2aDOQAJIACJb69C7vZ9OV5QVa4bdkVKn8MpZR-r9f6RhAZ60-PAYCBxjCslEOrTW-4yB3A3vrK0uggA

![Screen Shot 2022-03-23 at 3 46 38 PM](https://user-images.githubusercontent.com/1832671/159783319-905fc494-c0e1-41bd-ad89-6a09bd425d39.png)

**Comment by nguyandy** [comment]
@mpiannucci 

Issue seems to be with ncwms/pyxms.
The data we get is being plotted as expected. 
It looks like we're getting the incorrect values back from the GetTimeseries request.

Here's a permalink where we can test with a single timestep
http://20.85.242.58/?permalink=N4IgtghgDgQjD2APEAuUB9Azgd1aANgHYDmqAtAOwUB0AnACwBsFADAByMCsAzPfQEwAaEPggAXVN0bUAjK06cW3NhW6qW9AL7D0hAKZ4RJcs2rMBq1R0b0Nw0RJS3qVBmqW0Z-Tn03bw0ADKYgCe+AZoIACWACaoIBAATgDGAOJRmAAq8FDwxInQABZRySDChBBgESDZuflFJWUgYoUArmAARhVR+PGFYmJQmCgA9COYeokAbpPUScnEGfCE+FH61MnwYCPzi5gjiXqYYuOTUyVHIwDq8In4Mei18OgAstAjb1CBZ5MjYj16EYsIFAprHMIRUAzRKYKLLVBsYSYeCtFJHQxiHJ5ApQYqlSKhKDVArHSZNf7hTCoADaIH6g2GYwm01muyWKzWeg2Wx2KT2ByOJ2Z52SlxudweT1e70+3xZiT+AJGwAAXpplSF1cBEJoQABdYQUvSBKIqiLeRjCcRiRJRDqtf7wlAgEB+ewQEKTKkoamgWLxTF1HF48khInxEliMlIlFogNY+q4xrCMBrFXwLaoFgpiCIdOZlD8fiaPVukDYMCYb4DNbEb2gQjYIboMQdbDoQr16JxZ0m4iEKIAMxKEEIYg7eiixH66Hgg-Qm06nIe2DWK4gM0w6FHDxwenw+CwqMHEFFYNC4QjEFJiSam3wtwAChBwgNideowrEGQAPLJZKVE0oieokP5QKeUShKgMgsNmIDHLaMQRHBBQkJC4BrFmObICgMH+KmhBYQEOEyJwwhISerT4GILyYSgcEURAVE0bm0EMXolHUQAqgW4BNK0vFgOSBSDsOyS0YRuGGiJYlvDhQggHoFQdOEABKo7EBENqtHowhKRAKl6JkMklAAMlO-SoNpumKcp4QAMLLJiqLetZwioZpmQlAA1t61LZtwgiWrQgheKFnCllaYiiGOJToMQg5btgG56BOFmOH6PYgH2A5iaO46FJO07jnOC5bB0y7oKuhDrpu241Vg2D7oemDHqeBhIhe743ne8APokz6vlGV43iMMRRFMZCqTEMCtGQaxTEBHqTGBEFQbhsGdYhyHuRp6EEURkAkYw+F0WQLCyJ4tD8J49DYagtDUOwTD0JwtCWiAjHMRJRFfdRclseRHFMdxgn8bxg4SNJECiSUP0oNw1D8Gwz3Q7D4msSg0icIwMiMIitkGWpe1WYkOl6XZRkmck5nFaT5OE4ZjljrGrlkzZHlGT5fkBUFgghWFpEGiAmwsy59N6P44gxf8yTxYlVUpeg42HMkjqSQQy2geBySQSEqCKGWySoocY6fF5VSklA8T8CwRbndwZDeJkGj0SwbtPbBABaTSQFAFuCnoUDqWhNIgLb9tKE7nAu-Qbse7BLA+8IEf8A70ex-HsGe0n+rCK0A5iIEISkkJzpRGARK2i+TTnIkYitC+wTiHChBdvQg70Nw-6DskZCvRQjD92wMgyGQEC0DE9BkIOjC9939AUDIng9pl8Qd13Pd9wPQ-0CPY8T1PM9z8kC9LyvTQVFU8QAGpRPXjf4AABM36tLY4yh0NdqgMPQtA8MjBSD5JKUH4NQbg3A8a0CUGwbgLBWBLyBpgZItooBv2dL7JI3lJiOX6vEJCLA9AQDYK6fwExwhqz0DEO+D8m5iBbssPyIAN7d2SL3funBB7D1HuPSe09Z7z2SIvZeMg4jC2RPXKhpktYAEkAAiTDpb5TiglJKSsVZ6DVq3XqH5Vj6CpMIOuDcXxkGOAwtu+pNBAA

The WMS arrows are pointing straight up, which should be ~0 degrees.
But we're getting back 179.25 from the timeseries request.


Looks like OM1 has this issue as well.
<img width="1217" alt="Screen Shot 2022-03-28 at 2 07 14 PM" src="https://user-images.githubusercontent.com/43226410/160459874-b35b58cb-ca09-4366-bbbe-52229124134d.png">

**Comment by mpiannucci** [comment]
That is super interesting... might have to do with specifying the wind being from or to

**Comment by ndellicarpini** [comment]
This is a ncwms issue, pyxms just passes along `GetTimeseries` requests to ncwms

**Comment by jamesdoyle21** [comment]
This is also happening in the validation tool. Where did we leave this issue?

![image](https://user-images.githubusercontent.com/82955395/176260571-fbefbf2b-e631-4fa7-b0b8-e54e7d25f439.png)

**Comment by mpiannucci** [comment]
Something is off here......

https://dev.oceansmap.com/ott-coops/?permalink=N4IgtghgDgQjD2APEAuUB9Azgd1aANgHYDmqAtAOwCsAdAGwAcAnBQ3QExUDMXVAjFwAsAGhD4IAF1RcGNQU26Cq-AAwM17dgF9R6QgFM8YkuQqCafOn2uC6XJvYcVR4qSns12KqkwdelFN5UWjrg0ADKEgCe+IZoIACWACaoIBAATgDGAOIJmAAq8FDwxOnQABYJmSCihBBgcSCFxaUVVTUgEuUArmAARnUJ+KnlEhJQmCgA9FOY+ukAbvM0GZnEefCE+AkGNJnwYFOr65hT6fqYErPzC1UXUwDq8On4SejN8OgAstBTP1DhG7zKYSIb6KYqCEQjqXGJxUBLdKYBKbVAMUSYeDdLIXIwSIolMpQSrVeLRKCNMqXeYdUGxTCoADaIFG40mMzmi2Wxw2Wx2+j2ByOWROZwuV05t0y9yeLzeH2+v3+gK56RBYKmwAAXlpNVFdcBEFoQABdUR0-ThBJauKcOiiSQSdIJPrdUGolAgEAhFwQKLzBkoRmgZKpfEtIkk2lRCmpKkSGkYrE4sME1rE9qiMA7LXwA6oFRZiCIXP5lCaLQmn0gbBgTCAsY7YiB0CEbATdASPrYdDlFuJFKeq3EQgJABmVQghAkvf0CWIo3Q8DH6H2-X5b2wO03ECWmHQU7eOH0+HwWGxY4g0ph0VicYg1PSHX2+GeAAUILExpSHwm1YgyAAeUyTJ6g6cR-XSQCoCvBJolQPgVELEBLmdJI4mQsoSHhcAdgLItkBQRDQmzQh8LCQi+CoUR0Mvbp8AkL48JQZDaIgejGOLBDWP0OiGIAVTLcAOm6ISwFpMoxwnTImLIojzUk6SfkI9hRH0Oo+liAAlKdiDiJ1un0NSNNifJFKqAAZedRlQAyjJAdSIE0-QAGFNnxbFAzs0QsL0-IqgAa0DRlCy4YR7SYYQ+FUqiqwdCRxGnKp0GIMd92wXd9Fnay3BDQcQGHUdpKnGdyjnBcZ2XVcDj6Dd0C3Qgdz3A9GqwbATzPTALyvQwMVvH9H2feBX3SD8vwTe9HymJIEgWMgtKSGBujIHYFnAv15mg2D4KIpC+rQjCfN0nDSPIyBKLoEjmLIFQLCYPgmHYe6RAo1AmBoNRbCUJh7RANiONk8j-oY5TuJo3j2IEsSRKEscpAUiApKqQH3E8dQGBep1EaUriUDoGgqCsRhjKc7Tjts9JDJJ5yzOxyycopqmHJM1z3OTLzKfs3z9H8zIgqZULwuESLoqiqgzRAfZp3Zxn9FCSREtBTIUrS+rMvQGbzkyd05Ly1I32dSB0iiNWlg1hItZ1890kva8+rhVIMnSeBsAZUQX3fT99G-R30md12pk0q8AvWyCtsyOColQKhkNQ5JDpAbmjFOliCOkOgVCuuTkPO9OeL4xjmPzyHOMIrgM-BgvBPEz10NIURRJrv79HrzpzJk5iqIRpGZNxoRqOZ0n9B07DUEvfA5mp0z26sirZan1npc8sfP0nxPjt5-mg0LJhCz4dRhHYQJhHLlQJcc5zIjQptZdCQh4H3JI+mXfcuB3P9O30MAYIkbEcNDT0CZv43gdp6eMiZJbDU9uNAaf5poQw4qHTaMEI47UQrHJ08dyJJ3iCnLgqlXooAUFnaQBDc5EIHsDQucl8GVxLqDChdCOLV1SC5GGTcABiEk6YdxoQQrGPcGEKAXiPPS89B40xngzFA3kJGxDckvJE4juab2CoWaiiExaH0LJwE+oVxZ3wfhrZ+qs36rmxOcacLZqyZAsepTiUB-INGpFAVIXhNA3ToGQI++RLAsRUP4j6SEABaHRICOISM4hMUBRFxGZO49gnjvEUF8VQfxgSkIqFCaIBJN0KA3T4Kk9JSEglZNNO7Ox04AAi+goBdHIt0UcEhwhRGpE3SJFJnSfg6LcdIv9PyREkCiQg-Z9AqAzlQdgdAkhkEmUkJgZBBB9EyIIMgP07CLKsJkJ6-AzD6EEEYABDlxneCmTMuZCylkrLWXQDZtg+DbIUHwPZBzaj1EaAANQtv0-AAACQZOt1puEEHwO6lgKDsHwTwQQMgB6vjkpQUFvA6D3UmU9feKgwrN0wJkZ0dThmpDCRkAK8w3IjVSNQOwVA+jelCHMWI2t9BJC+X07oAyJBDM2MFY5EyzmzPYPMxZyzVnrK4Jsh5OznmCH2eUlCJ59CMqSOEaUdRnTwAshtJRQYJaYj6UyjVkEACSVTuX30fiY1+bxbF+3sW7SBv5tgGDtb0n5ZBLicpGbKpIkgIAuR9a+YgHChh-jwKEeAfRJQeo-GUBof5TVGKfi-dAZjrWWIkAyCW4bI06zJc8fsZrjFJpTZU9NIxMD4AABT72EL89BABSGt0U60AEpvRFigC5bYfMACiSxpxGCIMQDVuVjCkBQJQcwqLAjRToPwOgggVDODEJIaQsgGDPJkOwdQXAVBKCoqEYoOwR2EQoEwF6UcUD8C4KEMc+hJB-2ClWLQQA

![Screen Shot 2022-06-29 at 11 24 47 AM](https://user-images.githubusercontent.com/1832671/176474984-387e7373-e319-4191-b147-7e4f6cc8b861.png)

**Comment by mpiannucci** [comment]
All three of these values are different looking haha


Also... this doesnt even match????? 

![Screen Shot 2022-06-29 at 11 25 58 AM](https://user-images.githubusercontent.com/1832671/176475371-086eb6a3-5576-47ea-a0ea-5a918eec831c.png)

**Comment by mpiannucci** [comment]
After checking.... this is an issue for the wave layers only because those have the "From" convention, the currents and wind layers work ok because they use the To convention

**Comment by mpiannucci** [comment]
NECOFS has the same issue 

![Screen Shot 2022-06-29 at 1 30 14 PM](https://user-images.githubusercontent.com/1832671/176499406-f074254c-61e5-43ae-80c7-0567d3038180.png)

**Comment by mpiannucci** [comment]
I am pretty sure that OM 1 gets around this by making scatter plots for degrees_true units? 

![Screen Shot 2022-06-29 at 1 35 36 PM](https://user-images.githubusercontent.com/1832671/176500358-3a93833c-091b-44aa-925e-114ae74aec24.png)
![Screen Shot 2022-06-29 at 1 36 25 PM](https://user-images.githubusercontent.com/1832671/176500411-18931287-4eb6-4eb3-9aae-1383245187f9.png)

**Comment by mpiannucci** [comment]
We can prob check if the units are degree_true and flip the plot somehow, but the values then wouldnt look right. Do highcharts arrows have configuration for From or To for direction?

**Comment by mpiannucci** [comment]
So from what I can tell, Vector layers in NCWMS always come back as degrees, To and the stations are sometimes degrees from, and scalar direction layers are usually degrees true. Does degrees true mean From?

**Comment by jamesdoyle21** [comment]
This is related to #512 and #513.

**Comment by kvmartin001** [comment]
> So from what I can tell, Vector layers in NCWMS always come back as degrees, To and the stations are sometimes degrees from, and scalar direction layers are usually degrees true. Does degrees true mean From?

@mpiannucci Anything reporting wind as "degrees to" is probably wrong, since the convention is always "degrees from" - that's what NWS and NOAA use, and the GRIB file format also specifies it. "True" should just mean true north as opposed to magnetic north.

GRIB ref:
https://www.cpc.ncep.noaa.gov/products/wesley/opn_gribtable.html
https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_table4-2-0-2.shtml

In RUWRF for example - the NC variables are coming straight from GRIB params, so no reason to believe NC is storing it as "degrees to":
https://tds.maracoos.org/thredds/dodsC/Rutgers_WRF_3km.nc/Rutgers_WRF_3km-2022072600.html

So I would say this is just an NCWMS problem, but EDS is also giving us "degrees to" in GetTimeseries. I checked NAM and NOGAPS from the maracoos catalog, and saw the same problem - WMS barbs are correct, but the timeseries / validation data is flipped.

EDS layer:
![image](https://user-images.githubusercontent.com/56608780/181061453-fe1aa291-8c06-4a87-b713-ba43b4eff798.png)

**Comment by kvmartin001** [comment]
A few more things I found:
- Some of the RUWRF direction values are negative, which seems wrong, but Highcharts Barbs ignores the sign (ex: adjacent values of -170, 170 result in barbs facing the same way on the chart)
- the "component_of_wind_height_above_ground-dir" parameter doesn't exist in the RUWRF opendap access form, but the U and V velocities are there - does this mean ncwms calculates the angle itself?
