### ISSUE TITLE
Add ENC background or background overlay to display nautical charts

### ISSUE THREAD

**Issue by cpaternostro** [asascience/ott-coops#394]
Announcement from NOAA https://nauticalcharts.noaa.gov/data/gis-data-and-services.html#enc-display-services

With the ENC charts available, we are able to add a background of charts that look like the old paper charts that are familiar to all older mariners.

The ECDIS Display Service is available in two formats:  

[Esri REST Service](https://gis.charttools.noaa.gov/arcgis/rest/services/MCS/ENCOnline/MapServer/exts/MaritimeChartService/MapServer)
[OGC Web Map Service (WMS)](https://gis.charttools.noaa.gov/arcgis/rest/services/MCS/ENCOnline/MapServer/exts/MaritimeChartService/WMSServer)

**Comment by jamesdoyle21** [comment]
@kvmartin001 Would we be able to replace the maritime basemap with this new one for OTT but leave the original for our other instances to see what our internal stakeholders like better?

**Comment by kvmartin001** [comment]
@jamesdoyle21 That PR should do it.

**Comment by cpaternostro** [comment]
Could we have both types of nautical charts available, ENC and RNC?

**Comment by jamesdoyle21** [comment]
@cpaternostro would you like those as 2 separate basemap options? How would you like the UI to look for both?

**Comment by jamesdoyle21** [comment]
@cpaternostro OTT now has the ENC nautical chart. If you want to compare to the RNC, Maracoos OM3 still uses that one:

https://dev.oceansmap.com/ott-coops/
