### ISSUE TITLE
Remove Active Tropical Cyclones Data Layer Theme Info Button

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#399]
This is the only theme that has the info button. And it just says bruh

![image](https://user-images.githubusercontent.com/82955395/160465815-c279c939-60e9-4c51-871c-ca5ca0c23c35.png)

**Comment by ndellicarpini** [comment]
all we would have to do to remove the info button here is to update the themes catalog to not have a info field for `Active Tropical Cyclones`. But it would probably make more sense to re-create the theme file, as 1.) it's still hosted on github 2.) I'm not sure if all of the layer ids used in this theme file is accurate. Also, it would be nice to actually put proper info in the info sections (maybe like a list of the layers the theme will activate?).

**Comment by ndellicarpini** [comment]
ok, the plan of attack here is to create a real theme catalog file in `s3\oceansmap\themes`. Maybe I'll write up infos for each theme, maybe I won't, we'll cross that bridge when we get there.
