### ISSUE TITLE
Add Summaries to Info Button on Certain Data Layers

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#400]
For the following layers (NWPS layers) use this description: 

"The Nearshore Wave Prediction System (NWPS) provides on-demand, high-resolution nearshore wave model guidance to U.S. coastal WFOs, triggered in real time by forecast wind grids prepared and submitted by the individual offices. NWPS is maintained and developed by NCEP's Environmental Modeling Center (EMC) in collaboration with a number of Weather Forecast Offices (WFOs), as well as partners at NOAA/NOS, USGS and USACE."
**a.	Boston (NWPS Wave Direction)
b.	Boston (NWPS Wave Height)
c.	Boston (NWPS Wave Period)
f.	Boston (NWPS) – under Winds
g.	New York/Upton (NWPS)
h.	Mount Holly/Philadelphia (NWPS)
j.	SLDMB (Coast Guard drifters)
m.	Chesapeake (NWPS)
n.	OTPS Tidal Model (MSL)
o.	USGS (under point obs – also doesn’t have info button)**

"[NOAA/NOS nowCOAST™](https://nowcoast.noaa.gov/) is a GIS-based web mapping portal displaying near real-time observations, analyses, tide predictions, model guidance, watches/warnings, and forecasts for the coastal United States.
nowCOAST™ provides situational awareness on present and future environmental conditions for coastal and marine users by integrating data and information from across NOAA, other federal agencies and regional ocean and weather observing systems. For example, users can assess present conditions by creating maps of the latest in-situ weather/marine weather observations, weather radar reflectivity mosaics, cloud images from satellites, surface wind and sea-surface temperature analyses, and precipitation amounts for the last few hours. In terms of future conditions, users can obtain maps of critical weather and marine weather advisories, watches, and warnings, weather forecasts, tropical cyclone track and intensity forecasts, and forecast guidance of water levels, temperature, salinity, and currents from oceanographic forecast models.
In addition, nowCOAST™ provides users with thousands of geo-referenced hyperlinks to observations, forecasts, forecast guidance, and forecast discussions located on web pages operated by NOAA and other federal agencies to obtain more detailed data and information. For example, users can obtain weather observations from buoys operated by NWS or regional ocean observing systems, NOS tide predictions at specific stations, river discharge observations at USGS gauges, river stage forecasts at NWS forecast locations, and NOS Harmful Algae Bloom forecasts for coastal waters.
Users can display maps of this information using the nowCOAST™ interactive map viewer or by connecting to its map services. The interactive viewer allows users to zoom and pan, animate, chose different map backgrounds and overlays, click on mapped hyperlinks to obtain more detailed information, and even click at a point to obtain the latest weather or marine weather forecast for that specific location. The nowCOAST™ map services (REST and WMS) allow users to obtain maps from nowCOAST™ and create mashups with their own map layers such as coastal evacuation routes, critical infrastructure, or fishing areas.
nowCOAST™ is designed to support recreational and commercial mariners and fishermen, coastal and emergency managers, first responders, and search and rescue operations. nowCOAST™ has been available to the public since August 2002. nowCOAST™ is operated by NCEP Central Operations (NCO) in the high-availability NOAA Integrated Dissemination Program (IDP) infrastructure, where it is monitored 24x7x365."
**d.	Cloud Top Visible – 3rd party services from NOWCOAST 
e.	Cloud Top Water Vapor - 3rd party services from NOWCOAST**

"Weatherflow Observed Buoy Water Velocity (WeatherFlow Stations)"
**i.	Weatherflow Winds**

"In order to explore the Long Island Sound (LIS) circulation and the wave dynamics at the coastal area, here at the University of Connecticut we run a numerical hydrodynamic- wave coupled model in the region.  The model corresponds to the Finite Volume Community Ocean Model (FVCOM) (Chen et al., 2006a; Chen et al., 2006b; Chen et al., 2007).  The model uses a 3-D unstructured grid, free-surface and primitive equations to calculate the hydrodynamics.  The FVCOM relies on the wet/dry point treatment method to calculate water transport into and out of the intertidal zone.  This circulation model was coupled with the wave module SWAVE, which was developed by Qi et.al (2009) and corresponds to an unstructured finite version of the SWAN (Simulating Waves Nearshore) model developed by the SWAN team at the Delft University of Technology.  The SWAN model (which follows from the HISWA wave model) was developed specifically to resolve the smaller coastal scales, where shallow water processes are in effect.  The hydrodynamics and waves are coupled via radiation stresses, bottom boundary layer and surface stress (e.g., Wu et al., 2011).  To our knowledge this is the first effort to implement and validate a fully coupled high-resolution hydrodynamic- wave coupled model in LIS.

The model was forced at the open boundary with the harmonic tidal components (Foreman 1978).  Riverine discharge was limited to the Connecticut River.  Atmospheric forcing follows from North American Mesoscale Forecast System (NAM) and Weather Research and Forecasting (WRF) model simulations, where at this point only wind vector fields are included (i.e. no heat fluxes and no precipitation).  The spin up for the model ranges between 1 – 2 days.  The horizontal grid resolution (Dx, Dy) is 250 m with 11 sigma layers in the vertical (z).  The turbulent closure model corresponds to the q-ql Mellor and Yamada (1982) level 2.5 (i.e. MY-2.5), where q is the turbulent kinetic energy and l is the turbulent scale.

The bottom boundary layer follows a law-of-the-wall classic behavior, where the bottom drag coefficient follows by matching a logarithmic profile at height zab (depending on model resolution) and the the aerodynamic roughness length (zo) :

(1)where k correspond to tl.	MARACOOS LIS FVCOM Current he von Karman constant (k = 0.4)."
**l.	MARACOOS LIS FVCOM Current**

**Comment by nguyandy** [comment]
@jamesdoyle21 
These layers have to be updated from the EDS side, key 314

- Boston (NWPS Wave Direction)
- Boston (NWPS Wave Height)
- Boston (NWPS Wave Period)
- Boston (NWPS) – under Winds
- New York/Upton (NWPS)
- Mount Holly/Philadelphia (NWPS)
- SLDMB (Coast Guard drifters)
- Chesapeake (NWPS)
- MARACOOS LIS FVCOM Current

**Comment by jamesdoyle21** [comment]
> These layers have to be updated from the EDS side, key 314
> 
> * Boston (NWPS Wave Direction)
> * Boston (NWPS Wave Height)
> * Boston (NWPS Wave Period)
> * Boston (NWPS) – under Winds
> * New York/Upton (NWPS)
> * Mount Holly/Philadelphia (NWPS)
> * SLDMB (Coast Guard drifters)
> * Chesapeake (NWPS)
> * MARACOOS LIS FVCOM Current

@tgiguere @CoryMartinRPS 

Thanks @nguyandy, I'll discuss these with Tim and Cory in the standup tomorrow

**Comment by jamesdoyle21** [comment]
I am not seeing these changes for the following layers:

l. MARACOOS LIS FVCOM Current
a. Boston (NWPS Wave Direction)
b. Boston (NWPS Wave Height)
c. Boston (NWPS Wave Period)
f. Boston (NWPS) – under Winds
i. Weatherflow Winds

**Comment by mpiannucci** [comment]
the catalog service has been down so its possible they updated it and the catalog didnt grab the new config yet. Trying to make sure that is fixed and running again this afternoon

**Comment by CoryMartinRPS** [comment]
I'll check it out on the EDS end today, and give the thumbs up if/when it is taken care of.

**Comment by jamesdoyle21** [comment]
Thanks @CoryMartinRPS - take a look at #401 as well, similar issue.

**Comment by CoryMartinRPS** [comment]
Should be all set on our end now.
