### ISSUE TITLE
Remove Data Layers from Maracoos Catalog

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#401]
- MARACOOS Sturgeon Presence 
- ChesROMS Alkalinity 3D 
- CBOFS Channel layer

**Comment by nguyandy** [comment]
@jamesdoyle21 

MARACOOS Sturgeon Presence has to removed from the EDS side.

**Comment by jamesdoyle21** [comment]
> @jamesdoyle21
> 
> MARACOOS Sturgeon Presence has to removed from the EDS side.

@tgiguere @CoryMartinRPS

**Comment by jamesdoyle21** [comment]
Still seeing all three here 
MARACOOS Sturgeon Presence
ChesROMS Alkalinity 3D
CBOFS Channel layer

**Comment by jamesdoyle21** [comment]
I removed MARACOOS Sturgeon Presence and ChesROMS Alkalinity 3D from the EDS Dashboard, but we still need to remove CBOFS Channel layer

**Comment by mpiannucci** [comment]
Hopefully this change pushed through later today for the CBOFs channel layer

**Comment by jamesdoyle21** [comment]
I removed MARACOOS Sturgeon Presence and ChesROMS Alkalinity 3D from the EDS Dashboard for client MARACOOS | maracoos2016 | 314 4 days ago but I am still seeing both in the data layers list

**Comment by mpiannucci** [comment]
Yeah this is due to the catalog service @nguyandy

**Comment by nguyandy** [comment]
I just flushed the catalog, those layers are gone now
