### ISSUE TITLE
Virtual Stations - Add Select All Button, Unselect All Button, and Change Delete All to Delete Checked

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#403]
![image](https://user-images.githubusercontent.com/82955395/160473746-e507767f-a3f9-4c14-a41d-d7b6ec5270a5.png)

**Comment by kvmartin001** [comment]
@jamesdoyle21
Just wanted to show you the progress on this. I added a system to select/deselect that is separate from adding/removing the layer from the map:

https://user-images.githubusercontent.com/56608780/162044170-9617bebf-8f9c-4443-b428-cb718f6d580f.mp4

**Comment by jamesdoyle21** [comment]
Ahh, nice that's great. Good idea keeping them separate. That'll be useful for these demos with the vineyard windfarm
