### ISSUE TITLE
Change "Degrees Celsius" to *deg symbol C (And F for Farenheit)

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#405]
Most of the water temp layers are correct, but the following 3 need to be changed to match the rest:
- Mid Atlantic (Doppio ROMS)
- NERACOOS Gulf of Maine (FVCOM Bottom)
- NERACOOS Gulf of Maine (FVCOM Surface)

![image](https://user-images.githubusercontent.com/82955395/160476513-6911f97e-44f6-45e9-8d81-025437f0fc39.png)

**Comment by mpiannucci** [comment]
LMAO celsius is spelled wrong in the FVCOM EDS layer

![Screen Shot 2022-03-29 at 9 30 01 AM](https://user-images.githubusercontent.com/1832671/160622450-40e01071-389c-4a47-92a6-67eef48ae678.png)
