### ISSUE TITLE
Color Palette Not Changing for Wind Layers

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#407]
None of the wind layers in the Maracoos catalog are updating the color palette

![image](https://user-images.githubusercontent.com/82955395/160478186-c1440d1a-c416-4593-8cdb-563b5827f72b.png)

**Comment by ndellicarpini** [comment]
this is somewhat related to this https://github.com/asascience/ott-coops/issues/334. It turns out that eds wind layers use a different request format for updating things like density & palette that's different from every other eds layer :)

**Comment by ndellicarpini** [comment]
^ this guy is a liar, this pr has nothing to do with #334. EDS Wind layers use their style to determine the color palette, while all other EDS layer types keep styles & palettes independent.
