### ISSUE TITLE
Selecting a Date in the Past on Timeslider that has no Data does not Trigger Warning

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#408]
When a data layer is up to date, but the user selects a date in the past that has no data, how should we handle this? We should probably trigger a warning message. The way it works now is the data on the map disappears and the legend shows (what I assume) is the valid date forward of the selected date with data

https://user-images.githubusercontent.com/82955395/160480964-ea7b8b77-64e9-4e2a-a0c5-2b449f7e2ed9.mp4

**Comment by ndellicarpini** [comment]
I'm going to treat this the same way we handle out-of-date when the data is older than the current timestamp: request the closest data to the timestamp & add a notification that the data is out-of-date

**Comment by jamesdoyle21** [comment]
I am still getting the warning notification with no data showing up on the map. I should be seeing data for the closest timestep, right?

https://user-images.githubusercontent.com/82955395/163867948-36b12351-60f7-4467-bf31-9d8eac8f3a8f.mp4

**Comment by ndellicarpini** [comment]
I just checked for this layer, and the first time they have data for (1/17 12am GMT) has completely blank data. So by requesting this timestep, we get back a blank layer. I'm not really sure this is in our control unless we add some sort of blank image check.
