### ISSUE TITLE
Add Esc Key Notification when User Selects Zoom Tool or Measure Tool

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#416]
This should just be a short, non-invasive 2-3 second pop up that lets the user know the esc key will deactivate the zoom tool and measure tool. Similar to YouTube when you watch a video on full screen.

This can be in addition to a second click to exit the tool

Sheri mentioned not knowing how to cancel out of the zoom tool 

![image](https://user-images.githubusercontent.com/82955395/160879418-8dc47d70-e8b4-4ee7-a77e-2bde2adff25b.png)

**Comment by ndellicarpini** [comment]
Sorry, I kinda stepped on your feet here. I added a notification based on comments here: https://github.com/asascience/ott-coops/issues/410

**Comment by kvmartin001** [comment]
No worries, I'm still working on other stuff
