### ISSUE TITLE
Sync Virtual Station, Custom Layer, and Traffic Light Layer UI

### ISSUE THREAD

**Issue by kvmartin001** [asascience/ott-coops#418]
- Create a selection system for layers that works separately from the enable/disable checkboxes
  - Selected layers will have a blue row background
  - Serves as the way to delete multiple layers for now, can add other actions later
- Add back buttons to all editing screens
- Add confirmation for deleting Traffic Light and Custom layers
- Add Delete Selected button for Traffic Light and Custom layers

**Comment by jamesdoyle21** [comment]
This looks good. It just needs one more thing. For the Custom Layers tool, when the user clicks save, the "Cancel" switches to "Back" - as I would expect. For the virtual station and traffic light tool, cancel never switches to back like it should

https://user-images.githubusercontent.com/82955395/168124152-ff9cde44-224f-4149-b152-1e1ac0cd723d.mp4

**Comment by jamesdoyle21** [comment]
One other small thing. When you have a layer saved and edit that layer, virtual stations looks good, custom layers looks good, but traffic light tool opens the edit page with cancel and save highlighted, not back and save like the other two.



https://user-images.githubusercontent.com/82955395/176214962-8a65f663-a57a-4053-ba00-a5d785836f3b.mp4

**Comment by jamesdoyle21** [comment]
@kvmartin001 this seems like an easy win. Just need to change the cancel button in traffic light layers to act like the back button in virtual stations

**Comment by kvmartin001** [comment]
@jamesdoyle21 I'm planning to tackle this tomorrow morning. This is caused by the traffic light range slider causing too many value changes in the form, so it's a bit tricky
