### ISSUE TITLE
Remember Right and Left Map Timeslider Positions with Compare Tool Toggle On/Off

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#421]
Currently, the compare tool will remember the layer left/right/whole map settings when the user turns off the compare tool, but it resets the left and right timesliders. If it could remember this it would be useful for things like the permalink and screenshot when the user wants to turn it off briefly.

https://user-images.githubusercontent.com/82955395/161619878-8ea00e57-7127-4352-b149-f7ba846b1f4c.mp4

**Comment by ndellicarpini** [comment]
does it make sense for the time to be reset if they turn off compare mode & they update the timestamp? The dilemma I'm running into right now is I want the 2 map times to be up to date if compare mode is off and they update the "global" timestamp, but obviously that would clear whatever they had set before they turned off compare mode.

**Comment by jamesdoyle21** [comment]
Yeah I would say that if the global timestep changes at all (whether the user changes it or it gets refreshed at a new "now" time), then the times should be reset in the compare tool. We don't want to show out of date data without the user knowing.

But if the global timestamp doesn't change, the compare tool should remember where it was

**Comment by ndellicarpini** [comment]
ok sounds good, just to be ultra clear these same rules apply to elevation/depth/sigma

**Comment by jamesdoyle21** [comment]
Yes, exactly
