### ISSUE TITLE
Support Permalinks >2000 chars

### ISSUE THREAD

**Issue by ndellicarpini** [asascience/ott-coops#427]
We technically allow this right now, but we have the warning for a 2000 char limit. I don't think this limit applies to any browser outside of IE and *maybe* Edge from my research. I've definitely used permalinks longer than 2k chars and they've worked perfectly fine (Chrome), so maybe we could use custom error messages based on user's browser. 

Here is some of the info I've found: 

- https://www.geeksforgeeks.org/maximum-length-of-a-url-in-different-browsers/
    - this says chrome has "2MB(2048 char)" limit, but each char is not a KB, and I've used >2k length permalinks before
    - this says edge has a 2048 char limit, but a.) edge is chromium based now & b.) my testing has supported >2k permalink

- https://stackoverflow.com/a/417184
    -  Again I think the Edge results are from previous IE based versions

- https://stackoverflow.com/a/31250734
    - from the same post as above, this is a cool test
    - unfortunately no results for Edge

- https://chromium.googlesource.com/chromium/src/+/master/docs/security/url_display_guidelines/url_display_guidelines.md#url-length
    - another source claiming chrome/chromium's limit is 2MB, but this one doesn't make reference to the number of chars

Note: A lot of these links reference 'Android' as its own category, but a.) most users on android are probably going to use Chrome as their browser & b.) although I can't find sources on this, surely the android WebView embedded browser must be chromium based right? its 2022

**Comment by ndellicarpini** [comment]
After some **very** scientific research, I think we are server-side limited to 8196 chars, and I don't think any modern browsers would fail to support anything under this limit.

**Comment by mpiannucci** [comment]
We should have some kind of test URL table we can verify it all against as browser versions change
