### ISSUE TITLE
Add Station Group Name and Data Type to Tooltip when User Hovers Over a Station

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#429]
Oceansmap Bug tracker line 7.

For all Point Obs stations - include the group name of the station (CDIP, CO-OPS, NDBC, etc) to the hover tooltip

For CO-OPS stations - include data type in tooltip (Water Level, MetOcean, Currents, Meteorology)

For CO-OPS stations, do these have names in addition to the ID number we show in the tooltip? If so, include this too.

![image](https://user-images.githubusercontent.com/82955395/163205432-633ca77f-0a1c-4784-b516-e2ffd4949181.png)

**Comment by kvmartin001** [comment]
@jamesdoyle21 I don't see any title other than the ID numbers.

**Comment by mpiannucci** [comment]
This is not correct yet, this needs the station title. They are currently not available in the catalog, so we need to work on getting them into the catalog
