### ISSUE TITLE
Allow User to Input Lat / Long for Multiple Virtual Stations

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#43]
Google Sheet Row Number: 6 (Offshore Wind)

Want to be able to: Verify accuracy of wind turbine nacelle anemometers and direction vanes
So that he can: Determine if nacelle wind observations have drifted or are otherwise in error, since turbine control is governed by these observations

Does Oceans Map already have this functionality?:
Located where in OM?:

Inputs: "Turbine SCADA data
(from nacelle) vs. Validated NOAA Forecast Model"
Outputs: Scatter Plot with Correlation Stats

Feasibility: Yes - permalinks and virtual stations

Notes: Probably cannot compare to their data. But - Create a virtual buoy fleet by uploading lat longs

Need to contact turbine OEM (Siemens-Gamesa) for more info and past experience with anemometer drift

Example: https://tidesandcurrents.noaa.gov/ofs/tbofs/tbofs_mcf.html

**Comment by mpiannucci** [comment]
See #49 for more
