### ISSUE TITLE
Current Direction Station Data shows Intervals of 3hrs in Obs Drawer When Data Intervals are 6 Min

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#430]
OceansMap Bug tracker line 17

When the user selects a station with current speed and direction (CO-OPS cb0701) the Obs Drawer plot gives data points every 6 min for water velocity but 3 hrs for direction. We understand the arrows would become unreadable on the plot if they were positioned at ever 6 min, but the hover tooltip should at least give the direction data at every 6min

![image](https://user-images.githubusercontent.com/82955395/163207367-c5787bd6-d765-4359-9380-208b3445fcd5.png)

**Comment by ndellicarpini** [comment]
I looked into this a little bit and unfortunately this would be a lot of work. Highcharts doesn't seem to support allowing interactions between wind barb objects, with the barbs themselves being the only interaction points for the tooltip. In order to fix this, we would probably need to fork Highchart and make substantial changes to how its tooltip works. Is something like that worth the work?

**Comment by mpiannucci** [comment]
Not right now its not. Just curious, can you make sure that oceansmap 1 has the same behavior?

**Comment by ndellicarpini** [comment]
OM1 actually doesn't use barbs at all, it uses a scatter plot with the y axis being the direction of the current. I'm pretty sure if we did that on OM3 it would show all of the data, but is this a better visualization than the barbs?

![Screenshot 2022-05-10 134607](https://user-images.githubusercontent.com/22432482/167690919-aff3df32-3608-485b-9a3d-8dcd054382ac.png)

**Comment by mpiannucci** [comment]
Not sure @jamesdoyle21 Lets add this to the list to discuss with chris tomorrow

**Comment by jamesdoyle21** [comment]
Could we remove direction altogether from the plot and only show it in the tooltip, like the vertical profile plot does?

EDIT: I see that it is 2 different parameters for station data. Scratch that

@cpaternostro we will bring this up in our meeting tomorrow

**Comment by ndellicarpini** [comment]
where is this issue at?

**Comment by mpiannucci** [comment]
> where is this issue at?

What do you mean?

**Comment by ndellicarpini** [comment]
> Could we remove direction altogether from the plot and only show it in the tooltip, like the vertical profile plot does?
> 
> EDIT: I see that it is 2 different parameters for station data. Scratch that
> 
> @cpaternostro we will bring this up in our meeting tomorrow

Was this brought up? Should we convert this to using a scatter plot rather than barbs? Do we want to spend the effort to fork highcharts and allow invisible interaction points between barbs that have data?

**Comment by mpiannucci** [comment]
@jamesdoyle21 @cpaternostro  Do you remember what our consensus was on this?

**Comment by cpaternostro** [comment]
It looks like the data for wind direction plots
<https://dev.oceansmap.com/ott-coops/?permalink=N4IgtghgDgQjD2APEAuUB9Azgd1aANgHYDmqAtAOwAcAdAIwCcDADMwKx0BsFFALL2woAaEPggAXVAGY2NKtWYAmClN6K6Uqpwa8AviPSEApnlElyfGp2aaZOrVTYMRYySikUayqVLpV5igxU6oq6+uDQAMriAJ74JmggAJYAJqggEABOAMYA4kmYACrwUPDEmdAAFknZICKEEGAJIMWl5VU1dSDilQCuYABGDUn46ZXi4lCYKAD0M5hGmQBuizRZ2cQF8IT4ScY02fBgM+ubmDOZRpji84tLNVczAOrwmfgp6K3w6ACy0DN-KCRO6LGbiEZGGbMKFQrrXOIJUArTKYJLbVBUESYeC9HJXUziEplCpQaq1RKxKDNCrXRZdcHxTCoADaIHGk2mcwWy1Wpy2Oz2RgORxOOTOFyuN2592yjxebw+X1+-0BwJ5mTBEJmwAAXrptTF9cBELoQABdEQMoyRJI6hKKNicEQScSZJIDXrg9EoEAAUUwbqEAAJclkwHtg7lfTAAMIAeWDADk4wBBFNBxO5AAiMeDEEIKSD8B6iyDh0IrvdnteTLCLggMUWTJQzNAqXShLaJLJ9JiVPSNPEdKxOLxHaJ7VJnRE4cIOvgR1QzBnEEQ88XKEUoTNdZA2DAmGBEz2xGbwHC2VxlwrgMKSSatKg6UUSkUZGYnHfVEKjBQrD-zA0KwzAAFpdJAUB3g+Q5QAASvmxAJKyL5bu+n4foUzC8ABAFAawYEiChb4fmQdDMJh2H-qweGgeaIi9IQSTiJEMS0mA6RNJWtRYkY8TZEOKSRLKDRuvAAAyDZNiyFogNimQCRJjaZAAklmzasocEDXLsxhMiIhwlJg6CHPgfFeoQdEgCkEgQDGNn4GUABiIxDpkeDhPAAzShIaKEAAClkjRGK56lWTZNDwLK+aYBBwpgCgWiaCwdBkKl2B7B8mBUkYaQiNZ4gQBFUWEDF0BxQlnBJcwKVpRl6AAGaZEc6ApEklz8b5lmed55kxvADkoqY+WFZFRjRbFhzxYlVDJalZALBAWC4vVECyuglRGEkxDjOgjRQLs4i9CkRgtb0J2EugRgAI69CM7puv06Cjfm6DgsdYyYPgAAUpG8M4QZkcwACkwYzUDACUXTDUVY0lRNRwVVVNVkNgEiLEtmQrWtG1bTtEADPAKzoJc9WLEYhBrfl-Qfd9gTBoDINBtoENQ+Fz1w2Vk2IzN1VzdsJ2zp6J2o656DxCsow+pUn0-YoUhOgDrCM46LN5WzxWlVA5XTbNqUQG1r1GGAVIVIdlw019jj00rwYOqrYUFTD42cwjOu87VBZYNlaQ+gAxPV9WcA4rOO+zmva5VPPI+lnuNc1rXteZ6S+4oKQvgMFAhyNGvw1Nke6yjdVZUYOVPfV6DEL01wW6RfjW8DwaaPb0Nh7n3MF-rmToFAlyYJguLNNL32kcwmKKw3TNUCz4QQTGuzZAA1r6KwVqYRDEBJbgEBI0ieDYgRKC45goJQnBAVQUiBFQ4SlHsW8gMgKBkVbIAxKgGgMOEpMSAP6mgIhRxgqZDfhSPszQ-LwDvl0AymRWoNCHOpU+59L68HYMwFgPhFBCA8EBS+VBeAyHwYwTgnA2BsB3JaMB6RHJjTNiYEQPcSiLHBPiUB-YfS3wrHGLyXRUjk3BPVJIdIfQtxzi7POSMuhiCUnecQ8R0jxjIHGPykQgzRB8tsPS3QmLyJ9G7OgcIYiDH6hJAYvF0g-GCnGYqUid7uD3pfFgWDRDeiQaPRxmIQBQCyPw9IBkpjGX6mZTqIgcTiHyjlVAK18ALFCZ6CJKQYzVgDukOgiheHlkTEFdIRwpB-EyAvRYylyxdB7veLIMQ+oDXSB4CgRgBhUDhEYcs1lgFVNeOkVgAcUmWmYUkCp7S3I+mAsBEA4RpHCLbD7EArdoAoH8UZEywT0SUPYbJIxBNRgjlxLKHJYioDzIXAEpZzSk71hiGE0wNRthkHKYhUwDQmgcSyIUzIZBcn5NecUm5KVan1KoO+Zg3T6qApGV0CASx9ZiAGLo6JCxwjXMIGQbxKQ4GkD-CIRFZAICmXgNgd5yIxBPhQK6M6N99arzQLubEOzmizIOQswJplTkhNkgVIc7l9D-yMIA10IDQCUnAZA1e+kFywL2GjRBFAz7uMUKgtg6CbCX2wQ4xQ+DCG8GIaQ8h4RBXUNoQPUpTUTYsLPN0KhHDhXiG4VovhFYkiCOEd0SUTsOZay5vo2xMidHNEUco1R6jzJaPBHI5onqsQbJMfjcxPpLHWpsfWNwOD95OJcK46VyCr4MJ8ZSkAjKTkdRWTM+JaMfakqMHE8JpakmEhST6NJGTthZKeT6D5LyiklIYW6SAbT+odL0SmGAFAcxNJaQMvtQyQB0BTI5Wdjl6R9PHdU4ZIzmBjPOZM5I0z6WHMMky5ZFlVnNEwJGrZslRy7Nbfs3dxygksqLdIy5iQsV3MRCAR5zQe2vPeWAPJ7aVLllImQKgg7h0xlIjOudoLRnOkhSMfGsKcXwsxYBlFaKlwoZuTihy+LCaLCJagct5KoFUvCDSscV7YaaxvYsu9hbD1srRpyiheb56FJSDQn+5tEgAM4sAgkFqQAQKgaK14cDJUsjcRfOVaCMHKuTXgghbAiEMBIWQljeqfScboUaph8khFms014q1NreHHXtY6ydoiqNt3DaISSmRZG6JAH6lRaj2W+WDT69IdmT3GPwKYmNIA43WNhrYpNqrU0uIsifDNsqgjZuvG4PNRzaPMvo10MJCSolIYrcWqtAka3wDrVO9JmHCDNrpb+z5Hai1lJ7ZUidNSeD-NHdsVpjXl0gC6d0hd+ml39u66u9d9mlJXO3de-NdGznmrWX5zZcIL10sm6l-d96GOPs9FcwDr6HnZJ9F+xYP6-0FNq0i35LWGmAuBdB1g4K4PQsQzEowCLUMQFRSeDDyRAPYbxQS-D0BCOZDJdmkj54yNLb2TZuZU30szeuEx0juggA>
displays it hourly and looks great.
Also, just checked, the currents direction plots
<https://dev.oceansmap.com/ott-coops/?permalink=N4IgtghgDgQjD2APEAuUB9Azgd1aANgHYDmqAtAOwAcAdAIwCcDADMwKx0BsFFALGwIA0IfBAAuqAMxsaVTpJbNJAJjYUlnOgF9h6QgFM8IkuT41OSqtIa85chlWGiJKSRRrKqFRkp6-J7Fo64NAAymIAnviGaCAAlgAmqCAQAE4AxgDicZgAKvBQ8MSp0AAWcekgwoQQYDEg+YXFZRVVIGKlAK5gAEY1cfjJpWJiUJgoAPQTmPqpAG6zNGnpxDnwhPhxBjTp8GATy6uYE6n6mGLTs3MVZxMA6vCp+AnojfDoALLQE19QoVezCZiAb6CbMMFgtrnKIxUALVKYOLrVCOECYeCdDJnIxiApFEpQcqVWKRKD1ErnWZtYHRTCoADaIGGo3GUxm80WhzWGy2+h2ewOGSOJzOF3Z13StweTxeb0+31+-w5qSBIImwAAXlp1RFtcBEFoQABdYQ0-ShOIamKqTjCcRiVJxHqdYHIlAgACimEdggABJk0mAtn7Mh6YABhADyfoAcpGAILx30xzIAEXDfoghASvvgHVmvt2hAdTpdjzpQScEAiszpKHpoESyVxTQJROpETJyQpYipwnRmMlzbxzUJrWEQcIGvge1QzAnEEQ09nKGUyi0RsrIGwYEw-xGW2IdeAwXSmNOxd+uTidUpUGSymYa7IzE4L6ouUYKFY3+YNFYzAAFptJAUDXrevZQAASlmxAxIyj7Pq+L6cLkzC8L+v7-qwwHCIhygoWQdDMGhGE-qw2FAcawidIQcRiKEESUmAyR1CWlT9vo0TpL2CShJKNSOvAAAy1a1gyJpoo8vGiTWqQAJKpnWjK7BA5ybAYdLCLsBSYOguz4NxrqENRIAJOIEDhhZ+BFAAYgMvapHgwTwD04riEihAAAppLU+iOcpZkWTQ8CSlmmCgfyYAoOkPTMMRBFkGQMwQOg2DiLMWBkvoSTCOZYgQCFYWEBF0BRTFcUJUlyX6Kl6WOegCw2ek9EROguLoAkcSnDxnmma57nGeG8A2QiRj5YVoW1SVkW7NFciSFQLB0NVKVYJiABmECSugpT6HExDDOgtRQJsYidAk+idZ0V0dfoACOnQDE6jrdOgU1Zu1iT1KUmD4AAFERvAMH6xHMAApH6S3gwAlG0E1FdNpVQOVC1LfF1X1ZlmCbdtV17QdR0QD08ALOgpwbbM+iEDt+XdEMf3-coIO+mDkO+pwDCw-DwUfTNZVzSgaPLdV6xXZOLpXVjqToNETUMwDZDKJItqs6w7NsJw3N5bzxXI6j8joytSUQN17X6GAZIlOdpwK-9VBsKD6t+qo2tBQViPhbNexC4bItJdgWwvJg2VJO6ADEG0bZwdg8x7fP64LwsYwHQfoBtqR7J13X6L1bogOHygJI+PQUHHk169781+ynZCB9mWX6Dl70begxCdOcdtEXQjhqxDfqLW7CMJ1XvuLf7ZCmzLUCnJgOO2+6v2K8Rvds36MdD7rSOj7F8VPqttXrakW07QTh1iMdltnRdV0JDd7XvA9T2bD0r1gO9xVfZdXd0I+Tv92rTe8dK4Cx9rvKqAcMoy3niffG+1z7HRJmTCmVMaa33EPTRejMiJsHnH3dmxEgEV23qA6K4D95JTFugCWvY0pQNlvoeWWCAaeBZmvX0wMiGe35ijQW5DEqTzNr2S2swMELyZNglQ-92YqC4SPUhFU94CPrsHUOdtPAUGkVDCgciQG8LAZVChdc04Zyzl1Hqxk7Z0F4KrdhnAtZwx1sAkh+iyGGOUWnEOTcXjwFbu3TuzDAZ0E0fg7RuiXHlX4dVKe6AZ5nHnj9bBwTHahN9NIcJXsFFRKSmtaWjccpdxUKvZ2rMqAZJ4ZE9xB86r0KaqFVqD9s4WL6hHDaKh0icEMMEUC4ZNjpAANYegWMWIwRBiCiRcAQcQUhOA0AYGwGwTgTAoEoLM+KnhgiFC2JMkAyAUB0F-iDEAERUA9wYMESmYjsT1lAHBPY-lUgnJJJ2eoXl4DbLaDpVIXUai9mUqs-8v8HYMEkLwMFVBlC8GUIIFWcyFnSE5hQNgyhrGa03KaF5yRbK1RtoYYQM8CizGBNc0ApJ6hbOLJGNybRvrFjiBtOIVJ3TDz0ZUpRbRRByWvGIaIyQoxkEjF5UIvpwgeXWFpdo9FeXun4VCCIvQRqiR6FxPl55qZiAlc4GZcLFkiDdAC9ZqIoBpHVckHSYx9IjSMn1YQGIxD5QKSgLa+AZi2pdA6hI4YyxR2SL-GlRYYx+WSHsSQXxUj9NmPJIsbQZ43jSBEYao1khuAoPoHoVAoS53WOZR5ibHjJFYFHVg1IiVxHjXmpy7oAIARAMETlTLGxhxAPIqAMUZwWoMta5EGKuzukwPKkmgx+wYixMGvRbbdKWsMrnSxVYIh2qMBUdYZA41wSMDUOorE0gRtSGQENYad1RuXStFNaaqAvmYEW5gF7q1tAgHMU2ogejSudTMYIS7CBkGNQkH5pBvzCA-ZPQy8BsB7vhKIe8KAHQ3U2abEZaAtwDlHe6FtE6O1WpnTatEBVezOR0Lc-Q9yHRPNJZi90byPnaRnN8rYGV-kUDWUC+FYLbCQuhbC+ZILNYMCRSi-gnB0XtDIyAbFVyY2ZytsS48Qne0gApWIKlEraXAgZUy9oopuGJwMeyudsxuXSpAPywVwrRXGQlcCHl9RZX9gHYq4mKr3RetSBeDVHLpmuFmZx3gTh9UMcBZ4fFJr4MgHNXpTtmHu3NvdRlMO0H9BuvtTFr1uIfXuj9QBgNQaUNgFDduyN0b8WOkgLmka+b3RUHjDACg6ZM1FhzQm0rlaQB0HjLZWyLWS2pGBOWxrBbq3MFrbpytjax0uLQ2FjDecTI9vqP2hVQ6pKDnqKh0LU6u3TZENWBdsRAOrthCADd9Ris7r3Tlg9+Xj1kAq1V9MRFWvtfjDemtdoH0DGJi+iALr9DvqLF+iAP7Dxzgy8uz7NlQOk1mBB1AcXYMfIQ8EJDQ4UPjtW+FqbUIcOwiCIJ9IfSI0JFE7iowdy2KPJxMJijIyqOPB+XRhkBqmMgpYxCqFMLPPwu47x1FAnghkqxTizEeK5MSdLSSmT5L3mUupQBy6dLVNNZZREvh7i3NcqlfUIzQqRU4c8uZ9XZqVc2fm0qhzhm1XFk1e5jjCzvN6pMisvzhrAsubNe2ib070cJY9agV98WouJd4sl3xG1fXKH9esQNm7su5fDRdjbsbisNaTe6U96bavZp68nkAhaNrFtNKWzPZXs-9cG5tuSi6m0rbd2tiLG2+d9tswtxHy2UfV7R7Osv23Gy-b2+urLIRY+7v3XlhSv2T08DPReq9T288pFe0+j7X2fvLu-b+oH8Rfug5A2ByH0BoepBg4FuHJ4EcjqR821vk729YfOBlPDWggA>
look like they are displaying hourly also.

I'll ask my group to see if this is acceptable or if they desire higher
temporal resolution.

--

Chris Paternostro

https://tidesandcurrents.noaa.gov/
