### ISSUE TITLE
Allow User to Show Maritime Basemap Either RNC or ENC

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#438]
OceansMap Bug tracker line 55

The pint here is to give the user the option to display the maritime map they like. 

The UI here will be to add another checkable item to the top of the basemap list. The user can only have RNC or ENC checked, never both.

Look:

[  ] Show Coastlines
[  ] Show Maritime (RNC)
[  ] Show Maritime (ENC)

**Comment by ndellicarpini** [comment]
I can work on this, but where do we get the tile urls for rnc & enc? Also which one are we using now?

**Comment by mpiannucci** [comment]
RNC
https://github.com/asascience/oceansmap-3/blob/92bb49275fd84026a79232a371e221c363d96dca/frontend/src/config/ott-coops.tsx#L67

ENC
https://github.com/asascience/oceansmap-3/blob/92bb49275fd84026a79232a371e221c363d96dca/frontend/src/config/maracoos.tsx#L82

We are using a different one for each of these clients. I kinda think its confusing to choose between them, but if they want it we can do it

**Comment by jamesdoyle21** [comment]
Let's give both options to each of the clients for now. If, in the future, they only want one they can play around with both and let us know which they like better.

**Comment by jamesdoyle21** [comment]
The user should only be able to have 1 of these selected at a time. So if they have 1 on and check the other, the first should turn off

**Comment by ndellicarpini** [comment]
I could make a checkbox that just says "Show Maritime" w/ a radio selection next to it for "RNC", "DNC" if that sounds good. If we are going to enforce using only 1 at a time we probably shouldn't leave them as checkboxes.

**Comment by jamesdoyle21** [comment]
@ndellicarpini neither of these maritime layers seem to be working for me. Nothing is loading

**Comment by mpiannucci** [comment]
This is a noaa problem i think

**Comment by jamesdoyle21** [comment]
This is working now. We still want to only let the user have 1 activated at a time though
