### ISSUE TITLE
Bring Full Contour Functionality to Applicable Layers

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#441]
OceansMap bug tracker line 57

Some data layers (such as Water Level) do not have the option for contours. We want to bring in this functionality to layers where it applies. Can use Atlantic Wave Height as an example of how we want contours to look.

For OTT, all these layer types should have the contour option:
Wave Height
Wave Period
Water Level
Salinity
Temperature
Pressure
Ice

**Comment by mpiannucci** [comment]
See the `enableContours` key, when true it shows the the contours section, if false it hides it. So allow them to be shown for any non vector layers (aka arrows)

```json
  {
    "id": "sig_ht_sw1",
    "min": 0,
    "max": 15,
    "defaultMin": 0,
    "defaultMax": 15,
    "trafficMin": 2,
    "trafficMax": 7,
    "rangeTicks": [0, 3, 6, 9, 12, 15],
    "enableRange": true,
    "enableTrafficLight": true,
    "enableContours": true,
  }
```
