### ISSUE TITLE
Changing Virtual Station Pin Color does not Update in Tool

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#444]
Changing the pin color updates the pin on the map, but not in the drawer.

https://user-images.githubusercontent.com/82955395/163439566-f37898fc-e248-4346-bcb5-d8f80fe1a6c0.mp4

**Comment by cpaternostro** [comment]
Nice visual bug report.  I'm going to use this as an example of how to
submit bugs.

--

Chris Paternostro

https://tidesandcurrents.noaa.gov/

**Comment by jamesdoyle21** [comment]
FYI, the color does eventually change in the toolbar, it just took 10+ minutes

**Comment by kvmartin001** [comment]
I'm going to look at this outside the big layer selection PR (it also happens in that branch). Could have something to do with the way these icons get loaded in, which is a bit complicated.
