### ISSUE TITLE
Allow User to Customize Observation Drawer Plot Colors

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#445]
This happens pretty frequently when I am trying to plot multiple models in the obs drawer. We talked about doing a better job with the default colors, which we should do, but there are so many data layers that can be plotted together that we should allow the user to customize it.

Another thought is, could we choose the color of each line on the fly? Meaning, the first line plotted is always blue, second is always red, 3rd green, etc? This would at least solve the issue I am getting below.

![image](https://user-images.githubusercontent.com/82955395/163455470-463a2e77-9e54-4fce-844e-0e4a79d89066.png)

**Comment by mpiannucci** [comment]
Half of this is addressed, with Nicks commit there is now a color picker for the line color when clicking the legend

To finish this out we prob need to mod the logic to make sure we are making different enough colors by default
