### ISSUE TITLE
Expand Hover Tooltip and Observation View Functionality to Traffic Light Tool

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#447]
When someone is using the traffic light tool, they will not always have the data layers from the rules of the traffic light layer activated on the map. If we allow the user to turn on the hover tooltip tool to see what the values are at a specific location at the traffic light spatial layer, this will allow them to quickly see what rule is causing that area to be red or yellow. This has come up for me a few times while trying to edit the rules to change the color at a specific location

**Comment by mpiannucci** [comment]
This goes hand in hand with what should be expected in the observation drawer when traffic lights are turned on

**Comment by ndellicarpini** [comment]
this is blocked on 2 fronts. 
1.) kevin is working on the tooltip provider and I need to update the provider to support data from multiple `catalogItems`
2.) we should maybe wait until after the layer refactor? I imagine w/ the refactor, all of the data for a tooltip/observation providers (outside of the `MapSourceContext`) will be in the internal extents of the layer, so that change in itself will require big changes to the tooltip & observation drawer.

**Comment by ndellicarpini** [comment]
So here's what the hover tooltip looks like for traffic light layers. I don't like using the 1 letter layer references for each of the fields, but I think the layer name would probably be far too long.
![Untitled](https://user-images.githubusercontent.com/22432482/179073942-b86b4615-6a8e-48a0-a88b-9e103ac163b3.png)

As for the observation drawer, I'm not really sure what that would look like. Would the traffic light add all of the observation parameters to the drawer as if you had enabled all of the rules as separate layers? Would it just be 1 parameter that creates lines for each of the different rules? Any ideas are helpful

**Comment by mpiannucci** [comment]
It should idealy just show whether the traffic light rule is red green or blue, so plotted from like -1 to 1 where 0 is yellow, 1 is green, and below zero is red. Thats the idea anyways. Its a hard problem tho

**Comment by ndellicarpini** [comment]
How would that look for everything outside of the actual plot line? What would be the value & units on the parameter item? What would show in the plot tooltip? The only thing I can think of for anything that is not the plot line is the words "DANGER" and "SAFE", and that would be a solid effort.
