### ISSUE TITLE
Bring Active Tropical Storms Layer back into Layers List

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#451]

**Comment by nguyandy** [comment]
This was added, but I just removed it. Active Tropical Storms layer isn't available anymore. 
https://www.esri.com/arcgis-blog/products/arcgis-living-atlas/public-safety/environment-layers-retiring-june-2022/

We can pull similar data using their FeatureServer
https://services9.arcgis.com/RHVPKKiFTONKtxq3/arcgis/rest/services/Active_Hurricanes_v1/FeatureServer
https://www.arcgis.com/home/webmap/viewer.html?url=https://services9.arcgis.com/RHVPKKiFTONKtxq3/ArcGIS/rest/services/Active_Hurricanes_v1/FeatureServer&source=sd

Not sure if OM3 can support this (FeatureServer) yet, I can look into it if we want to have this layer back.

**Comment by mpiannucci** [comment]
I did not build out FeatureServer support yet, but would be valuable if someone else wants to take a stab at it. AFAICT FeatureServer is a vector layer whcih means geojson withing PBF tiles the same way mapbox does. 

We should be able to work off this:
https://github.com/rowanwins/mapbox-gl-arcgis-featureserver

**Comment by nguyandy** [comment]
Nice nice, I'll take this one

**Comment by nguyandy** [comment]
@kvmartin001 , you can look at how mapserver catalog/layers were added to get you started. (boem.yml)

**Comment by mpiannucci** [comment]
IOOS dropped this link. Lets pivot nad add these mapp server layers instead of the feature server for now 

https://idpgis.ncep.noaa.gov/arcgis/rest/services/NWS_Forecasts_Guidance_Warnings/NHC_Atl_trop_cyclones/MapServer

**Comment by mpiannucci** [comment]
Working on the layer grouping now btw
