### ISSUE TITLE
Observation drawer not opening on mobile

### ISSUE THREAD

**Issue by kvmartin001** [asascience/ott-coops#453]
The Identify Tool Config commit broke the Obs Drawer on mobile. It is supposed to be disabled only while Identify Tool is switched on.

**Comment by mpiannucci** [comment]
Can we make it so if the identify is on, a long click gives observation drawer maybe?

**Comment by kvmartin001** [comment]
@mpiannucci Didn't see this until now, do you mean just the touch event, or should long click work on desktop + mobile?

**Comment by mpiannucci** [comment]
Just the touch event, so in mobile mode only

**Comment by mpiannucci** [comment]
We can leave this out for now
