### ISSUE TITLE
Bring MARACOOS CBEFS 3D Total Alkalinity Layer to Maracoos and CBP Instances

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#459]

**Comment by nguyandy** [comment]
This has to be done from the EDS side.
The layer has to be added to EDS key 314 (MARACOOS).

The layer is already in the CBP catalog (EDS key 1189)

**Comment by jamesdoyle21** [comment]
Good call Andy, I just updated this to be included in 314 on the EDS side
