### ISSUE TITLE
Improve Default Plot Line Colors

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#461]
This is a known problem that has come up before. Sometimes the line colors on the plots in OM3 are too similar to tell apart. We need to either:

1. Improve the default plot line colors (set a default list perhaps so the first line plotted is always blue, second red, third green, etc)
2. Allow the user to customize line colors

![image](https://user-images.githubusercontent.com/82955395/167198302-3fb9753b-06e5-400b-9cdb-a44b3d0532fe.png)

**Comment by mpiannucci** [comment]
See [Allow User to Customize Observation Drawer Plot Colors](https://github.com/asascience/ott-coops/issues/445)
