### ISSUE TITLE
MARACOOS CBEFS 3D Oxygen Layer Changing Colors at Different Zoom Levels

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#464]
Weird stuff happening here...

https://user-images.githubusercontent.com/82955395/167204313-1ad6f6a1-0906-46f3-bcf5-480ed90978f8.mp4

**Comment by nguyandy** [comment]
This is an EDS issue.

Open this link multiple times
https://coastmap.com/ecop/wms.aspx?service=WMS&request=GetMap&version=1.1.1&layers=CHES_ROMS_HIGH_RES_OXYGEN&styles=VIMS_OXYGEN_REVERSE&width=426&height=706&format=image/png&transparent=true&time=2022-05-08T00:00:00.000Z&srs=EPSG:3857&bbox=-8613065.329826884,4377061.516340709,-8352655.415399621,4808640.685079252

And the colors change, even though it's the exact same request.

**Comment by jamesdoyle21** [comment]
@CoryMartinRPS can you take a look at this?

**Comment by CoryMartinRPS** [comment]
I'm looking into it. I have a hunch as to what could be causing this.

**Comment by CoryMartinRPS** [comment]
It should be all set now.

**Comment by jamesdoyle21** [comment]
Looks good now, thanks Cory
