### ISSUE TITLE
Bring CBEFS Sea Nettles & V. Vulnificus Layers into MARACOOS and CBP Instances

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#465]
From the client, "For Sea nettles and Vibrio, yes, I would put these under BGC predictions. (Note that “vulnificus” and neither “Sea” nor “Nettles” should be capitalized, technically.)"

**Comment by nguyandy** [comment]
These will have to be added to the MARACOOS key as well. 

and I'll update data-catalog to put these in the correct category.

**Comment by jamesdoyle21** [comment]
Added these both to MARACOOS 314.

**Comment by nguyandy** [comment]
The capitalization on these titles can/should be done on the EDS side ("OM Title" field).

**Comment by jamesdoyle21** [comment]
OK, all set. Looks a bit odd being inconsistent with the rest of the layers, but it is what they asked for specifically. I can always change it back later.
