### ISSUE TITLE
Hide the Timeslider when User Displays Time Independent Layers

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#471]
For example, if a user activates a climatology layer with no other layers active, hide the timeslider to show that the data is not linked.

If the user has a time independent layer and time dependent layer active, keep the timeslider.

**Comment by ndellicarpini** [comment]
what is the default behavior then? does the timeslider show with no layers on the map?

**Comment by mpiannucci** [comment]
> what is the default behavior then? does the timeslider show with no layers on the map?
Hold off on this one, I did this for the zms branch I have coming in the next day or so

**Comment by ndellicarpini** [comment]
um ok so I kinda did some of this stuff w/ the layer refactor. This is the functionality in the layer refactor:
- if `!Config.timeslider.enabled` -> timeslider never appears
- else if `Config.timeslider.enabled && Config.timeslider.autoTimeExtents` -> timeslider only appears when time-dependent layers are on the map (w/ layer refactor its easy to check if layer is time dependent)
- else -> timeslider is always shown

Let me know what you think of this behavior, it shouldn't be difficult to tweak

**Comment by jamesdoyle21** [comment]
The timeslider is still showing with a climatology layer open on the map

![Image](https://user-images.githubusercontent.com/82955395/179575955-a1b0a775-3de7-4671-b293-0d1aa9db33ba.png)

**Comment by ndellicarpini** [comment]
The timeslider is only hidden for deployments that use the `autoTimeExtents` feature. I think the only version we have that uses `autoTimeExtents` is floodmap.

**Comment by jamesdoyle21** [comment]
Got it and is that the only deployment we want to hide the timeslider in? I personally think it can stay up in the other instances when a time independent layer open even if it has no functionality.
