### ISSUE TITLE
"Opendap Data access" link to Tampa Waves points to Philly waves instead of Tampa

### ISSUE THREAD

**Issue by cpaternostro** [asascience/ott-coops#476]
Minor bug

The i button on all 3 Tampa Wave products in the catalog --> Data Access needs to point to the Tampa grib data.

"NOAA Tampa Bay Wave Height (NWPS)
...
Data Access
[OPeNDAP](https://eds.ioos.us/thredds/catalog/ioos/nwps/phi/catalog.html)"

That link needs to point to https://eds.ioos.us/thredds/catalog/ioos/nwps/tbw/catalog.html

**Comment by mpiannucci** [comment]
Thanks for finding!!!
