### ISSUE TITLE
Permalinking to Observation Plot Doesn't show "Validation" Button

### ISSUE THREAD

**Issue by mpiannucci** [asascience/ott-coops#477]
Example: 

https://dev.oceansmap.com/ott-coops/?permalink=N4IgtghgDgQjD2APEAuUB9Azgd1aANgHYDmqAtAOwAcAdAKx0CcATHcwGwCMADO1VRWYAaEPggAXVAGZ2NGc26dmjKiqrs+AXxHpCAUzyiS5ClJqnmAFirNmna5cuNLIsZJRTay0zfWWKKlya2uDQAMriAJ74BmggAJYAJqggEABOAMYA4vGYACrwUPDEadAAFvEZICKEEGCxIAVFJeWV1SDiZQCuYABGtfH4KWXi4lCYKAD0k5h6aQBuczTpGcS58IT48fo0GfBgkytrmJNpepjiM3PzleeTAOrwafiJ6E3w6ACy0JPfUGHXOaTcSDPSTbjg8HtC7RWKgRZpTDxDaoKgiTDwLqZc6GcSFYqlKAVKpxKJQBqlC5zdogmKYVAAbRAIzGE2mswWSyO6022z0u32h0yx1O50uHJuGTuj2er3eXx+fwBnLSwNBk2AAC9NBrIjrgIhNCAALoiWl6MLxTWxVjsEQScRpeK9LoglEoEAAUUwTqEAAIsukwNt-VlPTAAMIAeX9ADkowBBBN+2NZAAiEf9EEIiT98E6cz9e0Ijudrqe9OCrggkTm9JQDNASRSeOahOJNMi5JSlPE1PRmOxLfxLSJbREwcImvg+1Q3AnEEQ09nKFsmmNVZA2DAmABo22xHroEI8Ew6AyvXgADMz3oYvMJMjCOgwPh8Lg0JuMliziW-nl4nqKkoBSBRbDIXgIM4PIFBQbhuDg7gaHg7gAC12kgKAAKAvsoAAJWzYhYiZMDmAgugyCkbg8m4SxEMQ5D4PQkRSIg9gIKkGi6PghiUPQ00QC6Qh4nEMJIipMAUnqUsqnRO89AyPtEjCKVaideAABkazrRkBIxNIlK02s0gASTTesmRPM8L2vW970fDYXzfXARD2CALi2fR6VcmdxnPeA3wUt1CBNEREgkCAIwi-BigAMUGPs0jwEJ4F6CUHMIAAFdI6j0RKLJAKzz0vG90Hkh9gqc992nC8QIBoeApWzTBMIFMAUHUTxGEUMheuwCQ5iwLErwgKV0DKPR4mIEZ0AgS9FnQM4rzmPRCDG2qelCkBUvS4KIwCitDFq+rGr0ZrWr2drOtUHretmCAhrSEaxomqaZrqKAtnELpEj0dBEi6P68TKgBHLpBmdJ0enQU7s3QEFfuGTB8AACjIexGH9HhuAAUn9VQcYAShqiKGqawgWugNqOvYLrbrIfrEse56-te6bxFm+a-qWla1r+jbJI9MpkZR5QsfgvG-XYRgiZJuqybOimLv2Gm6c4XqyA2P7J1dP7GcG+87yR1GyGYGRxdx-06HYWWwtJ2Glapy7VZu9XeogeI0nhvQwHJUpvrOY2UaoOgLcl1hbZAY6FfOp2Veu7q3YZ7ZXkwck9GSIWRdN9hhD9bHJdzyPo4dymoGphP6ewFP0CvNJ9n+z2gqfIOpEx-OJfxmXibt+XS+Vq7addjXq5zLB09ea90GILoLiD9HODRDvLb9Txi-t8my4rofE41j2vagM5MEwLEGmFk2eCXgv-T4SOips0ryoyqqP2ZEXbAoMOb4oWWQkwiMtgZAANaekWCWQwRBiBaXcAQCQ0gKDISkMobgwgjCkBQJQWQ3AqBIJUCEIo2wYEgGQCgRgdBOAiEiKgJgnAQjLQkKfCyoAiL7DymkKhpIuwNEyvAQh7Q9hPESNsAaFlMHIRwVYbgdBuDdSkEgoQUgEHcCQVQSwUg6CqM4IwDQDANxmi4SkWKZ0A4GBEIfQocwQQ4k4d2D0BCSxRjSu0JIq0QRXniNSD0JdN4DxdondoYhjIAXEDEFI0YyBRkymEP0EQMreQ6CJUJHpK6cGhJEPoAUtK9CNh6T4eUozkwCXAjwSjcEoNcO6MR2DcFohAFAdIriUgCL8nsQKikW4iExOIWqGdUAjXwLMTproemJAjOWK8V4UhKGccWWMuUUj7CkN8NIQC5gmWLO0Q+gF0iRH2jFJKHpFEUD0L0Kg0IFIbHCuwvZTwUjwQmRMmklj4g7JuQckAKEUIgBCIEzxTZM7bR8dAFAzTrIBRiO0lE+jbEgEwOky8QwBxYilAsoFUAQW+TBW04KRTIhdMMJUDYZBtlEUMLUeoUl0irLSJrMASyqVrOLOjSiFBjmnIgtwB5V4OWfPaBAB8gw5pJP6bMEIhLCBkHqYkIRxg4IiHFWQCAb54DYE1giMQIEUCOkBvgj24DPwhAxMiho-dgWgv8tijpsK6p9mStoZhehWGOg4aAMk3DeHgJ8oI4RfZREUCwRIywUiZHKPkYoxBzBVHqM0do9guiQhusMcY0+mz65+ysUeDoBi7EevEI4+JLiSzxHcZ4joYoY6O3Ls7FJuK5jBKSSAcJkTomxOCvEkEISGg1vRPCzJc0ckgDyXmwp1Z3DhuUcg1BMUQoYP9eImpZiGn6pAOa1pEKcVDO6QNTO2q9CbpGWMvEjyPTTPlbM+ZHpFnLOpesqFdSnSQGuQdd5VAEwwAoBmc5xYrm7OfVMhMsVAOxSeQZF5T79l3M+dwb51ZjIEoBaa9Fq7wXNzvYmj0cKMmIthYOFFl60UYsKFi9dVrAn4riAqklcJCoXtCCsuYtL6X0dMky9Wr730ZnRgBoDPKvn2gFWIXowqlWirPUSqVMr0HzgSEypVMVVXwHVdAVAu7dV8INUioc+HFZl0Iy0lDkKQrohtXCYIeiV2ANWYkIxDDA5xBYdJdhuJs0gB4Xwr1aQZUiMZFUwNwbZFhtKZGtRGjLBaJ0XQcz6GQA2ZMamixoHrGupc-YvNTj5W-SLSW953idO+O7aIbSaR60NCbVEmJNqnztsSV2neig0lYayQOodBTFZFLHUF7qU7KlzuqcoWp9TfzuBXZii1JG71dJGX0kTe7trDO3Ye68kyT3MBmRsOZFLL10uvYyu9WzH2-og4c1lJyzlyW-a8v9Hp7kPJAyCS7R2PlQZg4VuDFGEMEeQ5atDLnMMIuhLhk1n3RtrtQ0Z175GmxMqo2S2jj7qWMZ2yxol6sjmnY5Vy3j8E+UCaFbEEVegxVMokweOcYmJVyZVWquYGqVNpB1Yu9TwBNxGq04CvLZqQcGY3dagadrNBAA

**Comment by jamesdoyle21** [comment]
I don't see the Validation button at all anymore, permalink or not

![Image](https://user-images.githubusercontent.com/82955395/174656526-3f085ce9-0fae-4a67-8be6-63f78c251955.png)

**Comment by ndellicarpini** [comment]
the validate button only shows if you have a point observation station selected

**Comment by jamesdoyle21** [comment]
Ah right my bad. Brain fart. Well on that note, any particular reason the Obs station layers are not in the data layers list for OTT? I see them in client demo

**Comment by jamesdoyle21** [comment]
That permalink @mpiannucci posted on this issue does not open the obs drawer or have any station layers on

**Comment by ndellicarpini** [comment]
the permalink probably isn't valid with the changes I had to make for this issue, but it should be possible to create new permalinks that show the validate button?

**Comment by mpiannucci** [comment]
@jamesdoyle21 Andy had to clear the catalog cache earlier. They will probably be back later

**Comment by jamesdoyle21** [comment]
Got it. I'll put this back in the In Review section and test later
