### ISSUE TITLE
Changing High Value in Traffic Light Tool Changes the Low Value

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#478]
When I manually set the low and high value of a rule in the traffic light tool, the low value gets switched to the first number I type in the high value text box.

https://user-images.githubusercontent.com/82955395/171702628-1d7b1ef4-6006-4042-9864-28e173cf4407.mp4

**Comment by ndellicarpini** [comment]
what's happening here is the high value is being set to 2, the range slider notices that the high value < low value, and so the low value is set to the high value. I can get rid of the check that validates that the low and high values are low and high respectively, but I don't know if that could cause issues?

**Comment by jamesdoyle21** [comment]
Maybe do the check when the user saves the layer?
