### ISSUE TITLE
HYCOM 3D Region 1 crashes when hovering over Observation Plot

### ISSUE THREAD

**Issue by ndellicarpini** [asascience/ott-coops#483]
Trying to create the observation plot hover tooltip for Maracoos `East Coast (HYCOM 3D Region 1)` causes a crash. This is because the data for the layer in the observation plot is "No Data For Selected Point!" for all points on the graph when the clicked position is outside of where the valid data of the layer is. 

I'm unsure how to handle this because a.) it's maracoos b.) it's kinda a data issue, but we probably shouldn't crash because of it.

Permalink: https://oceansmap.maracoos.org/beta/?permalink=N4IgtghgDgQjD2APEAuUB9Azgd1aANgHYDmqAtABwBsAdFQCwCcVjrADE1RQOxUA0IfBAAuqAMxi63CmO6N6sgKwAmbvQC+A9IQCmeQSXLc2NNtwCMEswzEKLAoaJT1zNet0X1li7mMWtqc3VNcGgAZWEAT3w9NBAASwATVBAIACcAYwBxeMwAFXgoeGI06AALeIyQAUIIMFiQAqKS8srqkGEygFcwACNa+PwUsuFhKEwUAHpJzB00gDc5mnSM4lz4Qnx43RoM+DBJlbXMSbSdTGEZufnK88mAdXg0-ET0Jvh0AFloSe+oMOuc0mwkGOkmbHB4PaF2isVAizSmHiG1QFAEmHgXUy530wkKxVKUAqVTiUSgDVKFzm7RBMUwqAA2iARmMJtNZgslkd1pttjpdvtDpljqdzpcOTcMndHs9Xu8vj8-gDOWlgaDJsAAF7qDWRHXARDqEAAXQEtJ0YXimti3n4qVGaXivS6IJRKBAAFFMI6+AACLLpMDbP1ZD0wADCAHk-QA5SMAQXjvpjWQAIuG-RBCIlffBOnNfXtCMJHc68YiQMEHBBInN6SgGaAkik8c1CcSaZFySlKcJqejMdiW-iWkS2gIg4RNfB9qg2BOIIhp7OUMplOpjVWQNgwJgAaNtsR66AIPMymk0ugzFgLtoIJgIPpm+6wBlMBdoVEYj37320u09nwJ4AAUIBiUYKV-IEsgACQAJTCMI8nQAAZegvgAVTg9AAQgHCsQAMwgKU3h0MByVKYQsT0atazSSMoGI+IolQcw2HnEALkdRJYg40oSDhcBtnIRQF2QFA-BCScRLE8RRJAHiiK6fBhE+YSUDIeTFIgZTVMXOSBG03SMJXEBw3aLpTPMs1SgIgjKjUwg5xsiA7Ic-SJI4nRal6GI4KzYhYhLLodAEbyIF8nQ8ls+yMhQ+JiBGVBgtCkBwsi8MNjxLF6xSgR+MCvJKgAa3rBlNL4edRLYvhzFE5R528PgxHnPxTRAItsrSTKgP-d0AGJ2KGth2iMlTMuLQceqeFJBuGkawp8mJgLOWZhHrIj8FmQydCUlSVvOHR1sjJyUE27aFN2nT9tWo6ARiDI+2SFBCGU-ABCgW71sZTcwsSTB0DKSI9jAdAxFeNJzHQDIsTOYtjy3GGL28vSoCK+oqSgFIGrXMg2CoMhzHoPJzG4FB2PJkwhoALXaSA0fiDG+ygfyBMZEAceUPGCfMZQ8g4SnKdMdjaYETnucJqh+foQX2OFthafapG4eEVMdCgTpnJALpCGYsJIipMAUnqEtx04nQHqesIpVqR14BQms6x+gc0ieh26IASVTMq0v+wHgf2MGIah5WUfpAQ9l-LZdHpdrEhECBwwToDiAAMUGP99C4w8UnBysBHgXoJREZFCFA0oTadhtfYBoGQaD9BIeh2Gw5NAui+uEuNmmis4h0P268D8HG5Dlv4eGTB8AACjENFfTYtgAFI-VnxeAEp89CKBwy2DJio9RZi30IhiAdpwCEMDTeDcZQieUCgvDYfwxEYMRqycF-TDY+gOFsCgfBauuD68BtjnxAOJV+5gBCRFQMoeQIQCI6BENRMqm51BAA

**Comment by jamesdoyle21** [comment]
Do we know when the user clicks a position outside the limit of the valid data? An error message that says this is probably something we should have across the board for OM

**Comment by ndellicarpini** [comment]
Yea we actually do, looking into it a bit more it turns out that our valid data check does work for multivariate data (like mag & dir). I'll fix it today.
