### ISSUE TITLE
Show warning when a user tries to create a Traffic Light layer from layers that don't overlap spatially

### ISSUE THREAD

**Issue by mpiannucci** [asascience/ott-coops#484]
Traffic light layers composed of layers that do not have overlapping bounding boxes will always show as no data (grey or transparent). Show the user a warning message when this scenario is selected

**Comment by ndellicarpini** [comment]
Should I also do this for no shared time extents? I already get the extents when a rule is selected so I could add the warning (right now it just requests the traffic layer at the current map time if there are no shared times, which I've never seen return anything but a blank layer).

Also should this be an error (blocks user from saving the layer) or a warning (notification)?

**Comment by jamesdoyle21** [comment]
Seems like the red text warning message is what we want for both imo
