### ISSUE TITLE
Add CO-OPs Station Names

### ISSUE THREAD

**Issue by mpiannucci** [asascience/ott-coops#487]
Currently we only have COOPS station iDs, we need to also harvest the names and catalog them with data-catalog

**Comment by nguyandy** [comment]
ex: co-ops station 8534836,
https://data.oceansmap.com/thredds/dodsC/coops_ag/8534836/8534836.ncml.html

the title is "8534836" on data.oceansmap,
but here https://tidesandcurrents.noaa.gov/stationhome.html?id=8534836 it shows "LONGPORT, RISELY CHANNEL, NJ - Station ID: 8534836"

**Comment by mpiannucci** [comment]
I think this is the harvester https://github.com/asascience/data-harvesters/blob/master/data_harvesters/harvest_coops.py
