### ISSUE TITLE
Change "X" to "-" to for Profile Plot and Observation Drawer

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#488]
Jeff brought this up a little while back. The profile plot and obs drawer don't actually close now, they just minimize. So the X should be a minimize symbol. This may take some playing around with what looks best because a little "-" may not be obvious enough

![image](https://user-images.githubusercontent.com/82955395/174656043-9c883c38-b062-4400-9b17-c89bb49d1be7.png)

**Comment by ndellicarpini** [comment]
We actually played with this a bit already and it didn't look great, open to suggestions though.

https://github.com/asascience/oceansmap-3/pull/396#issuecomment-1149032134

**Comment by jamesdoyle21** [comment]
Alright, if you already looked at this I will just close it. People will understand it is just minimizing with the box in the corner
