### ISSUE TITLE
Duplicate TBOFS Water Level layers, Missing SFBOFS

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#489]
Something got mixed up because there is no SFBOFS for water level but there are 2 TBOFS. The info button in bottom TBOFS is linked to San Fran though

![image](https://user-images.githubusercontent.com/82955395/174664555-2a7fd742-d4f3-4739-a728-feb42f2d1dcd.png)

![image](https://user-images.githubusercontent.com/82955395/174664577-d24237a9-0628-4a68-87f0-730fb24d72b0.png)

**Comment by mpiannucci** [comment]
Typo in data catalog, deployed and should be fixed after catalog update
