### ISSUE TITLE
Add Functionality Allowing for Multiple Virtual Stations 

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#49]
Google Sheet Row Number: 6 (Offshore Wind)

Want to be able to: Verify accuracy of wind turbine nacelle anemometers and direction vanes
So that he can: Determine if nacelle wind observations have drifted or are otherwise in error, since turbine control is governed by these observations

Does Oceans Map already have this functionality?:
Located where in OM?:

Inputs: "Turbine SCADA data
(from nacelle) vs. Validated NOAA Forecast Model"
Outputs: Scatter Plot with Correlation Stats

Feasibility: Yes - permalinks and virtual stations

Notes: Probably cannot compare to their data. But - Create a virtual buoy fleet by uploading lat longs

Need to contact turbine OEM (Siemens-Gamesa) for more info and past experience with anemometer drift

Example: https://tidesandcurrents.noaa.gov/ofs/tbofs/tbofs_mcf.html

**Comment by jamesdoyle21** [comment]
Allow the user to work with multiple virtual stations at once. This is part 1 of 2 tasks relating to the same user story. Task #50 discusses the addition of permalinks into this feature.

**Comment by mpiannucci** [comment]
Currently only one virtual station is defined at a time. Add an option to pin the virtual station for select later. Can add a separate sidebar app for managing custom stations as well (naming, customizing appearance, etc)

**Comment by jamesdoyle21** [comment]
When the user clicks on the station name, pop open the model data plots. Clicking the checkbox should check/uncheck the station but clicking the station name should open the model data plots (currently it also checks/unchecks)

![image](https://user-images.githubusercontent.com/82955395/127048833-1bc1d99e-58f1-4c27-b958-b7b0b82f8fb3.png)

**Comment by jamesdoyle21** [comment]
Add a button to navigate the current view on the map to center the virtual station – like the magnifying glass + does for data layers

![image](https://user-images.githubusercontent.com/82955395/127048983-fd54c0d2-3e30-4bcb-8868-98b20ada27d5.png)

**Comment by jamesdoyle21** [comment]
Check for duplicate virtual stations. Currently, when the user imports a list with some of the same stations already in the viewer, they are duplicated.

![image](https://user-images.githubusercontent.com/82955395/127049094-d2442073-2177-4f6a-a2be-c8105cbf63e0.png)
