### ISSUE TITLE
Using the "Active" Filter in the Data Layers List Should Auto Extend the Data Categories

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#490]
Just noticed this now that we minimize the categories in the client demo version. As is, it is too many clicks to reopen each of these to see your active layers. This screenshot is from a permalink I had saved from before this minimize categories change was made. I think the map view filter can stay as it is now, but open to input there.

![image](https://user-images.githubusercontent.com/82955395/174666320-e89470f0-398c-4cf7-8d00-df6f2c9c42ae.png)

**Comment by ndellicarpini** [comment]
should enabling either of the filters or searching extend all of the categories? If yes, then do we close them all again after the filter has been removed? 

My personal opinion is searching/filtering should open all of the categories, and they should not re-collapse when the filters are turned off.

**Comment by mpiannucci** [comment]
Correct @ndellicarpini

**Comment by jamesdoyle21** [comment]
> My personal opinion is searching/filtering should open all of the categories, and they should not re-collapse when the filters are turned off.

Yeah I like this. Probably easiest too
