### ISSUE TITLE
Make Streamflows the Default Option for Winds and Currents

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#491]
This may take some testing the streamflow inputs each individual layer, but it is worth doing because streamflows are awesome and they are pretty hidden by default

**Comment by mpiannucci** [comment]
No, this is 100% up to the client. Whatever @cpaternostro wants for defaults views of winds and currents is what it should be for OTT

**Comment by jamesdoyle21** [comment]
@cpaternostro thoughts?
