### ISSUE TITLE
Add a Collapse All / Uncollapse All Button to Data Layers List

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#493]
I can see users liking this. I would use it if it were an option. Probably a low hanging fruit item too. Thinking a little button next to the word Filter that highlights when activated and has a tooltip that says collapse all / uncollapse all depending on the state

**Comment by ndellicarpini** [comment]
How does this look?
![Screenshot 2022-06-27 120315](https://user-images.githubusercontent.com/22432482/175985524-0c216a60-0bf4-4973-9c30-eaf860703337.png)

**Comment by jamesdoyle21** [comment]
Looks good to me.
