### ISSUE TITLE
Observation Plot not Showing All Timeseries Lines when Permalinked

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#495]
When the user opens the permalink below, both checked items do not always show in the plot (it seems like sometimes they do and sometimes they don't - try it a few times). The only way to get both to show up in the plot is to uncheck and recheck each. 

It also seems like toggling on/off 3D currents will make station current speed turn off on the plot.

https://dev.oceansmap.com/ott-coops/?permalink=N4IgtghgDgQjD2APEAuUB9Azgd1aANgHYDmqAtABwAMAdACxUDMFFAbAOytXsCsVP7ADQh8EAC6pGPGgCY6ATh495FeezrsAjLx4BfYekIBTPCJLl2jWRQU3G9xauGiJKRuxoVN91jL8D1JTpdfXBoAGUxAE98EzQQAEsAE1QQCAAnAGMAcQTMABV4KHhidOgACwTMkGFCCDA4kELi0oqqmpAxcoBXMAAjOoT8VPKxMShMFAB6KcwjdIA3eZoMzOI8+EJ8BOMaTPgwKdX1zCn0o0wxWfmFqoupgHV4dPwk9Gb4dABZaCmfqHCN3mUzEQyMUyoEIhHUuMTioCW6UwCU2qAowkw8G6WQupjERRKZSglWq8WiUEaZUu8w6oNimFQAG0QKNxpMZnNFstjhstjsjHsDkcsiczhcrpzbpl7k8Xm8Pt9fv9AVz0iCwVNgAAvXSaqK64CIXQgAC6wjpRnCCS1cRkPFYwnEYnSCT63VBqJQIAAopgXYIAATZDJgHaB7LemAAYQA8oGAHIxgCCSYD8eyABEo4GIIQkgH4F15gH9oRna73c8GSFnBAovMGShGaBkql8S0iSTaVEKakqWIaRisTi2wTWsT2sJQ4QtfADqgqFOIIhZ-OUH5dCaayBsGBMICxjtiI3QIR4Jh0Jk+vAAGYXxhvTLY85lk-bp-pF9if75BINalQKkMhUH4ZBUKwZB+Pk-AoFQVCwbQcFUAAWh0kBQL+-4DlAABKubEHEzLAaB4FkJo8jQXQCEITQSGocIxEyGBEEyIwlHUXBtFwahZogB+X4ZkYUBdAuwjdIQCRiOEUTUmAqQNOW1QYkYsSZAOSThNKdQuvAAAydYNkyvGYuk6n6fW6QAJIZo2zJnheV63vej7PkYr4dPsECXNsxgMsI+xFA58D4KpHqEKawhJOIEBRtF+AlAAYkMA7pHgoTwH0kriCihAAAoZPURgpbZIBRWIEA0PA0q5pg6GCmAKBXkwVCaGQbVzBA6DYOI8xYBSRgpLU56Xted7oA+l6ue5vEZVlYVRsFVamPZI1OeNLmfm5YiNiymD4AAFAIgaaHBACkx2MKdACUHRlRVVVGDVdX7A1SVImI6D6XmR5tWQ0ohVgCTEHU+BYM6bnECJXrlHt+0yKw6IBidVDnUjMjXbd0WVdVhC1dA9UoG9lyfbmSQ-W1EAJOk6BQOcmCYNijQwwdFCMMdZ2BhQ7AY5FWMPU9+MvYTVPE19ZMkL9lPUwOYAUmUYiMyMsOaHQMjsyjgZ+DzpV8zjeNQATRMfWL5NkC4kndEkTOwzw6uo7w2t3djj2489BzC+9JPfRLbXxSQFtW0rB2MIuSMcwG8gozdvPlc7AsG0LRte+LxC-dgOxvDe6QHOgZPnGpOVB3D9p24GjCsI7usu-rhsi8bpOm+neZ9UYA1F4wMiaKXAaqJXsf867gvu0nJs+2QTdvJg-VvLe6DEN0lxF9o3feH391627r118njcZ5elQhUXMhsN3Nhr3Hg8J8P2+j6nbX8Vt6AQIiEAES3bfQ8rfDd5H58DzXicb4NzHg-MsT8X5vzzkYAunpdoHU0PDFeFdo4637hvIeW9Pa31+i9KAXkLzlEeinJe8gHRhw1j3ZBmM0HV03h7UWwC75kA6l1Hq0sjCy3mOIRmT9uiIHQJoI+rAyHI1RsIv+6Cr6YIYd7JhuD8E00kpkco7ceB0G7uoCRtCMH0PrrInBBw8H03QNnQ+n94GaFtuQ1GljtYBQmJeYKoVC7mLhqwNm1jAzsG5igp2-86FsA7qzdgv0WEM3SDeCA0p0CEKBqMJ+sttgKytrnboRh0D4nQEYAAjt0IYroXS9HQAPDJyRrYHU7l3TxAYZDyC0fHAmgTj7uDTnvKercUiuPsIjURx10a+Krg0oWTTgmtOblnHOUCYHhVccfIQ1SND1Mvo09xzSQltQnu-GeN454L1cHA-a6hu7wyWQA92IyWkUypjTOm4Tyn7U0KwdR1T7SnICas0ZGy2FYGxJE6JsTiDxIgNeJYJijA3nmG5aJZVejt3sCvHx1D17aKkSgCgAhNCYvWcwx6PyIlRPSQCoFiSA7pKSGkjJnwcl5O2H0QpYBik41KYHVxJ1u4hzeTo9FWgsVp2+eEv5hKjBxI+sC+AoLzgQpfNC7hclXHyDVtU4+nLUVNRDq1dquLuopS2UXeQK9NAqoJmqlqoStXfKWPFTIkkoiUtzlTaBYV26Yu7qwOpN1QjoSjNsTIABrb0SwyymCIMQfSrgCDiEkB4FqJ10RmFICgMgnBZAKCYKEYoOxw0gGQCgWNQgQBRFQHIRgoQIXcLpkyCNFlUj2KCiFR1hchzYmlKkfx0BGpzgcfset0zuy9i9AlR6CtzgdFpkUeYoJcRkh7I0DNZYYyZQ6GUssCQbwJBpF6PxkjjV9GaoI2sFlfxiFiKkWMZAYy5XCAGSI2VNh+U6JJE9XoTX7pAJgKI-Rgr6T6CpU9U1todBcFG2imKqBxr9hYVgKbI5sxAHgr8NbO11ucaiYQWIxBlQ-pE-Acw0Pukw0kKMlYbw3lSAgpdpZ4yFVbWARgPx0i+vmJZUso6XSQHSFEBa8VUpencOwIwfQKAwmgZsKKHGuPPFSHBEjcFaQToSBkTji0eMgCQkhEAIQty6CAA

**Comment by jamesdoyle21** [comment]
https://user-images.githubusercontent.com/82955395/174885787-440ed9fb-3185-4afa-9b0a-2fdbe490f009.mp4

**Comment by ndellicarpini** [comment]
I'm almost positive this is the same issue as https://github.com/asascience/ott-coops/issues/486, but I didn't realize you could trigger it from permalinks.

I think it's really susceptible to happening when plot data is fetched & the parameter is already selected, and from my testing I almost think it might be the same flavor of error as was solved here https://github.com/asascience/oceansmap-3/pull/261
