### ISSUE TITLE
Validation Tool Only Displaying Partial Data

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#496]
When looking at current speed for some stations, the validation tool will not show any points on the scatter plot and will only plot one line on the comparison plot. The observation drawer shows both lines, however.

https://dev.oceansmap.com/ott-coops/?permalink=N4IgtghgDgQjD2APEAuUB9Azgd1aANgHYDmqAtABwAMAdACxUDMFFAbAOytXsCsAjACZWAGhD4IAF1SMeNKgE52defL495VAdV4BfUekIBTPGJLl2jGluUU6je-PUV2o8VJSN2NeVz7tFdGr88jp64NAAyhIAnvjGaCAAlgAmqCAQAE4AxgDiiZgAKvBQ8MQZ0AAWiVkgooQQYPEgRSVlldW1IBIVAK5gAEb1ifhpFRISUJgoAPTTmIYZAG4LNJlZxPnwhPiJRjRZ8GDTaxuY0xmGmBJzC4vVl9MA6vAZ+MnoLfDoALLQ079QCK3BbTCTDQzTKiQyGdK6xeKgZYZTCJLaoCiiTDwHrZS4mCTFUrlKBVGoJGJQJrlK4LTpguKYVAAbRAYwmU1m8yWKxOm22u0M+0Ox2yp3Ol2uXLuWQez1e70+Pz+AKB3IyoPB02AAC8dFronrgIgdCAALqiemGCKJbXxAQ8ETpcYZRL9HpgtEoEAAUUwLuEAAIcpkwLtAzlvTAAMIAeUDADkYwBBJMB+M5AAiUcDEEIyQD8G6CwDB0IEhdboJyJAoVcEGiC0ZKCZoBSaQJrWJpLp0UpaWpElpmOxuPbhLaJI6olDhG18EOqCo04giDnC5QAgEOlNtZA2DAmCB412xCboEI8Ew6Cy-XgADMr4x3lkcRcy2fdy+Mm+JACColGhpKA0gETQBDIKhWDITcCioHgUCoKgENoRCqAALU6SAoH-QDBygAAlXNiHiFlQM3CCoL4eRYLoZDkLkRCMNEMjwMg6DGBoujEIY9CzVEL8fwzQwoG6RdRB6QhEgkCJohpMA0kacspxAeY4iyQdkgiGV6hdeAABl60bZlzRUl4NIMhsMgASQzJsWQvK8b3vR9n1fQx306A4ICuHYjEZfj50ma94HwNSPUIPiQGSSQICjGL8FKAAxYZBwyPAwngfopUkVFCAABUyBpDFSuyQAc69bwfdAn2vNyPNEaKJAgGh4BlXNMCwoUwBQG8qGoPgyEG+YIHQbBJAWLBKUMVITMy7LwqjEKXjPMrLwq5zqtc793IkJtWUwfAAAoeBcAM+EQgBSQM+EYC6AEpOka5rWsMdrOoObresYKgBqG17RvGjJJsMabRgOw75Guy7rr4e7Hpilq2sIDroC6nr+iYH7BrIYaAdS9BlgSrIpOidACXQZJEgudTcrBo7GD4PgoaoK6A1YeQ4YahGXre1GPvRvqsb+kaxvxzAptSL0KnBm66GZ1m6FYTmou5pGUagNHev67HcdFibCdakmya+SnqfCunDrls7oYDAQ6DhsIsKjHYsgAa29ZYyxMIhiAM9wCEkaQvA4Og6AEVwzBQMhOBoNRFa3UQSl2f2QGQFBGcZ0RonROgwjvV6JBxPFmwDyy0gOYpHJCsLaeHHEZTSHnkawnrAqr0LDBptELV7JpEoLovOigDJigWMFi9ACkmiTssYyyzoUh2xI70SWkvSexHXubvnDgF-rOnESz-wkOI0ljMgYzyiIAyiHKtn8ropNPr0tZ+2FogGEKDP6QwRi9KM6q7QPoHDwwclBh1cJ6aOrBY48HjonTIO1y5t2Ch3LuEVRDYgkI1UGKA7wQHwPMTB7ocHJAAQSO8d40iCAXqWeMRVG5gEYL8DIrsFhWVLEPF0kAMjREWglNKXpPDsEMP0CgsJO5bGirw-hLw0iIUoYhOkY9EiZD4UtQRIBUKoRrNuUIQA

**Comment by mpiannucci** [comment]
Thinking this probably has to do with the alias for currents or something

**Comment by ndellicarpini** [comment]
This is happening because there is no elevation included in the request, adding it back fixes it. Should the validation tool just use the map's elevation? Should there be independent controls for the elevation like in the compare tool (we have the time control so I'm not sure)?

**Comment by jamesdoyle21** [comment]
It should default to what is on the map, but we should let the user change it in the validation tool. Similar to how the timeslider works
