### ISSUE TITLE
LOOFS and LSOFS Water Tempurature 3D Layers Elevation Slider Labeled "m" Should be Sigma

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#497]
Both of these layers are between 0 - 1 but labeled meters. Should just need to change the label. Or we could convert to meters to match the other water temp layers

https://dev.oceansmap.com/ott-coops/?permalink=N4IgtghgDgQjD2APEAuUB9Azgd1aANgHYDmqAtAJwBMAdAMwAcVAbBQwAwCsF7TVA7ABoQ+CABdUAFmb0qARmaKmDOv0YMAvsPSEApnhElyDSTTk9WzfgrrsKchsNESUkijV7s63uhWYLmTkUNLXBoAGUxAE98fTQQAEsAE1QQCAAnAGMAcQTMABV4KHhidOgACwTMkGFCCDA4kELi0oqqmpAxcoBXMAAjOoT8VPKxMShMFAB6KcxddIA3eZoMzOI8+EJ8BL0aTPgwKdX1zCn03UwxWfmFqoupgHV4dPwk9Gb4dABZaCmfqHCN3mUzEQ10U3YEIhHUuMTioCW6UwCU2qEcIEw8G6WQuBjERRKZSglWq8WiUEaZUu8w6oNimFQAG0QKNxpMZnNFstjhstjtdHsDkcsiczhcrpzbpl7k8Xm8Pt9fv9AVz0iCwVNgAAvDSaqK64CIDQgAC6wjpunCCS1cSoQWE4jE6QSfW6oNRKBAAFFMM7BAACbIZMA7APZL0wADCAHkAwA5aMAQUT-rj2QAIpGAxBCEl-fAuvN-ftCE6XW7ngyQk4IFF5gyUIzQMlUviWkSSbSohTUlSxDThJjsdLWwTWsT2sIQ4QtfADqh2FOIIhZ-OUFQqBoTdWQNgwJhAWMdsQG6A6mB0FB0ug6G9sDsUvEW57umR9mBinpS+h4AAzdD3rm6DlLoCTEKM6AQH08BLOgpRYrmKALG+Byfro35-gBD7AaB4FiJB0GwfB3S5mQxFQDC0SxKkUAZKCmT0h0+z4M8AAKECxGMjR9BkfSnEkui-hA3T4BINZ1uk0a0ZkCTRKgcjsIuGJlgJC7CGUJDwuAOxqWEyCuOwoTTrpkD6ZISkCUJIliF8OkoBZgnCaJPxmQ5VmiQAqmu4CzB03TeYcDLmmUv6-lUtmEOQ7A0IEvDBRAoXhcu8mmPwnDCOhUGxAASjmxBxE63S6BldR9LE+QhWFmQADJgaMqCFcVICZWVuiRps+LYg2Qn4HM6l5bo+RVAA1g2jKLgpghUIutiCOZZogMxzy5R+qQAFK6GJnQQEMPzEIQsndKpKA9X1YT7YdAnVVBujDCdHFnS15U7fge0HWIR1xKdTVPW18AsekK0USgjUlVlloqceDXpEVYOtW9l26NdfS3ag31w7E7HpPRjEgzDTW0djVS4+jICEzjujpuhyJySgzCSMI5PE5a1pxHINDpWTdHM+EFK6I+VCM9zDFI+hxBdClQtEyLuW5gceiYA20WKZzTMi+1AMNrulT9iAoSEPAmDoLEf5G7dugLOIKKEOgYD4PguBPo+IA2mI4gHPbuCDlRlIQNS6RMf9bEcZtuuen2wKWU5W2iBJUkQDJtMKUplzOsdSkaflBjGSg7PsMwS76ezVCSEZdl58wgt6fJNBUHQnNR9ZEW6Y3znJeuwit2IXlgKkvfCP5veev3nSVeF5ceJX8WJZkLk13XnO-bLWd47DzWleVY81XVLig+v4PtaWWJItDa+Z4NI1jRNU2CHQC1LYD9TAyAZVFR0v0a8tT+n01bu7RAF0PrHVJpAQBn1kao3ur1H6G9BovQRkAr6D0YHg0iGnKGUDHqwIQeAm6d1vr60NsbMA5RTboHNpbd0Ns7YOwMM+F2m13Y0K9spOEvY-b9gDsIB+7FOJhxABHNUXcOix3mPHROUR5KKW9mnOIGcBrZzstFdEpkFw0AoKXKcSiaAcDkAzau9l1GSEkHITujkm5KLMe5Gy7cq5dx7n3PyAVaRb2boY3R+inQJSqnPQxGiTEY10MvAq+NAkVW8VUWqeEf6BMPp1E+q8mrnyGpkUaTJr6CzvtwoOj9VqelfvoWJOSgYxO2v-MBwDkFLgqUjPBaMqn71avkeBAD3qfXqdAwJaDkgYNJr9HBV06mYN0IQo2mRoK-iNreAC4h5joH7B+eY4hsRaXoQsii3s2Hhw4QORaOTeGh19v7KYwjxJiOkrJSRudpHKVkbpc+ijIr2ULqgeuZcnlKVUSgeuVjo5uLcn89uPyQD2O8pGJxQ8QDgunj4yxo8ImzyBYvWBwTSm-XCTPKJ9VElFKPl1UpyTL7pMEOlSach0rTSmulWa9dty1CIUkCZUy7yzOvOspZH1zh0OdusyiWyBE7K4XsgGByuLsOOackQtZzkJ0uVIlOKk5H9U0o8kySL3lqv0sCru-zflNyRXqzyYKIWpGhfCmeurzU+INY0nKCicW2sGlvLFu9QmOricfBse9CWpKviSwQZKKWLjtLfGanA6UgANkbYgBwyHTOwKy+ZuhFllE5asnlyaNmsOots-2gcRUhzFbmzhJzzGiREdKySFyk43NTskJVAqVXxBzp89VWiPkvO+Q3MtNk4U6ptaCyFZrB6mpcQiy1XiLU2qXvave6LnU7zRbAj1+KHU+rSY2RcpKJpBqpaG2+4bRk6BjZMqgN4WWcKTSm5ZXKnatkzXynNAq83ZILXwo5JbJWiKrbKmtCq7nPMbSvUALbO1vPbZq153brGWv7Vq6D0cHGemHcamF48O1WqSvBwJqKHXzoRS6pdB8OqeoJQNFJG7xr+sDVNYN1Kw0RqjfMpl56ZmXvZamlZ3L72rU2U+wR+bg7vvFZ+ntFa47VqucnGR9b7n2pA3Cr54HtIYaUwhixGG4NQcNd3VDIAR3IbHRauFk7rXYcdbhudsCMVVUI3h5dJHV3evI0Szd1Gd20b3TSw99KjaYF-Cx+NiaOM3vTTxrNsJ+OCsE+kUV-DBGluseJmVEj5UyfTsq4DKnINdo1YBtTOnYM9t8dqntSGoUmsM2h2eJnXHTpRbOt1+HMWLvs8RvFCTnOaQo367dAbd0hu84xohMk40XrmSFtN3HPS8r4x+3ZPDC3xcFYl6OyWf2peuf+2TgGHnNsU227L+WB3Fb7cVk71jysoaHUZ2FGHTNYe0xZxra9mu2da1Z9r8SvVuvXb1gNHnKWDYY0e7A+xJmsYTexzNHKuN3pmw+ubImFv7KW-NoRYmzkbblVt9LDa9sKdU4d0DBjSswbOzBi7iG9MGYq9ViddXzMzqbZ9ppC7oltdaiuzrv2XO+uJX18lnngcHuG0bfAJCxtsYmzDzjt7mwZt49m9HMW4vo9W9Zdb4icfSduTt+RTbCc5eUyTgrILTuafO+Zwdo6B56YezV+7jOnvM5XqzzeBGPtNYcx1n7Z8+eUa3QD-rwv6Oi6PSbCHQXofXqm-DzoiPlfI6FYt4TxbI6Y6lRJ39Una2Krk4bo7rb4N5eL09nVFPAXW7KzT+3rjavjvq+DSz3vwY2ciV717Pvvtke665qjguBth9pRHucUfxtstl6FvAEfMTj+l5P2PcPgA7kyNic4pZ-hDQaNSZ+00NxkHzmQaa+Rpr2XYOfjwikABaHRIBQG3+KXQUBcPMn31QQ-zAyAOHyOwSQ5-L9FJ2Bb9hB39P9j8qBf9-9FJACb9TRuF190IxAqYoAJZAMSJZJwgohqRIUGgyxqhBxzZMh+wkhwhpQ6hnR4BroJIxoFpMRsZ+ZqD5gABJdMMaSNIhXqKXKHGXJfLlXzY2MfZlBfK9CkOXQpPZDhbYBWeAkFcQCASMeQliYgAAMSGE4Rnw0CAA

**Comment by mpiannucci** [comment]
This might be a backend problem, will have to check Godiva

**Comment by mpiannucci** [comment]
The backend looks correct, so something else is going wrong:
![Screen Shot 2022-06-21 at 9 27 06 PM](https://user-images.githubusercontent.com/1832671/174923766-3d066aaf-ab40-4dee-82e6-745c0f71a119.png)

**Comment by mpiannucci** [comment]
Data catalog looks correct as well: 

![Screen Shot 2022-06-21 at 9 30 03 PM](https://user-images.githubusercontent.com/1832671/174924041-61e778ea-13eb-406c-91ab-2b5b07e675ce.png)

**Comment by ndellicarpini** [comment]
These layers haven't been working for the past couple of days, anyone know why?

**Comment by mpiannucci** [comment]
Not sure why, I just checked Godiva and they are up and working there. It doesnt even seem to fetch anything before saying the layers are broken and showing the error notification?

**Comment by ndellicarpini** [comment]
i didn't notice nothing was fetching, nice catch. The "No access to data" error happens when `fetchCatalogItemExtents` fails, so I'll look into that.

**Comment by ndellicarpini** [comment]
I think the layer failing is a catalog issue? There are no layers listed under `catalogItem.services.wms.layers` for either loofs or lsofs.
![Screenshot 2022-06-27 174642](https://user-images.githubusercontent.com/22432482/176041643-fe996a60-cb3f-4dfe-979b-4ff73491cb38.png)

**Comment by ndellicarpini** [comment]
so the reason the depth is in meters is because, for sigma, we expect the depth units to be `sigma`, but for these layers the depth unit is `sigma_level`. I can pretty easily make the updates in oceansmap to fix this, but would it be more appropriate to fix this in the catalog?

**Comment by mpiannucci** [comment]
hmmmmm it might. You would have to dive into catalog and convert sigma_level to sigma. Good first issue for diving into data-catalog
