### ISSUE TITLE
Create a Feedback Tool for Users to Submit Bugs/ Feedback

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#498]
This came up in our call with Chris and Jeff today. This moves up the priority list because we want to let testers submit bugs in the easiest way possible.

Up for discussion but the thought is:
- This tool lives in the left toolbar
- Asks for the user's name, email, and comments
- Submitting the form sends an email to me (james.doyle@rpsgroup.com)
- Included in that email to me are the form inputs along with a permalink to the active view the user had open when they hit submit. (This happens automatically, user never sees this)

**Comment by jamesdoyle21** [comment]
Take code from Floodmap for this. I believe it will be exactly the same interface right @mpiannucci ?

![image](https://user-images.githubusercontent.com/82955395/174888390-3cd90ad9-ee76-46c6-a1e4-e3c094fab460.png)

**Comment by ndellicarpini** [comment]
We already have that form for ott under the little carrot in the top right, but the automatic attaching of the permalink in the email is an amazing idea, should we just keep everything the same & just attach the permalink?

**Comment by jamesdoyle21** [comment]
Yup, exactly. And bring it to the toolbar so it is easier to find. @mpiannucci let me know if I am missing anything

**Comment by mpiannucci** [comment]
yes @ndellicarpini its the exact same tool but it will auto send a permalink of the current map with the feedback and be moved the sidebar with the new name of Feedback (last part only for OTT version)
