### ISSUE TITLE
Particles appearing where there is no data

### ISSUE THREAD

**Issue by ndellicarpini** [asascience/ott-coops#499]
Easiest to see w/ NOAA Puerto Rico Wind on the OTT catalog. Random particles appear within the layer's bounds, but in areas where there is no data. To keep accurate with the other types of layers, there should probably be no particles there.

Barbs:
![Untitled2](https://user-images.githubusercontent.com/22432482/175049149-703cb777-e867-45e2-9118-1b28bf57500a.png)

Particles
![Untitled](https://user-images.githubusercontent.com/22432482/175049164-1ca24c20-0607-48ef-aa7c-720286464fa5.png)

**Comment by mpiannucci** [comment]
Noticed this too... not sure why its happening but def needs to be looked at

**Comment by mpiannucci** [comment]
For some reason when i autoscale PR layer now (after fixing https://github.com/asascience/ott-coops/issues/494), it looks good, but not sure why it looks bad still with default scale

![Screen Shot 2022-06-22 at 11 29 37 AM](https://user-images.githubusercontent.com/1832671/175071492-d0df450f-9230-4664-87ca-e004b3f1ec70.png)
