### ISSUE TITLE
Integrate Tides, Currents & Waterlevel into One Display

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#5]
**Google Sheet Row Number:** 12

**Want to be able to:** Know the relationship between the tides and currents
**So that he can:** help provide a water level forecast

**Does Oceans Map already have this functionality?:** Yes [KK] - this may be solved - you can do a TS plot of both parameters and turn on water levels under current vectors on the map"

**Located where in OM?:** Inherent?

**Notes:** Yes; might need to do some work to ensure that vectors always draw on top of scalors (current vectors on top of water levels). This exists. Let user know how. Teaching solution. Make sure layers dont cover others

This task is similar to the tasks asking for a clearer display of forecasted vs observed waterlevels

Example: https://tidesandcurrents.noaa.gov/ofs/tbofs/tbofs_mcf.html

**Comment by nguyandy** [comment]
Be able to control WMS layer order.
Vector layers on top, etc

**Comment by mpiannucci** [comment]
#16

**Comment by jamesdoyle21** [comment]
JH - The effect of currents are already in the water level forecast coming out of most circulation models such as ADCIRC.  Do we have the option to display water level from one of the circulation models?

**Comment by jamesdoyle21** [comment]
I am opening this back up because we need to make sure that vectors are always plotted on top of spatial layers. In the example below, Chesapeake Bay looks good but Delaware Bay currents are covered.

![image](https://user-images.githubusercontent.com/82955395/127046287-252536df-a58a-4e3f-8f73-4a440a9ab0a5.png)

**Comment by mpiannucci** [comment]
This doesnt work when layers are loading, only after they have finished loading. Needs to handle pending layers the same as current layers

**Comment by mpiannucci** [comment]
SO this only happens when the first layer is still marked as pending. If the priority layer has finished loading, then everything displays in the correct order. Otherwise it has to wait for the first layer to finish rendering for some reason to update the queue. Need to track pending and current ids both.

**Comment by mpiannucci** [comment]
Should be fixed now hopefully

**Comment by cpaternostro** [comment]
I just checked with CBOFS and DBOFS, water levels (WL) and currents (CU).
For CBOFS:  WL is above and obscures CU
For DBOFS:  CU is above WL working well
[image: image.png]

--

Chris Paternostro

https://tidesandcurrents.noaa.gov/

(w) 240-533-0587

**Comment by jamesdoyle21** [comment]
@cpaternostro what were the exact steps you took when WL covers CU? I can't seem to replicate that bug

**Comment by cpaternostro** [comment]
Click Data Layers -> Under Currents: Click CBOFS then DBOFS -> Under Water
Levels:  Click CBOFS then DBOFS
I replicated it on Firefox browser

--

Chris Paternostro

https://tidesandcurrents.noaa.gov/

(w) 240-533-0587
