### ISSUE TITLE
Display full directional data in plots, allow chart zoom

### ISSUE THREAD

**Issue by nguyandy** [asascience/ott-coops#501]
- disable highchart dataGrouping
- add highchart zoom on x axis

**Comment by mpiannucci** [comment]
Taking this one cuz I have a little time to fill

**Comment by mpiannucci** [comment]
Taking this one cuz I have a little time to fill

**Comment by jamesdoyle21** [comment]
What was the change here?

**Comment by mpiannucci** [comment]
You can zoom charts now by clicking and dragging the region to zoom, direction is plotted as scatter plots for non vector directional data, the arrows now show for every timestep
