### ISSUE TITLE
Create More Detailed Error Messages for Validation Tool

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#507]
Jeff brought this up today. Whent he user selects a date range in which the comparison model has out of date data, the validation tool just spits a generic error message. It would be helpful if the error message told us what the error is. In this case, OceansMap knows the data is out of date and when the closest data is as it says in the legend. Can we create a similar error message for the validation tool? Something like, "Error: Station ___________ or Comparison Model _______________ has no data for the selected time range. The data is valid at date ______ and time ________. Please select a new date range or Model/Station"

![image](https://user-images.githubusercontent.com/82955395/178569537-368113ab-97ff-49a6-a2ea-95f41c102083.png)

**Comment by ndellicarpini** [comment]
I don't know if it can be done bc I haven't looked at the returns from the validation tool yet, but I'll try and match the error system in the observation drawer (out of date | invalid location | generic error)

**Comment by jamesdoyle21** [comment]
@ndellicarpini what are the options now for error messages?

**Comment by ndellicarpini** [comment]
There are now these warnings (warnings do not let you retry)
- No comparison data available at this location
- No comparison data available for this date range
- No baseline data available for this date range

If the error is not one of the above, it defaults to "An error occured" with a retry button.
