### ISSUE TITLE
[data-catalog] index catalog output to redis 

### ISSUE THREAD

**Issue by nguyandy** [asascience/ott-coops#511]
Add feature + flag to data-catalog that will index the output catalog to redis.
Currently only supports elasticsearch indexing.

- to run alongside the OTT deployment for NOAA

**Comment by nguyandy** [comment]
Will also need a new ott-coops pyxms file that points to their hosted s3 tds stack.


edit: and if the tds stack is running on the same server as OM3, then  we should have both stack on the same docker network

**Comment by jamesdoyle21** [comment]
@nguyandy can we close this?

**Comment by nguyandy** [comment]
yup!
