### ISSUE TITLE
Include Observation Station Data Parameters in Search

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#514]
When the user types "Wave" we would expect CDIP stations to populate in the layers list but only NDBC and HF Radar Waves are populating in the Point Obs category

![image](https://user-images.githubusercontent.com/82955395/179829669-d682c8df-b541-42f6-a840-93508afd927d.png)

**Comment by ndellicarpini** [comment]
Data parameters haven't ever been checked when filtering the data catalog, but it could be a good feature.

**Comment by jamesdoyle21** [comment]
Why does NDBC pop up then?

**Comment by ndellicarpini** [comment]
If any of the stations contains the search terms in their name the station layer will appear:
![Screenshot 2022-07-19 152020](https://user-images.githubusercontent.com/22432482/179831547-70eac0fd-8291-4bc1-bbb4-273d1fe7bf4b.png)

**Comment by jamesdoyle21** [comment]
Ahh wave is in the station name. Gotchya. If we can include data parameters in the search that would be great. Is that much effort to implement that?

**Comment by ndellicarpini** [comment]
Quickly looking into it, it would be pretty easy to filter by what's in the station tags (ei. `salinity` or `sea_water_temperature`), but to have it accurate with the actual data parameters seems like it's probably pretty difficult. 

I could be wrong though, I just did a quick check.
