### ISSUE TITLE
Add Warning Label Detail for Out-Of-Date Layers

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#515]
We want to include the data valid date and time inside the warning notification that pops up when the user selects an out-of-date layer or active time. We had user feedback saying it is too hidden in the legend

![image](https://user-images.githubusercontent.com/82955395/179830919-a9da5dd2-17f9-47ca-a016-614c5f5dcb16.png)

**Comment by jamesdoyle21** [comment]
To clarify, we want to keep the detail in the legend the way it is currently

**Comment by ndellicarpini** [comment]
is this good for the notification? I wasn't really sure what to put specifically
![Screenshot 2022-07-22 112145](https://user-images.githubusercontent.com/22432482/180471673-dbf0897d-b638-4f16-bc78-153bdc98fe7c.png)

**Comment by jamesdoyle21** [comment]
Yeah that looks good. Won't OceansMap sometimes show data ahead of the time the user selected? If so, you would just need to change the wording of it.

**Comment by ndellicarpini** [comment]
maybe I can cover both past & future out of date by using "was last valid on ..."?

**Comment by jamesdoyle21** [comment]
Or even just, "Displaying data on: date/time"

**Comment by jamesdoyle21** [comment]
Or "Displaying nearest valid data: date/time"
