### ISSUE TITLE
Create Option for "Show Only Data Layers in Window" in the Data Layer TOC

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#52]
This will be very similar to the checkbox option in the EDS Viewer

When the user zooms into an area on the map, the layers with data outside of the viewer disappear.
When the user scrolls back out, they reappear.

@cpaternostro This is what we talked about where we only show data layers that have data in the current map view window. I asked a few others here about that and we like the idea.

We also want to organize the Data Layers in the TOC by data type, not geographical region.

**Comment by mpiannucci** [comment]
Every data layer in the data-catalog exposes a bounding box region defining its coverage. This should prob be a high level option to start that automatically filters down the data-catalog as the user moves around the map view
