### ISSUE TITLE
Search not Returning "Water Level", "Water Temp", "Spatial Obs" Layers etc.

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#520]
It looks like there is an issue with the search feature when the user is looking to display all layers in a category that has a space in it. "Salinity", "Waves", "Currents" are fine, but when the user types a space looking for a category like "Water Level", OM returns no layers

**Comment by jamesdoyle21** [comment]
Search "water"

![image](https://user-images.githubusercontent.com/82955395/180788289-2af368e8-23fc-4a2c-9b30-5298a3173ccf.png)

**Comment by jamesdoyle21** [comment]
"Water level"

![image](https://user-images.githubusercontent.com/82955395/180788410-bfe3ef18-970c-495a-93d5-4fa203ca883f.png)

**Comment by mpiannucci** [comment]
Generic search metadata ticket
