### ISSUE TITLE
Units Issues

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#523]
Few issues here:
1. By default, units are set to metric, but it appears all layers (with a few exceptions) are showing imperial units in the legend by default.
2. Changing the units to imperial changes everything except the depth slider which is still labeled in meters, but showing feet
3. Autoscaling confuses the color displayed on the map

**Comment by jamesdoyle21** [comment]
1. 
![image](https://user-images.githubusercontent.com/82955395/181037061-cfcc6376-d900-4cd6-9701-52cb73cc3252.png)

**Comment by jamesdoyle21** [comment]
2.
![image](https://user-images.githubusercontent.com/82955395/181037643-c7594d4f-e9cf-4acd-9ad8-d4f0b8f9a945.png)

**Comment by jamesdoyle21** [comment]
3.
![image](https://user-images.githubusercontent.com/82955395/181037873-0c49681d-901d-4b19-8147-7750ceae44ed.png)

**Comment by mpiannucci** [comment]
Wtf is happening with this lol

**Comment by mpiannucci** [comment]
This is high priority, right now all the legends on all the OM3 instances are incorrect.

**Comment by nguyandy** [comment]
issue started after this commit
https://github.com/asascience/oceansmap-3/commit/b1573b7a2e14ec59b52af212fd71cce03d963a32

**Comment by ndellicarpini** [comment]
1. legend issue was from https://github.com/asascience/oceansmap-3/commit/b1573b7a2e14ec59b52af212fd71cce03d963a32
2. elevation slider issue was from https://github.com/asascience/oceansmap-3/commit/e6c44aee2f43621aae56df54d729d9bd68ae290f
3. This might be a catalog issue? the autoscale values are being pulled from the catalog item correctly, its just the `metadata.scaleRange` for cbofs temp is `[9.11, 18.45] C`.
