### ISSUE TITLE
Change NGOFS2 Currents Vertical Profile Plot Label to Match Timeseries Plot

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#528]
"U Eastward:V Northward-Group" should be changed to "Magnitude of Sea Water Velocity"

![image](https://user-images.githubusercontent.com/82955395/182447642-6db40cfe-8dcf-47c9-9064-d0aa107ce3bb.png)

**Comment by jamesdoyle21** [comment]
This presents the larger question of whether "Magnitude of Sea Water Velocity" is what we want to display here. Stations just label it "Current Speed"

@mpiannucci if Jeff is going to focus on this anyway right now, maybe we ask him to look through every label in here and come up with consistent labels for each data parameter. These one off fixes will just keep coming up.

**Comment by kvmartin001** [comment]
This has been resolved by https://github.com/asascience/oceansmap-3/pull/574
