### ISSUE TITLE
Change Model and Observational Wave Period Data Labels to "Peak Wave Period"

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#529]
There was confusion about data labels stating "mean wave period" and "peak wave period". Hold off on this issue until we tackle the OceansMap renaming of data labels across the board, but I want to get it in Git so we don't forget about this. From our emails with Jeff,

"Correct, those are not the same thing. But that’s not what the buoy stations provide, that is just what oceansmap is labeling. 

Looking at the raw Model data, we are displaying the model field “Primary Wave Mean Period” which is the mean period of the waves that fall under the primary wave components spectra. One step further, looking NOAAs own GFS Wave product viewer, they even call it “Peak Period” in their own usage: https://polar.ncep.noaa.gov/waves/viewer.shtml?-gfswave-latest-atlantic-tp-

![image](https://user-images.githubusercontent.com/82955395/183944607-97fd9fc3-8c1d-49ad-b8a4-399f3b1d9a9f.png)

Looking at the Stations (NDBC for example), they don’t report a “peak period”, but they do report a “Dominant Wave Period”, which the period of the swell spectra with the most energy, which matches the above definition as closely as we really can with what we are given

That’s probably as close as we are going to come finding comparable data between the two and as a user that would line up with what I would exapct to see. The confusing and incorrect part is that oceansmap is labeling them differently and its confusing. That part we can (and should) fix." -Matt

"I fully agree that dominant and peak wave period are one in the same!" - Jeff

**Comment by kvmartin001** [comment]
This is resolved by https://github.com/asascience/oceansmap-3/pull/574
The label is now Dominant Wave Period
