### ISSUE TITLE
Create Data Catalog for OTT Deployment

### ISSUE THREAD

**Issue by mpiannucci** [asascience/ott-coops#53]
All versions and features of OM3 require a data-catalog configuration to declare functionality and available layers for the app to take advantage of. See Chris's spreadsheet containing the models of importance.

**Comment by cpaternostro** [comment]
List is available here: [CO-OPS viewable datasets](https://docs.google.com/spreadsheets/d/1RvX0YYal3B4JmVhwKPTWLajVL70lSIoYPZePeaOIUqo/edit#gid=0)
Note:  This is not the final set of data sources.  CO-OPS management will have to sign off on displaying data from other parts of NOAA.  @cpaternostro is working with them to use the complete set of NOAA data.

**Comment by nguyandy** [comment]
Thanks @cpaternostro, this gives us a great starting point!

**Comment by jamesdoyle21** [comment]
Thanks Chris!

**Comment by mpiannucci** [comment]
Catalog is created and deployed, any additional changes can be tracked in other tickets as long as is functioning correctly
