### ISSUE TITLE
Validation Tool Not Showing Comparison Model Data While Obs Drawer Is

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#537]
Looking at Currents with a CBIBS buoy compared to CBOFS currents, I am getting the comparison plot in the obs drawer, but no model data in the validation tool. This has happened to me a few times recently.

![image](https://user-images.githubusercontent.com/82955395/185620952-19441353-37a5-4ddc-aa50-5aba68884f52.png)

**Comment by jamesdoyle21** [comment]
https://dev.oceansmap.com/ott-coops/?permalink=N4IgtghgDgQjD2APEAuUB9Azgd1aANgHYDmqAtABwDMAdAKwCcADAIx0AsTHD7dTATABoQ+CABdUVWgzp0WTdu34yuLdgF9h6QgFM8IkuQDsTGgLoV2ANhZVr-au2GiJKKgxrubVI-35TeAXVNcGgAZTEAT3w9NBAASwATVBAIACcAYwBxeMwAFXgoeGI06AALeIyQYUIIMFiQAqKS8srqkDEygFcwACNa+PwUsrExKEwUAHpJzB00gDc5mnSM4lz4Qnx43RoM+DBJlbXMSbSdTDEZufnK88mAdXg0-ET0Jvh0AFloSe+oMOuc0mYkGOkmTHB4PaF2isVAizSmHiG1QFGEmHgXUy530YkKxVKUAqVTiUSgDVKFzm7RBMUwqAA2iARmMJtNZgslkd1pttjpdvtDpljqdzpcOTcMndHs9Xu8vj8-gDOWlgaDJsAAF7qDWRHXARDqEAAXWEtJ0YXimti-DoVmE4jEaXivS6IJRKBAAFFMM7BAACLLpMDbANZL0wADCAHkAwA5aMAQUT-rjWQAIpGAxBCIl-fBOnN-XtCE6XW6nvTgs4IJE5vSUAzQEkUnjmoTiTTIuSUpSxNT0Zjsa38S0iW1hCHCJr4PtUExJxBEDO5yg-OpjdWQBksWdS388vF6lSoCl+AJ+GQmBQyCwGHkWPwUEwmM-TC+mAAtdqQKCH4-9lAABKObELETLnn4V43iwRh5Aob5vmYL7fsIkGXteZD8Cw8HsIhL7IV+JrCDuaR7mI6Y6FAnTzsIXSEPEYhhJEVJgCk9RllUi5QAAMrW9b6HsEAXFsugNs2ySekJIl8vSNR1A0kbwMJYiiTiZrdg08AIqIkQ0qCACqQE8SkkwFmIZB7IUJzQPEkxQGkSCRAA-Fi+AALwsuMUxqnSNDwFKOaYL+AoHNJql8hq2oaoaurqDQUCGCEhDwJg6AZL08AAGZpVQrykeR4kJJJIApWlGXZbl+W7jopZyR0mkpBk4gQPgxRkB1UCRIgYD1bMozbMQ4lbrmvQZOl8D4DEGTuoQ+gtp6o3jXsU06DNyJzRpPZSS1bXEB1ZBFNsYjRr0fU6ANJDDSEGUuuVk3TbN80lbdZ0Tat60oltDTNWIrXtZ18DHad52XUNeBbmUWVpNgECLPdH1PXEC3MtDsPw+9j0bV223brtAOHUDpYg9CF0gldEMhFDaRYH9s0I1jHoScM0O0+IG0M2tT3fU1+P7YDwNnaTYPXSRiTxFAmNc9jyMveLksrYzm0Nbjv3-fzhOC6D5Pg2gW5WeMUufXNstNbOhuK9LX0qz9fMHUdxNC+iZODddIQYmk-aJHxdZpAAkumDZMmV6WZTl6B5elNV1e04VqfVS1G9z269HdSfY8I1Po+c6fW9TbP07nysZPLRex+bnPG8RICJC1kZ8wAYoM-ZpBDwjwGd1zsxsAAK6QKS3QelaloeVRH1VkbVYj1T3Bb7BAGQHQVU-oHDcwQGBWDkjoySmiAHcSt3hBKW1iL6CHFXh5Hy8x56ZSYPgAAUdBGAG8hMAApG-VAfwAlO0s88SQEXh1Xojo5iRHQPMSa08UgAGITDyCsAwABc9gEHQgPEGm-YwDklKGILEDQ4E6CyhkCgFAsqoKAQvJeOgppYHiMQWo+BaZ7mIDRT0cDehZU4FYLiIBAHzxAWQTBNMHLnEwIQ+BWUsoUCYBAXoVChFL32FAYSaUyg6AgOLQwnC8ovjkUo9BHU9i4PUegKAjEMhlGkVlKgOgXxGJoSY1R5jHJTXgXQHQiCmBOOETfMQq8EQbx0OgcWZwq6cM4OwHQ3C-FL2joEtepRN6YG3iVBBGROBxOEII4xZAXCMS6IkIhiQsoQCygwShuS0HOIKRsNYBCSnwIYGU2RvianUOEbMCA6BYYt3QHQrmzpmosJLIkLo60bhRHgdw7JRh4kdR6X08Qcx0DQx0DoTUg0LFE1cCAOBfBsnVIEbU7pWiVkDMwK1bYjE9KcLkWAmRiyyDLP6WsnBeDxBSKiUwBgCiTl5LqW81Z2CdC4PXgQs4q8uiIHQCwWxDArCOM6copZWjdCjBiBYxyijOEyLkVlBZqL8kYlEGInMdD0plHSJvAJ8CfFUARSSup2Btj5QqB4zhBiBB6BZcItluZ1mOTAGErBVsTYHLkVYCAKLTldIOoK14aTNkZIYGQrKJCXlKq3qq9A2V0DEC6BcWx9jHEhF-JGLYGQADWXpFiln0EQYgfFXAEHEJICgZgpD8FfgYUgKAyBGCsJ4HwLAKAhAdm6kAyAUBGAoAwYQ9z2AUBYCETV3yzhB3db7Jqqc3qWyroOLEUoUgBQxcFaAKBXqV2TmSBoDctFQr5SAByhQ5gghxKSRqnoo0k2EEkKe8QsrxGpJ6IF-DdJzEPKpRSmjrnkggDanQ-oYC1lXV0eALF-SP0jDAP2MAwj-zNIxGIKQJ3tBcJ671VBfXOA9EGkNUgjDhuEGo8iea06FuTpiMQtcvaoHKfgWY7c3T-p3pGCszzPSPnaJUDYcYFJlrAFQb4aRl3+xLO0ByR50iRBPk8FIOh2AsAgCwfhsxxl4YI63T0Mj6MnJbiCajk1COeg-B+bD-cOICU9AyAAOiARMWD-Q9yzZIs4gnBCCeE2kf0eRwVfObVJwTkHJ6ln9OmcVxsVMgDU+Rf0YR0m6aUrmSZIJpmRF02EG5DEoi6fuKC+TinIWEIc05hTEL8FueqIJ+47LNPadmju6G+xf4OYC0Z1VEXcyBmNWIQTxoQDBE3OoIAA

**Comment by jamesdoyle21** [comment]
This is actually because the station data is mm/s. We need to make sure the units are the same in the validation tool

**Comment by mpiannucci** [comment]
Confirmed those units are borked. 

![Image](https://user-images.githubusercontent.com/1832671/187266212-6eb52c23-7038-4893-8dac-98e1204bd55e.png)
