### ISSUE TITLE
Expose all tools to menu when using mobile view 

### ISSUE THREAD

**Issue by mpiannucci** [asascience/ott-coops#54]
Currently, only the first defined tool in the configuration file will be shown using the right drawer on mobile. Need to figure out best way to expose all tools for mobile users

**Comment by jamesdoyle21** [comment]
@cpaternostro hello

**Comment by cpaternostro** [comment]
Yep, that mention ended up at the top of my email list.  Thanks.
Next I'm going to check if this email is added to the issue.

--

Chris Paternostro

https://tidesandcurrents.noaa.gov/

(w) 240-533-0587
