### ISSUE TITLE
Import Virtual Stations Causing Crash

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#542]
Matt Edit: Crashes when clicking the import button

**Comment by mpiannucci** [comment]
![Screen Shot 2022-08-23 at 11 33 36 AM](https://user-images.githubusercontent.com/1832671/186200250-4dd9ac36-8075-43d1-99a2-9ff603441ee4.png)

Its a problem rendering the react-papaparse component wtf
