### ISSUE TITLE
Remove All Tropical Cyclone Layers from OTT Instance

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#545]
This is a conflict of interest for them as they have other software for this.

**Comment by nguyandy** [comment]
Removed from http://dev.oceansmap.com/ott-coops/
https://github.com/asascience/data-catalog/pull/1032

**Comment by cpaternostro** [comment]
Please remove these 2 HFR layers, because we will add HF Radar data in the FY23 version:
MARACOOS HF Radar Stations
MARACOOS HF Radar Waves

**Comment by cpaternostro** [comment]
While in the catalog:  Can you please reorder the major catalog headers to be from top to bottom:

1. Point Obs
2. Currents
3. Water Level
4. Salinity
5. Water Temperature
6. Waves
7. Wind
8. Ari Temperature
9. Air Pressure
10. Ice

**Comment by jamesdoyle21** [comment]
@nguyandy I am going to put this issue back into In Progress
