### ISSUE TITLE
SFOFS MLLW Water Level Layer is Labeled as Tampa Bay

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#546]
From Chris, "This Layer states that it is TBOFS WL data, but it is really SFOFS WL data. The extent, the data, the mapping are correct, the name is wrong. "

https://dev.oceansmap.com/ott-coops/?permalink=N4IgtghgDgQjD2APEAuUB9Azgd1aANgHYDmqAtAIwBMAzAHQ0AsADFQJzOMCsNVAbDS5UANCHwQALqhoB2BoL5cKMmRU5tlAX1HpCAUzxiS5ahTps+rNjQps2ADm69R4qShr2GjChUYyqMswUfKqMmtrg0ADKEgCe+AZoIACWACaokVAARkhRknr4+MkSBqKEEGCJIACSkMR6AE6xIKISABYArmBZ5cn4GW0SElCYKAD0Y9DJdJDZSHQAxvBgY5hxCZhjAG4UY7M5iKv5hcV6ZFtsYxJ9eptUXHxjzE9PLSBr8VX7SOOr67d7aAHI4lE4lc5sEARBYdBoNPSECQAWWgABVkpU1nooBkqKwqGRmGxCTJUcwaChmMxKcw6FTmAAtN6zdGYkpQABKEBIiQA2iA8VQCUTCYwyYwaTS6VSmaJBcLicx7OLJVTpYyQABdUQdQjFKKxLFgDKVCQNZILZnQAAyEFijUwhiWEDWRX0jqSaQyztdyXdb3KlQyAGF4C6JG7bm84lAqvAto1xM1WjcAKoc60ZMbwIZkJbwEaTKDJMZQBpIWIAflh+AAvINhqMJtcNnR4As9NzMLNFssxj6I369GNgAAvTQjxAT4CxTR0KDGaHwAuYdBLQp6BbXeCEQxelAgfMjNfwDdb5I76OxWPeyQQfDwYhkZ9QeB+iQAeSyjtEmD0Qz9YgPWAcJREgc1rkqMgEUtT10gPcDigxM4YIDCoqhRCDkIAAgACgAUQAOWDABKK8bwPeNEztaM0wzAYhhGX5iGSTBFjaCAGiGZd8DYwgwwgOhiHjSYGgWFjNnhNZVkaLYLQBJFgyiMYiODD9CEjMYUSgKJZMaMY9EQCRNkwpDKmDDiuN0ho5I7LToj0hoDMQV8uMrVJi1rCwADIADN4AaSAJFrBdiG8s0uygTiEWCs0Oj0bysgOWtgCSpBoJGJ8PC4GRNG8qIOVrbKZG8jEIHqAqivsHLvKTB1a0wNp4GwABSGgAEFmBaqhgwobrgyofqaH6xh+q4fq+H6krfNrMr6jeTAFjaPQgwPCQwEdCJ+NXTBfJyXzVwKPQtkkC9CHQMBClwOCMm2rA9vgA70COk7t3Oy78FwVpryqBY7wfJ8X1iRANoW-9rhIYDwgiTAApKVJbXtBpqgAEQ9flEMglDCEtMp4B2h6npe06dwuq63gHSMf0PZdj3XBJz0vbUQFSO9g3+x8ADE+hKBpDDWc1jAPN40uQFBeV5ShaC8KxOB4fhBBEWR5AeJQVDURgNBkbVJdMcxLHYGw7EceXhA8LwfD8AIghCXxNU1cIgA

**Comment by kvmartin001** [comment]
This was fixed by https://github.com/asascience/data-catalog/pull/1027
Here's the fixed catalog up on S3:
![image](https://user-images.githubusercontent.com/56608780/189666612-78cfc462-6c49-4960-b960-8eaed91f4beb.png)

**Comment by jamesdoyle21** [comment]
This is still mislabeled in OTT

**Comment by mpiannucci** [comment]
@kvmartin001 this one today too please
