### ISSUE TITLE
Create a URL Shortener for Permalinks

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#550]
This can be hosted on our side, Chris confirmed.

**Comment by kvmartin001** [comment]
@mpiannucci what stack should be used for this, and should it be dockerized? I would probably use Express and MySQL.

**Comment by mpiannucci** [comment]
It will be dockerized. We're going to use express, typescript, and I havent decided on the database yet. Stay tuned for a little while

**Comment by mpiannucci** [comment]
THis is written and the functionality is merged into the core of oceansmap. The service is not deployed yet though so still marking this as in progress
