### ISSUE TITLE
Add SSCOFS to the model data catalog

### ISSUE THREAD

**Issue by cpaternostro** [asascience/ott-coops#556]
Please add the SSCOFS data, that is still in beta form, to the available model data in the catalog.
THREDDS data is available here:  https://opendap.co-ops.nos.noaa.gov/threddsdev/catalog/sscofs_catalog.html
add all the available parameters from the netCDF data file.

**Comment by nguyandy** [comment]
hey @cpaternostro, could we aggregate this data? Our catalog and WMS service works best when pointing to aggregated data.

**Comment by mpiannucci** [comment]
Maybe we can ingest via IOOS EDS?

**Comment by cpaternostro** [comment]
However is easiest.  This is for demo purposes and there may be changes to the data before it goes operational.

**Comment by nguyandy** [comment]
Hey @cpaternostro , would displaying a single timestep suffice for the demo?
I added a single timestep to our ncwms service to test. It is a tad slow since we are dealing with 1.5GB per timestep.

**Comment by cpaternostro** [comment]
Yes, that sounds like a great idea.

> Hey @cpaternostro , would displaying a single timestep suffice for the demo? I added a single timestep to our ncwms service to test. It is a tad slow since we are dealing with 1.5GB per timestep.

**Comment by nguyandy** [comment]
@cpaternostro 

Here you go!
https://oceansmap.com/link/NdY8djNxQm-0ZFtfZf91DA
