### ISSUE TITLE
Add Lake Superior (LSOFS) and Lake Ontario (LOOFS) models to the catalog

### ISSUE THREAD

**Issue by cpaternostro** [asascience/ott-coops#561]
To fill out the great lakes domain of hydrodynamic models, the GLERL models of Lake Superior (LSOFS) and Lake Ontario (LOOFS) need to be configured and added to the data catalog.
LSOFS - https://tidesandcurrents.noaa.gov/ofs/lsofs/lsofs.html
LOOFS - https://tidesandcurrents.noaa.gov/ofs/loofs/loofs.html

**Comment by mpiannucci** [comment]
Have to figure out if these are setup on the COOPS thredds or not. If not we will have to add the aggregations

**Comment by cpaternostro** [comment]
These are the catalogs at CO-OPS.  But you probably mean the CO-OPS OM thredds servers.
https://opendap.co-ops.nos.noaa.gov/thredds/catalog/loofs_catalog.html
https://opendap.co-ops.nos.noaa.gov/thredds/catalog/lsofs_catalog.html

**Comment by mpiannucci** [comment]
thanks yeah i do mean the thredds servers

**Comment by patrick-tripp** [comment]
@cpaternostro LOOFS and LSOFS are using the FVCOM model now and are probably broken in the OTT OM3 thredds configuration. I think they were using the POM3 model previously. Regular grid versions of these are available from CO-OPS which we ingest for the tds.ioos.us/thredds server. OTT OM3 thredds is currently using the same RPS S3 bucket that is used by tds.ioos.us/thredds so the data is there.
