### ISSUE TITLE
Style of the Pins for the CO-OPS Stations markers

### ISSUE THREAD

**Issue by cpaternostro** [asascience/ott-coops#562]
These are the images for pins that should be used in place of those for the CO-OPS Station in the Legend.

The source code at https://tidesandcurrents.noaa.gov/map/assets/js/main.js and it looks like the marker icons are available via

https://tidesandcurrents.noaa.gov/map/assets/images/redpushpin.png
https://tidesandcurrents.noaa.gov/map/assets/images/yellowpin.png
https://tidesandcurrents.noaa.gov/map/assets/images/wlmetpushpin.png
https://tidesandcurrents.noaa.gov/map/assets/images/bluepushpin.png
https://tidesandcurrents.noaa.gov/map/assets/images/greenpushpin.png
https://tidesandcurrents.noaa.gov/map/assets/images/whitepushpin.png
https://tidesandcurrents.noaa.gov/map/assets/images/purplepushpin.png

**Comment by jamesdoyle21** [comment]
@ndellicarpini we can talk about this one at the next standup

**Comment by mpiannucci** [comment]
https://tidesandcurrents.noaa.gov/map/index.html?region=Rhode%20Island
