### ISSUE TITLE
Replace the OceansMap header with the Tides&Currents header

### ISSUE THREAD

**Issue by cpaternostro** [asascience/ott-coops#564]
Attached is the NOAA Tides & Currents header that should be showing in the upper left of the CO-OPS OceansMap 
Let me know if you would like .svg or .ai versions of the emblem.

![tides-and-currents-lockup-horizontal](https://github.com/asascience/ott-coops/assets/62911145/34d67d59-72b1-4daa-944c-c151939652ce)

**Comment by mpiannucci** [comment]
Also add small beta tag to the right of the logo :)

**Comment by nguyandy** [comment]
@cpaternostro, added the logo and updated the theme color. How does this look?
I found on the original logo, "NOAA Tides & Currents" becomes small and hard to read.
I have an updated logo with the "NOAA Tides & Currents" text bigger, but let me your thoughts.

edited logo
<img width="434" alt="Screenshot 2024-05-08 at 8 39 38 AM" src="https://github.com/asascience/ott-coops/assets/43226410/299c8934-f3ba-4c1a-b261-2b6b20ad375e">

vs original logo
<img width="434" alt="Screenshot 2024-05-08 at 8 42 46 AM" src="https://github.com/asascience/ott-coops/assets/43226410/bce0ecf8-2f5d-4be2-8cc8-ad33c70f2572">

vs current
<img width="434" alt="Screenshot 2024-05-08 at 8 39 41 AM" src="https://github.com/asascience/ott-coops/assets/43226410/6bdbb216-a3b5-4b0e-bce6-38f0df6021af">

**Comment by nguyandy** [comment]
Hey @cpaternostro , I think this one slipped through the cracks. Any thoughts on the changes?

**Comment by jamesdoyle21** [comment]
@cpaternostro I am going to close this issue but let us know if you want any edits to the logo.
