### ISSUE TITLE
Submit feedback button failed

### ISSUE THREAD

**Issue by cpaternostro** [asascience/ott-coops#565]
I tried to submit feedback for an error I was seeing.  However the feedback tool is not working.  Perhaps this needs to be reconfigured to work in the new CO-OPS environment.  Or maybe we should rethink how we want to get feedback.

![image](https://github.com/user-attachments/assets/8269498a-1909-4557-b315-8990d71609f7)

**Comment by nguyandy** [comment]
@cpaternostro, two questions for you:

1. What email(s) would you like to use for receiving feedback form submissions?
2. For sending the feedback submission forms, we can configure a generic "noreply@oceansmap.com" to be the sender, but if you prefer another email, we will need the SMTP config/credentials for the sending account

**Comment by cpaternostro** [comment]
You can have the feedback sent to me at christopher.paternostro@noaa.gov
Thanks

**Comment by jamesdoyle21** [comment]
@nguyandy can we close this?

**Comment by nguyandy** [comment]
@jamesdoyle21 , this one slipped through the cracks. I'll have to get the AWS SES credentials configured and coordinate with Greg or Lloyd to set up the mailer this week.
