### ISSUE TITLE
Add Tidal Extreme Parameters - Validation Tool

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#62]
- Add outlier frequency metrics

- Instant recognition model performance displays (Green-Yellow-Red)

![image](https://user-images.githubusercontent.com/82955395/124665991-6adacd00-de7b-11eb-8f04-e36b5e88100f.png)

Powerpoint: \\ri-vsq-fs-01\CONTRACTS\2019\19-P-203344 IOOS OCEAN TECHNOLOGY TRANSFER FFO MODEL VALIDATION TOOL\Validation

**Comment by mpiannucci** [comment]
That plot looks a lot like what we already have... ill try to get the powerpoint opened tho

**Comment by mpiannucci** [comment]
OKay after consulting the powerpoint, what if we just add a custom peak and min extraction, then run the statistics on them. For tides we can make it the default behavior but for the other data types you can turn it on as an option? So like very local minima and local maxima would have the statistics run, and we can export the bias and time delta or whatever for every peak and trough? Not sure the best way to make a visualization for this but I think its prob what Jeff is looking for>

**Comment by mpiannucci** [comment]
Coming along nicely. Just need to get the table working to show both x and y axis 

![Image](https://user-images.githubusercontent.com/1832671/170363729-b744f513-b81f-4858-b790-5c0046da6ea6.png)
