### ISSUE TITLE
Link Validate Tool to automatically bring up selected station results

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#65]
![image](https://user-images.githubusercontent.com/82955395/124666559-39aecc80-de7c-11eb-8732-b43022ea27d4.png)

Powerpoint: \\ri-vsq-fs-01\CONTRACTS\2019\19-P-203344 IOOS OCEAN TECHNOLOGY TRANSFER FFO MODEL VALIDATION TOOL\Validation

**Comment by jamesdoyle21** [comment]
@mpiannucci @nguyandy having this option will be nice for the demo. Can we make this a priority? It should just need a button linked to the validation tool window. If it could open with the data the user is viewing in the station plot already populated, that would be a bonus.

**Comment by nguyandy** [comment]
Yea! I'll take care of this

**Comment by mpiannucci** [comment]
@nguyandy aside from opening the Tool, you can just fill in the state from the observations maybe and unwilling auto load the data I think

**Comment by mpiannucci** [comment]
Let us know what you think about the placement of the validate button, not sure we know the best positioning of it

**Comment by jamesdoyle21** [comment]
I would say the top left of that area is more noticeable

![image](https://user-images.githubusercontent.com/82955395/135177865-9f5e057f-9e4b-4a31-bfa0-4778253c87b2.png)

**Comment by mpiannucci** [comment]
yeah I was actually thinking in the title bar of the drawer would be a better place
