### ISSUE TITLE
Add Support for 3D Datasets 

### ISSUE THREAD

**Issue by mpiannucci** [asascience/ott-coops#70]
A la OceansMap 1.0, 3D datasets should show an elevation slider for the user to pick the elevation. This is needed for currents, salinity, winds, density, etc

Should also handle default elevations, etc

**Comment by mpiannucci** [comment]
What is supposed to happen when there are more than one 3D dataset selected? They may have different units (meters vs sigma, etc).

**Comment by jamesdoyle21** [comment]
Lets discuss this in the meeting this morning

**Comment by cpaternostro** [comment]
I'm still looking for feedback from how this is handled elsewhere.  One interesting solution is the use of zslice option in pyroms Python library:  https://github.com/ESMG/pyroms

**Comment by cpaternostro** [comment]
There is a file that I learned about today that may help solve this.
In the CO-OPS Thredds server there are 3 days of files that are used to reslice the CBOFS irregular grid into regular grid segments.  
https://opendap.co-ops.nos.noaa.gov/thredds/catalog/NOAA/CBOFS/MODELS/2021/08/30/catalog.html
the files are called nos.cbofs.regulargrid.n006.20210830.t12z.nc
The **regulargrid** files are sliced to provide Z-levels and have a regular shape that may cure the CBOFS grid problem too.

**Comment by mpiannucci** [comment]
Ahhhh... I will try to load those in beside what we have currently to see how NCWMS handles it. Then (if it works), next week when Patrick is back from vacation we can see what we need to change on the S3/Ingestion side of things 

Thanks for the help so far Chris!

**Comment by mpiannucci** [comment]
We should check if the regular grid ROMS data changes the elevation units from sigma to depth

**Comment by mpiannucci** [comment]
So I am pretty sure that this new grid solves all of our problems. Here is a look at how it looks in Godiva. It looks correct and when plotting the fields version in the same GUI we gets the same distortion as we see in oceansmap. 

<img width="990" alt="Screen Shot 2021-09-02 at 12 20 20 PM" src="https://user-images.githubusercontent.com/1832671/131880642-aafaed1f-9074-41b0-b9f9-be4e01995313.png">

https://opendap.co-ops.nos.noaa.gov/thredds/godiva2/godiva2.html?server=https://opendap.co-ops.nos.noaa.gov/thredds/wms/NOAA/CBOFS/MODELS/2021/09/02/nos.cbofs.regulargrid.n006.20210902.t12z.nc#

You will also notice that in the "Height" section the units are now in meters for the whole dataset, which is exactly what we are looking for. I will forward this to the ingestion team and they will take it from there. 

cc @kknee  if anything looks incorrect here let me know.
