### ISSUE TITLE
Add coastlines layer 

### ISSUE THREAD

**Issue by mpiannucci** [asascience/ott-coops#72]
We need coastlines layer that always draws on top to match OM 1.0. Very useful for looking at thick raster layers

**Comment by cpaternostro** [comment]
I'll look around here:  https://shoreline.noaa.gov/
What is your desired resolution?  Some of these files have the smallest islands, whereas some approximate a coast with a single line.

**Comment by cpaternostro** [comment]
Spoke too soon.  
The NOAA medium resolution shoreline may be suitable.  https://shoreline.noaa.gov/data/datasheets/medres.html
It is a 42 MB shp file.  We can cut up this or other GIS files to make it suitable for your needs. I might be able to share a project with you if you have have an account on arcgis.com.

**Comment by mpiannucci** [comment]
We also already have a tile set served currently via S3 for coastlines that we use for current OceansMap so we will most likely start there unless there are specific objections

**Comment by mpiannucci** [comment]
Initial Support: https://github.com/asascience/oceansmap-3/commit/62a5f16f7a982a56d34f4363003d130a51ac4071

![Screen Shot 2021-07-20 at 11 46 11 AM](https://user-images.githubusercontent.com/1832671/126355134-83ce29cc-5dcb-4be5-ab51-b47b9a4e6846.png)
