### ISSUE TITLE
Create Info Pop Up when User Mouses Over Different Basemaps

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#96]

**Comment by mpiannucci** [comment]
More info needed please. Is this just tooltips?

**Comment by jamesdoyle21** [comment]
Yup, just like in OM1. For now it is just a brief description but we could add more info about each basemap later if we feel it is helpful.

**Comment by jamesdoyle21** [comment]
![image](https://user-images.githubusercontent.com/82955395/134048454-192f66d1-957c-40b8-88b0-71d19016c2bd.png)
