### ISSUE TITLE
When the User has 2 or More 3D Layers Selected, How do we Handle Multiple Vertical Sliders with Different Units

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#99]
For example, 3D Water Temperature needs to be separated from 3D Wind when both are on. How do we separate these vertical sliders? 2 sliders side-by-side? 2 sliders stacked? 1 slider with different units on each side? 1 slider allowing the user to switch between active layers?

This is open for discussion.

**Comment by jamesdoyle21** [comment]
@mpiannucci I havent tested this yet and layers aren't loading for me right now, did you cover this when you made the 3D slider?

**Comment by mpiannucci** [comment]
Yeah, eventually when the 3D OFS layers are fixed they will all be in meters and we will standardize to meters
